apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-service-ulm
  namespace: external-service
spec:
  interval: 5m
  chart:
    spec:
      chart: external-service
      version: 16.0.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    portal:
      open:
        enabled: false
    service:
      main:
        enabled: true
        externalIP: ${CONFIG_ULM_IP}
        ports:
          main:
            enabled: true
            port: 443
            protocol: https
        type: ExternalIP
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        annotations:
          nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        hosts:
        - host: ulm.${DOMAIN_1}
          paths:
          - path: /
            pathType: Prefix
        integrations:
          certManager:
            certificateIssuer: domain-1-le-prod
            enabled: true
          traefik:
            enabled: false
