apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:Wg+0BenHS4S+ZU7FJHWWGBgmifk4a8TYyxkjQZzInlg=,iv:Uo6H+8t/ciLib/A9WhIRawMI+ggnNsfU2iJZ4xNQ6pA=,tag:lchofoq6lXbLZpyGYzzt4g==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBSHNjd2ZMU0VDVmdiS2Fv
            VVlaOFBDMURscG1TR0dvR1NoK29vZlNXNzI4CmpEeGdEUUF3a2lSczlOdGxCUHV1
            clhhMm9TbkcxRVhwMklPQzRlaHJIeVUKLS0tIDRWTEpLTE0wWnFTYWxyR1VYbzNP
            OUpzdnNLNVpTNDhlZGxsSSswZTZBSlEKqhXuJVgTCi0BklMfr0dQwaSDIU5CeRvT
            sr0zkM11SKjHVRR58pF7EBDgq1D1PtANF83TRp4YTtzLBRZq5oabOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-08T13:12:33Z"
    mac: ENC[AES256_GCM,data:FXjjt80HpMXFaNc5SYKbNiUaVPxjM7/OVWMm7N5eAU3RM5fiq4AN+TWzeAo/3uVBW0aMaPyv/wOHQPfByIDiwqemkkSKg3BH1uwkD+pWnkSkhMHGBnwAEj/E00Cy6jxQqxFr0jmq2v7wZaaSTQrMZTuMWL7Afo/iW/tjS3ZAX7Y=,iv:Yfp8AwGagdKE/ACK0zOye0XLkT5mudBu+7Gmw4NE1is=,tag:bsyJWcaTnO5Vy9qpb00sJA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
