apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:MxmDVxK6biX8zR5qeHH/gIFPmECm25sZBLqODqG/rj4=,iv:sz3dxrwfdBGSB0VLA1R/+R5GmQumJX+Jiy1L36qM8qc=,tag:p2JMvJylFVn6ymUgbzEl0A==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrUkRBeGFkSDZXcHk5UTZJ
            YzRZQnpKL0Y5SXAyMGhFQ0NUczdZdENQYmtjClB0M0NMYUJOQ08zRm5nNmx2Rk1r
            YTFrbzRCMEMxRDRGcXgwYnNCM1E2dmMKLS0tIG00c2R0dkQweDJrS2Vxc2tpaXNN
            VEJKTjZCNjN4cHNIdUtCQWp3b3FnZjgKWSmy95ubJSUVV9jda3PoQe43h3tzF4/h
            IpptHu6KACi04GVRKE8v20TRfMM2W4YtPL3cKM2mDfUoIY+K4a6c6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-11T15:00:44Z"
    mac: ENC[AES256_GCM,data:3vv/o2zPhPjtATycKrYYQMJ++pmsMXcS0ojjJUG/9SET3Ab4TQi45NRy31FEllQygsftg1+EtMkGb4jFskn5CHDvG3aQdYrzW0LaiIxIIAvp7TNOrSZm13U8gQbhJT9+n+ZszEcpY40eCSIXKPytINAy+TgSC7l9vT9LGsmtGig=,iv:N039etgjgMzEVtOwkHLpo0drhs7J8IW4GZQG3ttc2Zc=,tag:v7uv/69tRfARyB0Gv9bOpg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
