apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:DHjJVxAThy0rZgNb6PBMtKtb1rdjT8b2HZhIn5xKgNA=,iv:rMi9Yf2Ig96xpHXQbC7soccVcujlobUlqm9Yh+37uZA=,tag:hNP+fMq8hq+ztbJ5BAjofw==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3UW5UYW4wd2REaW9jaUZz
            ejZxaHhRcXZTQnc2eS81MmxHUjM4QWRIbWlFCit0b3E5SU02NVhCeCtZSTUvWWRL
            cFlJL3JrVE9RMit4WVMyT3V1WEZrWlkKLS0tIEc5UElET2tzNGZGdndrNWhmUFRR
            ZzFDQi95QjUyZ1BQR1BjQTFvSnpqd0EKLs4kjIs1Yv3No1ATA928S+vEmcsaqaB+
            fEbvxM/IQqsekeieo2fm5+gc8qCVSDbTXgOtVIuAeTHsGs/HT/ib+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-11T15:27:24Z"
    mac: ENC[AES256_GCM,data:jBWG7wLyk9zUw9zFAl1chGya00SGFda7dswwhWJQbPdGSlBHDWXQ0fIrPdEzYXUyEQjoD6FKtREbxHcribf0cIqkRlUM307o+u0edgJ+yJLsd57cqGn0rZcWN5oeqfq+X/i/ancZsKhbx+VXukU0u3UceT7YUEiHHbAwBIa5Ud4=,iv:l53nwK2NGtldfOmqQ0JieURnljlaFTvthxy2+c6jr50=,tag:Z8HxSozO93xDqUWIJPDMmw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
