apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:NURGlc7kiBkvJ2cF3d9HTCTiuh2JFGhoi3+mi9QzzEw=,iv:s8XWCceXFY8llNY55fn5o8eARozlLnZBfPoFViF/4po=,tag:VCMLAr0y5qfoqAPYDj3F6A==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4VGZOVTFTUFRzWklUM09h
            bVNXNDZvQW1uTCsrQ2tGT0Z6SWU2TVpEQlJNCjh6ekxOS1g1TjBTdEI0SnRKQzl6
            enlidURiQ05HZUdrZW1rUjR0ajNGQ00KLS0tIDRtSUVyL0ZUdS9ZbUZlU2JvMVg5
            THFYTUxZcmVkNFY4YzJ4Z0ltMmN6YUUK2D/bwbxBQ2QSwRlx4UKOhMQvO8un05lc
            mmtuB1bRg91v/AP1djm8tR5Gzeqka9giOqoBn3UotiMiW2xnZj6xLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-11T14:48:55Z"
    mac: ENC[AES256_GCM,data:Cd2bZt6Qng/JJQ6RQwmmdxD4PJqO2ACcZQHoANyRWC5WJHi0cPaof7EVsDcKrLWcfH84/upBDikvY0L6rxmPpxaGS5SqJn6VxRIA37dTDlZsc7bDe9AP2lVERnWO+256T7xer/YZd68wZiFtG+7VECt9ZG0of7ZHZtzJAGO45E0=,iv:/VMCr9udfW2Yc5otUKqtGbRuHx7EXYYN32VBG26X6ok=,tag:vcOCrNhzl9gAziy8l8MX2w==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
