apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:Gdcz42YsRjaBIlj3CXBeWYvZq+ejmTwFOVU9hYqkqdc=,iv:tCRIsMv6jFfl9Mrv3wUUSy/1zPujnNJF7WSu/9l6Pu8=,tag:jkbBMI6uTup/86vCiSK9Ww==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBTHlBU0pKOXBvWjVvZXRU
            b3pjdVlFTzZXRGFRaDJFdzN4MG9QNTcranpZCk5Nb2FJdER6WlB0eUd5Mkd5d1N2
            dFU1UmRyLzlBWDV6UzhKNUxmL0hncGMKLS0tIDBMc1lBUHZiS3VLRzRGekQ2eUcw
            ZkFsOWU2SHhIaExPbm1nWlVQNjYwVkkKHoYhX1E0Hq9BgG0df/6pmhBUJck+d6JN
            uJ0Dl5ZA/VbvgCl5uJkcvbzjUrimmUacj5lY7G1Zc2cjEQp69k5nuw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-11T15:02:47Z"
    mac: ENC[AES256_GCM,data:KMMo81Ctezkr3IfeuBuyL0j0ytKjYrZtYNehCf/nBGbTgN0seKlZX4ucqg7ATj5m/bwxvvPz7owN1OVcZ3/iP95Dl25+2aX5AjyPwU48OXCn46qrPisx6FSk1JnGpTCZ5H+GvtsvQ+xyLF4KnQKXMl8RsBbJ/pPV+0erm6vOBx4=,iv:KJMQ7hECk+0Pz4UG4UZ5zjwf2fq84K1VRkaS29kHTgU=,tag:c1lwIN2zOvugQPYwqokZQw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
