apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:TNK5AQkq8NnnWRqJy77nzJAqdMQ14oHLjMp+QnP8MgA=,iv:3VzvCy6+CkB6n5BcPfxf0cPKgvZDq8aYTXElHZuqr0U=,tag:O7b4XN7QVPpP9NXXBVG9Ww==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYVXBpSzlWRnBmMmJ4YlNk
            ZEEySGpSYnJWUDdraS9CanR2akx1K0QzakRrCmRWQ2Z6UE1XR2N5cW5XbEVDdFFq
            TU1xSms2WXpnbjU0bWxURTJ1YXgvdXcKLS0tIDluWEF5SjhjUUplRlhOcEZObmdo
            WnNOY0lZK3VUMGx4a3NSOGFuMEFsTVEK/2yVOuO6MipoTw/wkDMVrZ0jDfUr5V3U
            TiWuJfZhIFdaQHwa24NiX+0Q647MgilcM86McoVKYSIjwvUMLYaM+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-11T10:56:55Z"
    mac: ENC[AES256_GCM,data:RktQWy9n3Y4VPb+flT+pXzrfeK2F037xhGXXe3cTAbHjbv21wmj20pcGS7l/lZw0NwkWcmuYcdl1fFbnPLNa3anx0uKzgPPYhKThgDW9JpaZ5cYjKPGhfgcP3LZeaLvsjHmDMNg9JfFHQKVUDQSCslmzHeKzESL8B5YhdKUWgsY=,iv:GJBpg92cFLIrpPLbAieMOkLuQN2bww734mYwT9GI7pM=,tag:7GG6A1r8Kn8AdYUlS6VazQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
