apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:sO8AASCe+Z/xfjo4HGX3uHH/sfoCA+5ePh3LTr5rSjE=,iv:LSUJ7y3+dhjHC5wD4KcDL4m6s91g0DEUanvEvlSFC5U=,tag:eCzEnzRHa7zg6BdZR22+vQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTYnExOHVuRVkvemRVYStF
            WnhPQmxuR1o0U3JHRzBCNllwNzNZV2Z3Q1VJCjQ3WWNWRDdOdEZvemo2azNDOVE3
            RWhuMFkwTzh1V3dCSlFlTFJ3QWpSeFkKLS0tIFpBSjhzK2FpcVppYnhaUE9EQlFo
            RTNRUk9pTHdBVitqWHZlbnZqaTlaa1UKqiWt99Sh8M1fvaycKIJILE1MyE1gdWmc
            bHI9bJ5nsL2aFyHPkVwVDt8pys4vdz5Yu2p2GCWxumTIyQy3c4raUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-11T14:55:09Z"
    mac: ENC[AES256_GCM,data:KbeZr+lPC87Yc/tMqQMJCrXJx02+pWE3m4qO48SY9H68xEO4HKuHyHJnM8bmbU/hzw3dYSdnPfDkQrJsHiMPUZavI4g/3VfqfwpztjKHBOCw/c34KIb4k9pxWO6GEEvw734Dk/W7lH6xECQAxMqOU96AmJ1cXms44AgMFt4yu5s=,iv:Opqn9jwb3Ymocl6J8Mfe2KOb8UgQA/MAqFmmsYNpKEQ=,tag:q8h94MnH487wVuvBwNzp1w==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
