apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:B4G8YXZdzDwf2spcfQ6reSoAOwp/1Hayk8UlXt/G/eo=,iv:wOICihCC9k6wLhC6+Am69WArdpTKOcOu+eD6E5fWdR0=,tag:qwAmp2QIvVGEEQA5bPIlYg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5UUM4cTI3TkZIcWo4eTRS
            bGJZL2VTS3FUQi9NWXdNUlN1Z1NWcTJyelJNClhPOEdOaTRIZ3lyL1VwdmNnc3Vu
            d0tpWldzRHJTcXZYdjFnTG1IelRsRW8KLS0tIGJpMm1TVlk1Nm9CSEhFQXVsZjQw
            ZTB0TVNzVnFUMURZQmRUQ0JzQjJjbVEKMNuUi/PlHDHQD55EWyuyytw8q1bbe8nk
            lILjoRMWGXLUgAkvsJZOWEjaum1vOQ+vwUk6ZqPTcSNLw9BH6Ywidw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-30T12:40:45Z"
    mac: ENC[AES256_GCM,data:TGLTerH1s2Lp84ku1FGToR8hioWDowoR1ndhrAC/N4XLLlOuMjerMGxFbtymDzrbsOyjI96Ty17MaE9bh8G9eXmMj/A8Yk5sKBLCa4AnN+4J7/iH4bRmGhG+frYEPa9nwvtZ4MmJ7t8yNz6x0QPfiB4TzxgWyGe5ct7r435dTvs=,iv:/lMiezq7E9EfTnmtMPP0nDEsHhMZ7zh6WLleZngdVvQ=,tag:tvoS+K6xbzM3FMpTIO1MKw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
