apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:S31FwFzAL6LbUbi+ecRapKhTnYlUbN05yxBo03+njsc=,iv:FlrWDRWxN6VFDUN/nvNCdKiWo4RtcK6NEwZbfrMSpK0=,tag:xYhEaQIQP37FkKLIUU5FAg==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiR3BPZGpVV29KTDdscnNX
            MVR3dDY4bXhHbzZyaS9lWG55c1BkMHFZTlJ3CkxyOTVvMXh4ZEpvdzh2clUwUW9u
            b2NDTER5SmZvNnFXMWI0VU9oakJyYUEKLS0tIHJUdURyY0NsVzdYdEU3MFcvQkpS
            VGtodVA3dnEzSTV5L0R0ZkNXMklpVTAKHPR+tgtFHY7DnBEMID2GfFpOkavdOman
            gCe86HOiYiGeZdwOB8oLabzlxujHmPiO5sZduzpJ6ueAXohbcS9rag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-19T08:07:56Z"
    mac: ENC[AES256_GCM,data:2orFfahdAa1FfhGOF2Qr/k1xxuT3tj7DQRA5YexaeLZlKRgaE2hdfgb6Rd1KoLky+fDVBAhMjSgWEM8qX3oQ8DY9Piq4+p7DPGgV4Opf7M+e8p7s6g9geMFNQbqOwcO0QE75jKTrOJ3GszVAqzjb7UL6AnyFUJV61h76yBeK3VY=,iv:/iTlqnO7xjXL3I7TR8WRhXCQJEE9sunRoNMEYx7A+W0=,tag:Qs8LkqvcIfx/ZbsME/5K2A==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
