apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:tRjTMSEFKqLP7xvM4YlaIAY78XzJi6x+mtfAoHTyOoE=,iv:BR+2IJL+2IJF7YQ/N609u52jxgt6KRVOUobGJNmXUlA=,tag:CgL/n9xeVWdei92Dm7QTnA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTVEVNWGl2YWNvMHlTU1J1
            QnNvRGZKbWJlSWRnUHJOMW9JYjNGZFhNMkRJCkN3aW5oTCtaaXVyWUxDNnZNdnUw
            RnlTRnlPN2s4N2x4YkNEcXhya3VZSmcKLS0tIGlacGNMU0RxeGNPa2d2YXF4dXZN
            a1ZtZEpJcTFzZ1FudVhEQnhhWWlIY2cKR/NeCDPitovNprWlYE5A4wAo7bsjBpCL
            ZI00kfF1MZyeLRfkRocVa5RXyAhCHlsIMvAk8eDxMH2M7Z8/1sduWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-15T19:25:56Z"
    mac: ENC[AES256_GCM,data:X150UneALjgqGl+qj0XHy5PElLIKE8qM7h0olnNgrHR9AaMBC+EmU1G7xHMlIyWNBxW0tquIpI3XH5GSSYU9c6OW98RLMdjhyGscc5Q8XBIBYwdzwbRPG8nML+3/tT+ZNSiYpdrfpC7TPRZTLlxeCz6+0ZBM34XGWNJn7uiCeFA=,iv:jAfJ73/k7uy7QWaxhyFib4A1ExVtE6Gsjjd84X5gc4Y=,tag:lR+5ppelRbjlul4bqzfpaQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
