apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:hfQKWSyZIHkHyI85T8V7R1RQNCNzXObOKbq3DHLypGw=,iv:3ZivbCLaX3tv+SsbBpsEVI3AnmSBW88V8edwLB0R3bQ=,tag:sobZTlJXydxP1irE5wd0Kw==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqWUhiYjNqN2dBVnZZUkN6
            dWczbER0RHlaMkVJSUN3V0F3UUFSTERFYUVrCnl0QkRvY1N2dUhXdHpYazlMS1RK
            dkIvWGp0djFoT2xHRVJNR21XYkRlVGcKLS0tIExvdFJvSkpqUk1UVjY1RDJncUFH
            SXJZQTNRMTQ0YStzV3BlUXhRdnVaSjgKVPQwEn5ZaCZVswSj89xjnht96YU73wyY
            MpBvpZdMZgB74v/Iq7pZCu9l9Lhu0wESLnZCgNQcazMJ3HBSaVxKZg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-12T14:11:46Z"
    mac: ENC[AES256_GCM,data:1EUnUykoYspkcydHKO2R3YZ4VMR4VAuYUe4pwdSEAYADT1FmqkbJThMQzfIid14siLI6U78RhnAD1NhjfIBQq9m9iTqFEnxLHCQ4BoY1l72bw/dM1WqLGIE94BQpMVWvzvNJsuWDVEQ/HWzIOes5yrTJuftx6bNzvAZZg4xrVec=,iv:rpBv5/BVLa8lX8tJ/yFUKst02+8wGMnsXH4o44AL0tk=,tag:zX1lXFPIF3N6oN6dGKXt5Q==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
