apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:bY+BRtpdm/luWNlDkrNhhgMfVzXYlXWNZx6nKNnobCA=,iv:UEzVnBtMtu/16hOL+6miNzn3JtCUvAY2/tcvFHG66VQ=,tag:dJhAZBXWRKU3meM+vWd4Gw==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRL2xWVTFRVmIxcDc3WnB2
            Tkh5amtoMnRQRE9KVzFuelgwd1ljZTRuRkdNCmJ4bTBuQndxZXBPZ3hiQUV3RktW
            QkVxUzVNMis4ekc4SzdIV1g1cHk5WXMKLS0tIGhpRDlQU1pTbWVnTlZMVzAzUWF4
            MmoyK1dBUG56TW92ZHdrUDhiTVh0NzAKHhSVDMv1jfcHLSuraFuReoVXaOWVWU8i
            7seSkGOgpNtWDDINIQ8e2CSTG0SHIwtjEtmUYzMTYsOa3hTqkcXLDA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-11T14:57:15Z"
    mac: ENC[AES256_GCM,data:2b6nYDQ8z+UPLicOifculaUHwIy48LlTJA1uQvpg+FJhmTArr0/bESbbpAG8NHPmECk8ELd6z9KUiTDhbZF4Eq2ptjztZQD5eADNQYIsir4e0xx+s2QSMI9XrNPc9V9hOujTw1KudMvUG3+tOosRWOBwlMDenyBAo1GgOonlc8Q=,iv:HAFEtC9UUzyjFHFywDr1n/hbQYm3Km6hpK5ymF/Il+U=,tag:jMkcE/uyAP/7KvEVMqj3Lw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
