apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rustdesk
  namespace: rustdesk
spec:
  interval: 5m
  chart:
    spec:
      chart: rustdesk
      version: 2.0.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    global:
      stopAll: false
    credentials:
      minio:
        type: s3
        url: "https://${S3_URL_MINIO}"
        bucket: "${S3_BUCKET}-rustdesk"
        accessKey: "${S3_ACCESS_KEY}"
        secretKey: "${S3_SECRET_KEY}"
        encrKey: "${S3_ENCRYPTION_KEY}"
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                RELAY: "wireguard.${DOMAIN_1}:21117"
    persistence:
      data:
        volsync:
        - name: data
          type: restic
          credentials: minio
          dest:
            enabled: true
          src:
            enabled: true
            trigger:
              schedule: 20 1 * * *
    service:
      main:
        loadBalancerIP: ${RUSTDESK_IP}
        type: LoadBalancer
        externalTrafficPolicy: Local
        integrations:
          metallb:
            enabled: true
