apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: minecraft-vanilla
    namespace: minecraft
spec:
    interval: 5m
    chart:
        spec:
            # renovate: registryUrl=https://charts.truechartsoci.org
            chart: minecraft-java
            version: 22.12.0
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
            interval: 5m
    install:
        createNamespace: true
        crds: CreateReplace
        remediation:
            retries: 3
    upgrade:
        crds: CreateReplace
        remediation:
            retries: 3
    values:
      global:
        stopAll: false
      mcbackup:
        enabled: false
      persistence:
        data:
          enabled: true
          type: nfs
          path: ${MINECRAFT_VANILLA_NFS_PATH}
          server: ${CONFIG_TRUENAS_IP}
        backups:
          enabled: false
      resources:
        limits:
          cpu: 8000m
          memory: 10Gi
      service:
        dynmap:
          enabled: true
          ports:
            dynmap:
              enabled: true
              port: 8123
      ingress:
        main:
          enabled: true
          primary: true
          targetSelector:
            dynmap: dynmap
          integrations:
            traefik:
              enabled: true
              entrypoints:
              - websecure
              middlewares:
              - name: real-ip
                namespace: traefik
            certManager:
              enabled: true
              certificateIssuer: domain-0-le-prod
          hosts:
            - host: dynmap.${DOMAIN_0}
              paths:
                - path: /
                  pathType: Prefix
      workload:
        main:
          podSpec:
            containers:
              main:
                imageSelector: image
                env:
                  FORCE_REDOWNLOAD: false
                  GENERATOR_SETTINGS: ''
                  ICON: ''
                  JVM_OPTS: ''
                  JVM_XX_OPTS: -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200
                    -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch
                    -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M
                    -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4
                    -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90
                    -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem
                    -XX:MaxTenuringThreshold=1
                  MAX_TICK_TIME: 60000
                  DISABLE_HEALTHCHECK: true
                  MEMORY: 8G
                  OVERRIDE_SERVER_PROPERTIES: false
                  RCON_PASSWORD: ${MINECRAFT_PASSWORD}
                  TYPE: PAPER
                  VERSION: 1.21.1
                  USE_AIKAR_FLAGS: false
                  USE_FLARE_FLAGS: false
                  USE_SIMD_FLAGS: false
                  VIEW_DISTANCE: 16
              mcbackup:
                enabled: false
