apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tdarr
  namespace: media
spec:
  interval: 10m
  chart:
    spec:
      chart: tdarr
      version: 12.1.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  timeout: 20m
  values:
    portal:
      open:
        enabled: false
    global:
      stopAll: false
    credentials:
      minio:
        type: s3
        url: "https://${S3_URL_MINIO}"
        bucket: "${S3_BUCKET}-tdarr"
        accessKey: "${S3_ACCESS_KEY}"
        secretKey: "${S3_SECRET_KEY}"
        encrKey: "${S3_ENCRYPTION_KEY}"
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        integrations:
          nginx:
            enabled: true
            auth:
              type: "authelia"
              internalHost: "authelia.authelia.svc.cluster.local:9091"
              externalHost: "auth.${DOMAIN_1}"
          certManager:
            enabled: true
            certificateIssuer: domain-1-le-prod
        hosts:
          - host: tdarr.${DOMAIN_1}
    persistence:
      configs:
        volsync:
        - name: config
          type: restic
          credentials: minio
          dest:
            enabled: true
          src:
            enabled: true
            trigger:
              schedule: 50 0 * * *
      logs:
        volsync:
        - name: logs
          type: restic
          credentials: minio
          dest:
            enabled: true
          src:
            enabled: true
            trigger:
              schedule: 50 0 * * *
      server:
        volsync:
        - name: server
          type: restic
          credentials: minio
          dest:
            cacheCapacity: 20Gi
            enabled: true
          src:
            cacheCapacity: 20Gi
            enabled: true
            trigger:
              schedule: 50 0 * * *
      transcode-cache:
        type: "emptyDir"
      media:
        enabled: true
        existingClaim: media-nfs-pvc
    resources:
      limits:
        nvidia.com/gpu: 1
    workload:
      main:
        podSpec:
          runtimeClassName: "nvidia"
