apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: recyclarr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: recyclarr
      version: 13.0.4
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    resources:
      requests:
        cpu: 10m
    global:
      stopAll: false
    credentials:
      minio:
        type: s3
        url: "https://${S3_URL_MINIO}"
        bucket: "${S3_BUCKET}-recyclarr"
        accessKey: "${S3_ACCESS_KEY}"
        secretKey: "${S3_SECRET_KEY}"
        encrKey: "${S3_ENCRYPTION_KEY}"
    addons:
      codeserver:
        enabled: true
        ingress:
          enabled: true
          ingressClassName: internal
          hosts:
          - host: recyclarr.${DOMAIN_1}
          integrations:
            nginx:
              enabled: true
              auth:
                type: "authelia"
                internalHost: "authelia.authelia.svc.cluster.local:9091"
                externalHost: "auth.${DOMAIN_1}"
            certManager:
              certificateIssuer: domain-1-le-prod
              enabled: true
    workload:
      main:
        podSpec:
          initContainers:
            initconfig:
              enabled: false
    persistence:
      config:
        volsync:
        - name: config
          type: restic
          credentials: minio
          dest:
            enabled: true
          src:
            enabled: true
            trigger:
              schedule: 40 0 * * *
