---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wg-easy
  namespace: wg-easy
spec:
  interval: 15m
  chart:
    spec:
      chart: wg-easy
      version: 18.0.4
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 5m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      stopAll: false
    credentials:
      minio:
          type: s3
          url: "https://${S3_URL_MINIO}"
          bucket: "${S3_BUCKET}-wg-easy"
          accessKey: "${S3_ACCESS_KEY}"
          secretKey: "${S3_SECRET_KEY}"
          encrKey: "${S3_ENCRYPTION_KEY}"
    service:
      vpn:
        loadBalancerIP: ${WG_EASY_IP}
        type: LoadBalancer
        externalTrafficPolicy: Local
        integrations:
          metallb:
            enabled: true
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        integrations:
          nginx:
            enabled: true
            auth:
              type: "authelia"
              internalHost: "authelia.authelia.svc.cluster.local:9091"
              externalHost: "auth.${DOMAIN_1}"
          certManager:
            enabled: true
            certificateIssuer: domain-1-le-prod
        hosts:
          - host: vpn.${DOMAIN_1}
    persistence:
      config:
        volsync:
        - name: config
          type: restic
          credentials: minio
          dest:
            enabled: true
          src:
            enabled: true
            trigger:
              schedule: 40 1 * * *
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                HOST: "0.0.0.0"
                PORT: "{{ .Values.service.main.ports.main.port }}"
                INSECURE: false
