apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: unpackerr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: unpackerr
      version: 16.0.4
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    resources:
      requests:
        cpu: 10m
    global:
      stopAll: false
    credentials:
      minio:
        type: s3
        url: "https://${S3_URL_MINIO}"
        bucket: "${S3_BUCKET}-unpackerr"
        accessKey: "${S3_ACCESS_KEY}"
        secretKey: "${S3_SECRET_KEY}"
        encrKey: "${S3_ENCRYPTION_KEY}"
    persistence:
      config:
        volsync:
        - name: config
          type: restic
          credentials: minio
          dest:
            enabled: true
          src:
            enabled: true
      downloads:
        volsync:
        - name: downloads
          type: restic
          credentials: minio
          dest:
            enabled: true
          src:
            enabled: true
            trigger:
              schedule: 10 1 * * *
      media:
        enabled: true
        existingClaim: media-nfs-pvc
        mountPath: /Media
    workload:
      main:
        podSpec:
          containers:
            main:
              advanced: false
              envList:
              - name: UN_RADARR_0_URL
                value: http://radarr.media.svc.cluster.local:7878
              - name: UN_RADARR_0_API_KEY
                value: ${RADARR_KEY}
              - name: UN_LIDARR_0_URL
                value: http://lidarr.media.svc.cluster.local:8686
              - name: UN_LIDARR_0_API_KEY
                value: ${LIDARR_KEY}
              - name: UN_SONARR_0_URL
                value: http://sonarr.media.svc.cluster.local:8989
              - name: UN_SONARR_0_API_KEY
                value: ${SONARR_KEY}
              - name: UN_READARR_0_URL
                value: http://readarr.media.svc.cluster.local:8787
              - name: UN_READARR_0_API_KEY
                value: ${READARR_KEY}
              - name: UN_SONARR_1_URL
                value: http://sonarr-anime.media.svc.cluster.local:8989
              - name: UN_SONARR_1_API_KEY
                value: ${SONARR_ANIME_KEY}
