apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: bazarr-anime
    namespace: media
spec:
    interval: 5m
    chart:
        spec:
            # renovate: registryUrl=https://charts.truechartsoci.org
            chart: bazarr
            version: 21.6.4
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
            interval: 5m
    install:
        createNamespace: true
        crds: CreateReplace
        remediation:
            retries: 3
    upgrade:
        crds: CreateReplace
        remediation:
            retries: 3
    values:
      portal:
        open:
          enabled: false
      global:
        stopAll: false
      credentials:
        minio:
          type: s3
          url: "${S3_URL_MINIO}"
          bucket: "${S3_BUCKET}-bazarr-anime"
          accessKey: "${S3_ACCESS_KEY}"
          secretKey: "${S3_SECRET_KEY}"
          encrKey: "${S3_ENCRYPTION_KEY}"
      ingress:
        main:
          enabled: false
          integrations:
            traefik:
              enabled: false
              #auth
            certManager:
              enabled: true
              certificateIssuer: domain-1-le-prod
          hosts:
            - host: bazarr-anime.${DOMAIN_1}
              paths:
                - path: /
                  pathType: Prefix
      persistence:
        config:
          volsync:
          - name: config
            type: restic
            credentials: minio
            dest:
              enabled: true
            src:
              enabled: true
              trigger:
                schedule: 20 0 * * *
        media:
          enabled: true
          existingClaim: media-nfs-pvc
          mountPath: /Media
