apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:evp5avjGuqvx9wuw/3YTdyMseAjTRaWLtq0+iQu6FdFtSMU/XalrlNXFMiUA08beJWpVyfPM9vgTF0Qkp627UjzyCpx5serbPdABu1w+vxSmYbXldH2lAZAaUEkOtD+267gdIbs3avUkP/RI450+IZE+TF3mMx82Hw==,iv:WVLk193WTbOHWq020bxr7gRRWoWzWXb9kJmOvuM6lyg=,tag:d/874qww20lnAqe5gw7cyA==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSYzhMbGZyZ0ZVOGp5TW1s
            VTlpSmdVZC81ZVFaZ09DM2dsUUpTSmZoMW1RCkMvYzNpblExRlBER0xEbmZCcXZ4
            TUFldmpDTkNxRVZhK013WE5sWlpIZ00KLS0tIHFRTmNOZ3l0L0RtZ1ZQVmJESXJJ
            cyt4dkZFTktHQXZOOG9qS1BFZ3dJZ0EKFUZyCD4YIkKEISGCksgurkHf8FIxPgoe
            HC/hbhcrVwT/3CU+t5rM2CsAjkCjv1dlTBxVW+Ma/7S/6hPMh97PUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-11T10:56:55Z"
    mac: ENC[AES256_GCM,data:EwPL9V3p812njnKCkILgN4EeNrgNidvfBrfaKMyyhUilUU0Kkxlry7RfWK/lCP2959A7J5/TNsFv1+6Ryelu+8bqzA11wpQ5oNJelr8B8fOSFJItX0WkySyTSS2etXkRBt6YhOUFJQWRJEwG1xs4HUSn/lS+myD+Le0ymO5cfiY=,iv:T99akGGIsX4H9Emnndm4NCbIWHmxs76oGWFX48cG0Y8=,tag:NQLmCltpahdVS6+hwr7F0Q==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
