apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:5FH/1KpCr8mjhewOGvLUdyPAoAum6cc2FEhelG/FERyruiMiatHFeOd7esXjYCkS6xeYh3AuYHfqEV8Lg/WaVLwee8+fJoqqs20zbn//kGJeN55ldH+oW25O3mRsxX1zTVr7hQaU10NpRPiuZSGj/W44L4Mzv9vmCg==,iv:Yv2KX5tBBq7OaP2HushRZzl6KdxYpSDKmGk3iZNOj08=,tag:8IUJItZCdJAIgDNSI+/OmQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwWElQQ213VUxycHNmM2RZ
            THd3WFlxYTBidkpCTktDaVVUa20yMFp3Q1NNCktUazBXb2RwTGs4WHdMTXJ3dDVE
            SlJhS1BudGFWS1MzVVJVN0lQbXZLVEkKLS0tIFJocGZPbXVzcUdHclZvMnlRak9v
            cUFkT28wWDFWMXBXVldZRm5GRnNQSWcKfzAdX5LEMcUdIZ+oCisYWG9XOP5oHKU5
            1xLJm1+w7E0AURPEEs+hEFDpH6nRssg9vJ8w06ZKhoGA5YjsKI37eQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-10T13:37:00Z"
    mac: ENC[AES256_GCM,data:RxjRj2ytAHQQvdxTtPKVox8Sy8QDaDtIpxkbGXuVM7ptzGtOGqd9ip1XDAnU2bJrtptqhq4/As2dVSso4w1xDduntHzxHZfzWj3ILO/99z4zhX/1yq3N6SO3EPcnu0PJCd2qgBSELKwc1NqYgCugmDJENTr5T2YK3WueUUmut34=,iv:2SqGXqIxsNsX4Z8dxgDEM3bp0cPW80R83/i4wwO/sMI=,tag:7T9CaN8GM7ZMoLFf4ePYog==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
