apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:G2hW2xpRSlBojO95PGtCh/+c7677Z/2WQrWjCVSowSTa7XxpXP+RqYjzSgVuMxrzN16OigRPCJZYLlnH/r6gnkrl/Zr4yH7EojF+aX3STznNAJapfWLJxR0fMbdYZqBdI3kX8M3SENCgOz/PjaCqDzjHaiV3dmZtIw==,iv:HLLuTE1kqpNJeAVsKxmD7BNkF3hdA1ICXaGxOLCiZMM=,tag:P6XZYLaY+w55J2Bk3QJ1XA==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCamR0U3llMmpHaGxqMHZW
            dWpNem5WTXZXZm1QUUJZb05iYk9ZaUQxQ1NvCml6WGdiMDY3cXJob2JsVmQ4b2Y1
            U3VEdFk5azNhUHorK1UrTGhmbHk3WXcKLS0tIDBNZlRwTVh4TDhvUjBJZndIRFFn
            NFhvbGd2QlVXREhHNDBONUsydUdlTG8KsVrSAONfLPUgIFmAQHfUpaAPQ44QJuZw
            a4LaV6BKeoiua39lKa+TlweSqSyV6xvt3dUeMRwcwYBweDUZaXomAg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-11T14:52:32Z"
    mac: ENC[AES256_GCM,data:AZPPz3Edp71PMK8XTFoKzc7dQ2gLxCujLp5WF8UqcNQwjG0XQq/hcIVjHmE27dcHFj1ReXOpysP/VOzVD8VYMRqymoDkqniOY0CjAhFs8YD02bNhtj4nHnjnFpgmnLm+xzSdQ8FAOxp54ME3+S8927icxWdaYn12zmPxH+jzNbE=,iv:BbNe5mGsj2iip2JEVjgvIQiHTTgD7Z6lcAFCkIWUNFE=,tag:4s9rx4fYsjC6rFObQVOejA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
