apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:9INRxaDTg+vdio2a6mwsbuksAKTrwQ+hjhIpW6DSxRVx++eRqf8kso7gxG408/dZUzHm6+YC+ROl+IQ6nB9KUFzgtdo/Wi8dszQoQTHeYSS4Sf7EXwVDGeN9qaOlAQliMpb+W9DV2fwNFVFqAYAl0hOV4axYcSJ8Dw==,iv:UNt5yFFR/RiLjXhdTyLJ4cEpNbmltbhiwxUVoeGsaNk=,tag:J37IU9Qu48rqrKMLu58wIw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOM2t6YmYzNGthTEpBM0Qy
            d1NLK0huTWJ6eXZ2c2dlbmp4a3R3dkVJUUVNCk5LaUxiMTh0alMxcTM0TzQ2Y2Er
            SVlZTlRIcGVLMW1EdUtqVjV4SjJWTDQKLS0tIHZHS21IanZEMStPb3MzMkkvUjVH
            dlBlSzRvS0tIQXlnbkhJMFFVSkRsT28KX+QnJ+Swd3V/Vqu6h3BralEPQK5x+a76
            Y1R3pfKgdP9awseUQ9fOjD9rWobLjyXfHs2EIu5HyezwMZ6OBjR1Mw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-10T14:14:40Z"
    mac: ENC[AES256_GCM,data:xUNxhV3DDzmpzPlIbsqO1aoDYU9RYV8JXJHSyb0WG93XfxucMcwJ9LYcVjXULgPim3jVJ6OxiUnuSOeHaImC3eQ7L4MhGmNG3Es+7MfXQ7ztweVxqlibtLRw9vfDfXUuI5+RBqCRIEByih9N+/2JoPvYni7b5pHnOhkOTuGxdG0=,iv:HM8PRnCTwRr1X4XLRSx1CoHWg5h7cZFCg3N9BVe5Oxg=,tag:a2VjvzbPGOLK321FaPr6vg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
