apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:AVElTUQG2apG8wbSdZ1/sV43M446slTSIIL/ThxyQvN5qpZIeoVPOqtERECYAYUDk4cK85V67G8x+cIXGjLvMK+ZlSJaFf9l3yw6h6n+qxuz9T2+z4gOkYdOyx3tsVaU1Jkfvdl0uyjShhqI+BzaXdfGqnxPDbt2PQ==,iv:Nl+vmhOslRj1r85bdbaFE6j906odZ1UePTJoR8G6rek=,tag:xp1RVuuKP7CuDKpeOTGuwA==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSRjN4cnVEd1YzdG9ocDZB
            WUREa0JwaFE4WGhRRE5IV1Q1Y3ltWXlwSkIwClRpamM4bDdDN3dXNERnZmVaZzJy
            c1BMK24yWnpURXZqcmQyZTFDU2s5L28KLS0tIEJFZGl2WlI5KzJFOWJrYkhkZEMy
            SmhSenpVdlZIZFFwRTVMSmNWM0ZZaUEK9GeQfHP2Z0JH5vPMuTcRtuqa0FZHJdoS
            mk7IMaTb93xkFd/Xtije2CXkoPPq/dd3SFgZP9HzL5y4dvge0Sp5Mw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-11T14:48:55Z"
    mac: ENC[AES256_GCM,data:Js9ruNyWTQlIE0aTp3+Jedm2fllFDtcrvuYrpBE1T4KBqq9EyWM8S0tu8WxrqevxLKK1GKePYcY4evKulLQXgFEbKYsql7edJUbTaWhq9wlUje+MNIgFfQwBJje2q20nprDWRcQ+ZDetzh+akBU0tNJTuM1UwRlU50hbPhGrl8o=,iv:i8dC4N89g0viH8Qr0FTq3ZNL+071dI6sRYKVPXCzeDk=,tag:vEBGduYvF4p1wXRNfFRrhg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
