apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:ufVotytDktfjkr/dBwlnK+c9CBpEu1Aj+j5LcaYcHbRENTsyKg1ymWOCNaVSylXZHVlF6/b3BdGNBIJMcBEtJuOfuJV5gN+e+22xzoc6+zf94Xk0aOCimw7+TVj+xOoYBeWL2euTXTkvdisPz4R+ee1xu+6qU40pzg==,iv:aE7d18/Lb9m9L77cPX1Y+i416azmRdK8udr9lVzSms4=,tag:+z423ynMi1B2m2hHgo8kdA==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJSy9RbE44czgvR2w4RkVo
            QUE1bDM2S0VoZlhvY3NEVWpwTUhUVmg0S2o4CmQwOEwzMC80WTJQVDlXdU1xRGtJ
            eUNsNENLaEJuODFmZUNFRUM0YjJjbmcKLS0tIG5TVkl3cS83THJJUnltY2J2Yk1E
            VTRCdDZBU3JHOHhERk85eHBoeUtKOVUKwtpRIBrjISo29xQx4RoPL20O/YD1UlZn
            GgQICdnI11Um0XDkvRY5kzii2X6ZYRiN+CDlwZFA1KH/VCWN6zEz2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-11T14:57:15Z"
    mac: ENC[AES256_GCM,data:Gm07wRa6odT0Y/r9ycIG372jM68ypLzhlrLbaCQOOLE3XYpxu2vPIlaeDC8ciWwMMQGC2AtDiIRyEXoqjKm3oISSN5/JgimsV+BBKx3woSOjmn9+TtGogzZ3yJIcub9Zf+mZ8G+EPXdAP/UicJtQnJXARyRxVU5gJSklbYbOdao=,iv:fiWIYBgecpl/N2dRNsnza2Uc5aJcwhbWuP1BxDYmBLA=,tag:F+7mpEdd/sALoVZrTA5FHQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
