apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:Ted5+rHH25jM6RraYI8rBwMOvOzLxKozjc556joppFA+XHX4g7DsxFvrXInpZNsUxnGfEZuO21UPMmBxrKc9zyuu8Y5JIMTNBGElm3f/F8WgCr5CGWXes3otB8pCfb5KGqVaukTrgxz2U/2VKl0sI8NGxGVAmHzDSQ==,iv:r2Mb7fMWC0SInCIJjtuOnFSrGSYyBIyWgqT6ngR4fIc=,tag:NVRkR1t8UTe5oUqRL7iJcw==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5WFg3Y05mc3VIcnAyd0hy
            cjkyT3F6ZCtlWDgvSnBBMWJKdkV1SHJqTGpnCnBadCtzS1NSd08vRWhpanE2a1M5
            TzJJVWxsNnNQTjF2N1htT3JYYUFRenMKLS0tICtoQ1BNL0tVK3FaTmpjV09LcWQ4
            OERnNGlqbXZDb0R2ZnRlRWFLZ3pyMVUK56Hx6xZocBtOvO8Wywyxsi2Pt7bjdVoR
            lE3Xlm6p20kKm0ccjA6f5tTOVxVGLI+f3o6iaPJKFtdt6ZmabTCSrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-11T14:55:09Z"
    mac: ENC[AES256_GCM,data:1+aNdS74NF5qkCo+QwI3vVBMYkYNLvFl9NoafrVpB6Xi3W1NMzRB179Cf6X6V58HHujqb5ZRc7/XhKHZqU5UcHC3IjNiHY+nCoZdN5BC1iVioonhTsuLzbqo7umrlySMpbGRMSqUPNMwzPotUMqoRF0tdejFx6b0Ndmeb5/nOMw=,iv:eyIz8njpjrTWifxdWa5aGPINJfvYj4Hiz8jxleBWZLI=,tag:lK5RwLnXZ0x5K63fFWdFWQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
