apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:xaR9C1Patev7WR/hhKhNsvW3WIUQjvYTfneK02gi2LHhvm9vLNbmM+Eo/ZB9kh6yrhRIPeWZe8KP9vcNizSqOmweAmFcKOqaQ5m8Ia8ezthZukcB9dbpEIwjFpEDpiVntyiKzfMRRCnZtLgotVzhKFglWQwCgWXw6Q==,iv:PbTHU6QAm+1wBTgdEYqOgskfrMVDO7AOeLUNtlDE4Fo=,tag:WkZMdVow74KU/hPkjRvgqw==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBscHkyRmVKc3NYaU1uZzlh
            bldKWHd6WEl0azNpMTV4UGFTOHFyZFAvakVRCjFjMlEzLzJLZkIvN3V0VnJJaFM3
            ZXhCRk13ZkZQMDd5ZjBMVG9vMmM2NmcKLS0tIFB0dXVzOWhMczl1U0ErVUU2NVlI
            MlB6RHUvZ3ZoQ3BsSVRTRXZ4Sm0renMK0avF4xvtwM1jYklSipL0l3eYHcZ089eE
            UWvVRxlH6Fjs89y1DFuH48a/Z8AbkI3UdtNs6oHWCIymAQKO27yktA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-11T15:02:47Z"
    mac: ENC[AES256_GCM,data:m1RV/Y22d2pjxCe0rl73YwHawMbUoxFOkyuTKVOmwlHr5P+CF/HLvTZG80bEoq4/4xMubyEf0K/5xD9f4AYrwLVHXw2SAXYJlt1cMdFwOtICCKDP37NJvqrxM43Xp4Z+ZSLiHoPm9TDsZfMb0SMY3OAcsetEL5NHCvShlvSFcjo=,iv:xKvyLY7+SuPbeyWKb8P/BCdEV3r6qYDbB9y/NVfR2vc=,tag:vErA8cM7s/CxpMv6E8s4Gg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
