apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:Xt8SUMyiDl7RyIfGBBPO7K+AKcJd9X0z3CS/ukFpV7Sx2Kye5wBFUrvdS12yAkEDqB9t6tww+Ch4Puy6mNTTcMX9/UB31XxSU3crQc8BS8o+xIQkwDD72jYXC9wU8m4Olp3KMwxzNwZSXad5hndJfTQzgMVlJ8n/zA==,iv:WLReDKbGojSOG4g/sPU/sXdJT/It8svJS5IGQ9htSsI=,tag:eNjjB0ksrPS0ZQbwfLbjBQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwWXBBZ2xGZjRjcHh2Njdt
            SXpsR3RMOGx6WDBlL1NiN3NoUFFkUHlzVWtZCkVHY3VzcEdUYWs5WTBvQm1Xc2dS
            bUFOVWVGUi9MT2o4TTZNTmZRNjdYM2sKLS0tIEt3L0poYjZqVTdZQmlpcFJxRGdz
            OGNPVFU4WFAxcXRmV2xpZC9LcE9RUlEK3bNRgX52qM0kzqGttGrny0kGafY/EVZx
            C5kMbiVBISzbbMbG0Y06ApWIBp4PPvokzcjr6aDcqvGgyG2FZ8mzcA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-19T08:07:56Z"
    mac: ENC[AES256_GCM,data:0V4y1WXwmVNPWnMdRNR5AWG0UcOiMborfaK2AFe4ZcXOtk10YtVm0ZatUx5uEmg8UuoIMt7Zhf4An7oKz/wfXX6YDjIso3kCvDecD0ZKMrn+HseS/07yC1nvXkd+TmLHekCZAeNJy3Vb0oeZkAm6hd4sZbpBnBEaWBpW2nY/bTw=,iv:6Z4jKg7aSAi3DBMRkR4F6zfGadVckwNY/JWSU0jWLjg=,tag:OYlLFilKdx6TAVQ/2AtQTA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
