apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:rj3DHQ8fbebo3fJ65kG1ShA5lAhdr5wufv3hsKhGror5PfBeDcTPqNcFJ3Niq0d/B5AqgsKBIUCGbwUCC3caBIJKm+RZ9H2W4bIPY/qrdkCxERcjLvtcQzo+/GbUmTqLY8ypOeSXK+mhtHNuUYoNawRuysrcKbk3VQ==,iv:OtTNG602BtZZs/9WM1YYiuRqtaPFdepQjnSJkLhZ5d8=,tag:h2lxo6HyIHL/npzQSmOoWA==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXdXo4WUtIVzNMWGpCYWlN
            NFhJdno1YmpRakxNY0Vla1JVVjRkcEdlMGlNCmxmNG9xelJIbERBVzd0RjJSMmhX
            ZW52Zkw1Nkw5bCtrenVyVVlDckR5RmsKLS0tIDB6T0dYcEhsQzhqSlE1TWIrWlcw
            Y1N6SzI0TGhENk1qRUpONEdZbnVHQ1UKBrd8z1d+DraieHCGgTSmpr7LuyYOmJ4R
            FCAoqnmJcwNyzFlT3JWaS86Vv+Swm8Q8K/P4M8L/wSYRMPb+0Hr8HA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-11T15:00:44Z"
    mac: ENC[AES256_GCM,data:pyBNorVhlakBqDIQRKO22leK65UbOD8KAsIQ44R1RkiSnrp0tlGbXcT/CUMAzkRctMQr4DwMf7OrFOP4+hsIS6mI7xDu2unshvjf5kyWgFSV7a9W4gOue066S3j62GqGFGjsu1B19ddYpZUoj06bDn4pViUpPz+yXkDRlhofqV0=,iv:HtNsHMOrCUbXAVlorPNaNxkLxH2IFhTXxsa3M8szSk0=,tag:DzYssmvLXcF3wm03zfeHCw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
