apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:uRwQ3YZzRYDb9wfKvEp4/qsfpna8UB2Xux9PtB4IENpoYWd4IuJFeWKO8Ti6hQwG+iWqbdkwJydCrV8nR+w4J4qYdtf+d0ZN4xPpVp9dVsnnHgajkb26Lb8Prox29y+oVkIgEE+900no/Tw9pGcbJK6n9/lZbrxNBA==,iv:zrxWMr86cmJ6neA02I/maj+MKTl/kMu+S67Tbg+oI8s=,tag:wvJyWwpAnzj/31TMihY7uA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsaFFINVcvaHRBSnBUZWJa
            cTBzWm5XbFhpbE5WNUpGcnRtNUZ5NHFja2w0CnZqSHREaEFZdHpaTU8wZnVEVTVz
            bm1mSXZHNk4yKy9Fa0NncnJxaXgrcVEKLS0tIFh1U2hBa3pGVVN5bFk1WnF6SmlJ
            MXBQOXpOWXVJak02SXYveGVIZmwxWEUKuhgKdIhvFT2ao62XjhMe1fuaPD4J7l3A
            z1Sfi51a1J9u5aT6tmgAIsMy8BECMDGNegvlDQ3VABUrUMsSHZaqJA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-30T12:40:45Z"
    mac: ENC[AES256_GCM,data:RdB1BSUfxYFZxvwWCtD8CNc1UWCL2dW4OQhaXFygUmyRSjBBTV5XvQNADmzcogSKsNPDBNYxqYVxlwGRCuo0ZWYH8D9bcNQNahM4itlRfh37ZnxOaqkUtAPGDjd2iseKI7ZEXs7cCn7fhEdnzR50WkZgws03PVPhKNL3tNb+jrY=,iv:ts+/Mrj5IdENNe2F2IUWXgX4pLkBhFOG+FGSvMFHQxE=,tag:oyllT39VDKGoFnpZXptSZg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
