apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:tUbeyohCGRgCT6T0xx2Gmp+pAyeeatck5VWG6N9bssTlxfsoQZAH4Id5yXtxqEtpWEvCmNZcIfIjTuM/F3Y2hoNqtIlifo3Hs0GViBLZRGp1l0wIHk1aAwqZrz4ynMhbWWY2DYaA2OvC4yO+S/VtXM8ZP5jqNsHyUg==,iv:HQ0wIJ+6nP66fLK2IZDDjqnJA7MgrmWooHa+LznQOAM=,tag:7Grb+8wAdiO3oNlxqFY3rQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJSU1xUkJhY3JEWTFnNys1
            Rm03MEhyd3N0ZG5PN1lGRTlRQVYrQlRGMXhFCmFQUHorT1RXSUdMNjhBb0hTV29T
            emZUVWFDZVM0b0cxWUZYOU1ZRHAyTTQKLS0tIFcvM1lDQitPaVVNTURDTVIreXRO
            WFhnN1IvSTAxWnc0TXNaamNPeFV1NjAKCR1a1GZwgQ13bMrtA0sdqtL6B8gHizy3
            X36gW6NvBfOr/A7fIWoNh0AD8YlOvUItjK4Mq2GGvBIxTXfqClWgGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-11T15:27:24Z"
    mac: ENC[AES256_GCM,data:tSRsK8vKNex4vOIjzknox4ZJ7EbL7tMLrQs/lIQ1pJ/hDBCObFwK1JXFCw5iZg/+pGWdeWVEGTL4LFbgjqnN8L/8MGkmCgrR08MFX3zsTW7ABUYNQf4vNHZwuQ73sxdaDK/t/QzleJssT+yNy3ypnBoUTJlUNvfXUkAkUOsceL4=,iv:G8wDQlfPUH1VQUr/Jy7k822L3HNKvS3jXwIOsS9TNik=,tag:owlmEUxqjksCEtBEMWollQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
