apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:woCaeyfuwOzR1MX7XWcFboTf0A/KKTJXOHrgXJDDR6gO2G/cfuMoFh33/2jyq090x2kOwq0fXRrDyEmslOYYqUXyE/F89BOk/+CDCddx/yy+6ezNelHSQauwYGxB4xMBbsgIdIx0M5rALdR1+QuCneHF+IqmvjphWg==,iv:EgyyZgPSytgZqlrOF6dqstISjrIgGvu5pScX7/cdaAc=,tag:bVvzrj9HVkFxON85M0u88w==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwVU5DMkxHcGhaaHJXM2Q4
            REtGSE4rcHlBeVF0dmRvdTFFZW85eVg1TW5jCmVKYmY5TzU2cDYxaUdiV2pEb295
            Mzc4YVMrODRGVDJ5Z2tUR0NXNXBoSEUKLS0tIHRpdmlsYmgyQVdFaXJ2dGxWMTk5
            dVdnKzhFMXpkV2ZtS05SYzE3YWIxMFkKVjTaQDTMRAH4J6XMMx6uADPTbiMIXI76
            jOSDpdxUigUtt83jPIzclzyY0fdgNMZrN2T+mGnSllN8DOhfqdZndA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-11T15:23:57Z"
    mac: ENC[AES256_GCM,data:Mf8Ifzsyd8OgUoMsr531+KNqCTStR12VlyndNxuhLql6Ojbp6hmMiaV8tFxYsHDBDVTqpsoj0A3X/JwLFsH+IrXKNZFSoPkHpUKqMt1XTWxapwqDYwIulOQn3P2MUwG5rjGu3WQGD5/HD/k7MvisvM5tFJN02NphMQ6a8bPRVVY=,iv:pIgkhzQRsE2P4ejzUqseOrFfw537QSovMe++muAnnhM=,tag:L0OsqO2MD0OGOSZEFIHn6g==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
