apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:Dg8zNOAenTEDE7WzaWxxqz0yCUtOtHy2QfsMW0QvjtzyFzzMGq3p7PtLa7tP/UY8cnLjYOBlZONg30cJQD6ak+LVW2r04uccQzaxtZyDFBV+VHVhRoMEL6QJ/zsbppvSj+n6KvtqqI9YXY24tchoBteaIdCBt2cMDg==,iv:dynHSMi+ttYwrhOqaBOeeq/NJLSUN5kCOduRwfHHRz0=,tag:AS768DSWwk4PNC+s/8OzhQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVOXQ2K2srM01jVFZBNno2
            OWhxbWU1N3MvZHhPREo4cWNZYUNBbDMyZmhBClN2R2hpL2JJOGdiT0pYcnlkZVh5
            NnNmUG9DcjFmQ0IwY1dJelBod1pvUEkKLS0tIDFRLzlQYUcxVFNSUUFsQUxtaG1n
            M0k0TzBzdEs3NDFJL0tGQ0xTZk52OFEKa4ELiDQxNiEXTCYtI6eqo497NPlNZ4IY
            HfUW3mQkCadHVO9s8slImT/dTdHWM+hUUtueIuwIJviLEPYQnzVuIA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-19T10:06:26Z"
    mac: ENC[AES256_GCM,data:guDUzU2sTiNI5/6GWs+olhkJa8LZT2MTlVsB4JC8bCmX+d/w7+QqalDHiCXhk5BEamW8zYKN1YM5hhKyQoZqQVuNZNKcJjwK69jPyOrn31hWNTSvPF6HTmwGIQG0IqQx5KvYCZ1jcp+RDxdzJecHfnMBz5XSAUDPQL/T5f+ey+I=,iv:0ch/RiQkxwz1CLHxSKHrAm28XfmDYRY+NQKkNhSTa7s=,tag:eFF/axTGebTfgM8IBIMZuQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
