apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:Bbn90ns1BKKobfc3M+0t4Mz4KVDJFyyUAYpIK+M3roFSgtIjXtdrAerUGzghMBuGY15T8nUKurS9JVkZw2FHdmoGaNfQ3NCbSqIlPwMGWkiQ+S2qdH8ie0aA1aLxgeyueWDfK8KBw5K9YEgZ0aFVzjNlXPB2sOpQUA==,iv:CJx3Ke0E1uOlgNfDifeVm2Pv3YbertcjpjnJg/AcwPU=,tag:bqeYb49yL5U5sc5t3e1pug==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzZ1hINVdwc2NiL1F0Z1dU
            VUkvL3lUWTVPTVk2a3RCbnlTWWtVYjQ5aFVJCjV5YjBxSWFRcEV2YW9WYlM3Q2di
            WDYvZFUrU2w3cFdOL3VGdFdkOS9kL1EKLS0tIGxPSFhFUGRHKzFDeDNiZTREYzgr
            anRJNG5YYndDeUVEbFFJNW8wUEd0YVkKfVvki00uKaNdjHCKxi0vnzwITC/IiIrw
            80sMHy8sb9GnlLqVZE/fOzSh4E544PIjbj+ElJDf4KyQX3YZqADCBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-31T10:31:13Z"
    mac: ENC[AES256_GCM,data:Xy6rx+OFq17PdoqmJeFubhb+7L4LSwFu94jtWzagBCTgiB9z3uw3G3su4LgE/isE5BS6G9bE9kAK+mIIDEQnPLGTx3HaMEsVgi0UqVA3g5kOpUuEedAI7dFaJbHQsgqlm6mSYLbYQZEPzK/tfqUF8eWeaM8nPXSACIVZfn81R2c=,iv:i1eWkr3/P7gX6FBBxPW2hb5upaXC2iu5ePUlVJdL1YA=,tag:tcjlM3xCvb04YIuTC1crtQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
