apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:QiyBhkpTFz5GtBRrvoUsrjMRrbQlh1uN6z2szIuuaKvOp2koib0JusOcxw5ev6JcZt+Jkl1047i9vSZvjEy/4BAzqb3opQK7UJ5QdayGUEEstHctEbLPHhxbhzGCQo/JzPVIMUh/su4U5Z73inBStXeeqfx5At9y/w==,iv:/DVryrAUfwQgH4OZO65vgI0WTj7Cwo0XNyx6InBHaOU=,tag:LjCUgUtcb7yNzRoUnPop7Q==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5dWF5bmQ1VnJmVzUrTlhR
            Tm1LeldOdU85MHVaQkFXVVdaUXRhalFTY2lNClBEK2RWL1NEdUZuK3pVS1U2Ynp0
            SFgxcmNlUnRvMGVKQWpDN1Z4Ty9EOHMKLS0tIGdqaVBXeFY4amRVMzRFYXc3Rlpn
            TFdlbnFpWDRjRFVaSDIyd1ZmTXdlZEkKJIJSYHGPkALavlZh4SIYgV4wkWAcBJHW
            luBA8RXVnGpqnzLBFUl+BRiCaJbMQ+9skOAve4v9n2471UgFyGXt9w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-28T10:18:49Z"
    mac: ENC[AES256_GCM,data:UZ8Ge8AruXqVSPc6YJ9Xc850Vjgt8aF9c0YuMKUKv/Ag4hxjwBNJC9uJztMhCRcMXCJtmDROiLunXEYcf+B5h/nfMdf0AOfiE2EAAnPzQxhTyft6n+WoOmmqfDQdiloSXP6vHQp41lohveDWjeWAWZFpx23hGEDbznJbvJOQgyU=,iv:7+9sqbqR3cvOc8NNHOgFIHNV1uDPxFuGkJrF1mv1jg8=,tag:Bm8RMS2V6nH9K6G3Tst97A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
