apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:SBBuF/hsuPEV416LmfzKvrQKIm43hzez6r0Jcopj99KcDa+iCBS/cet471D4WcgJaYRsPJKhFJ7yGbYR3brQyPVUk098qQ88vuJIZOB8KHUIC0zgiZPnRmpM+jAOZ98+6Z2JSNEXxlL4lmrGg+fpasXuPs5eCkCBKg==,iv:+HKJUnTTbHAIeAXn3RM0BmHq0ESyJ6vCn8OKWjRmrQs=,tag:tpalW5PJVtysrEXksaMn+Q==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqVkRGKzRMV3FzT0RiaWlm
            V0RyLzJxaWNEMVpEUnh5ZDBXcGdzdmpSRVdBClVWOEs1UG1oaXdNblNSY3NCZTNW
            Wmtwb0hDa1JuQnBXcm5YOXUxTGk1dkUKLS0tICswTlEwdG1WOUp5YTRSR29UZ1ov
            UG1qK0VNM0l1K3NvQ3dvZTRtbXFtMlEKgKhWxxLXM6OnrmyLu16mQI1NEuqPA17G
            QOIU1NzunfjgRBNuORZSW4sRi0z/QdRlsnePon8feIY49CYvyd+D+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-31T10:35:12Z"
    mac: ENC[AES256_GCM,data:40Ry7PZ3rNylY4LMTmF3xQfixZsadB+dpVCHr/F9Q4cCEWR0hEQ6uXLd6Qdg0181v3SMPI/sHwjL4Lhx+NPIQbr4/8O2J6ucFl61d7JIQpw5V18GAncrjxkC0EVzDV1JtywGGvG+bH7Ml3TKi5xesgiWwwgnUU2zsOsB8Hm3DOE=,iv:zlrPbbhFMtsPAMi5Fyr35WP8ECdcmVyablWcDpmcuq8=,tag:4i5juHVtg943hIBcJNtb9Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
