apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:QoJlt8M2yGAH4ric1efktogFeDKC/K93iFU80pXNO59vBzMo11fUsP2EKe4GxuoprU7THgHJxMqX+ZEHf78iTSv7fyxe8T9AT6445Csv1OKGDT6Tgb+I6896aM/sQfXuRhjX5EaWUfESwijwMGGYWbTU4/ea0IMp6g==,iv:z5hFugWR+VFygmscY5yP/OfdDEUNwRX9364D8Uu7TZA=,tag:gX7m/zesWMuN4+8xIXvnCw==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxQTZMck5rQzFhTDdKTFBL
            TXJrMXZKN2FIZXZOcDhYcDlyWUs3cmRTOVRjCk40R0N6cnJLbmUyaVUrTDIrNUdL
            T2NYWmw4YXRrTFAwNzhpSzA0Wm9VYjgKLS0tIEx6VXlSanYxVmdIRUNocGZmeFdJ
            OWVVWVpHSVc4ZnM0WmdkeEl6UTB4clUKpvto3sq7ompmNlM3sAQSl6FiyExhugSZ
            f0nH/wiMW4+P5m88SDVHhY7lYjSV/7uB5e5qVEjUkHBAP3SXFltGFw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-17T21:41:56Z"
    mac: ENC[AES256_GCM,data:yqEz7fPfxZRlNqS4Pl7D6HKrEz5RbWb+1i/RBDhkMXP5+n7E9FPP+1+7N8JZMGvcC/OpcnbHOTkJWkYgxYVL1BbcQ0MrXdEI8DevDpdeqBTtlYf7mhA5UcOgEgFa8Vzng4+aF+o7BjerwocKFVtbssS+J2eafgoeLi/hYriOKMs=,iv:0RY5NT1qmBXz0DE09TBlVKUsytgreA1Lib7XmCEOaaw=,tag:iPwa6bug2Q/jTgFPruuBtw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
