apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:Y1J7EP0i236QC/hXOGDS0N+cdVQXiMMbY0iYAAMV2T8tGlUTMyipqkoR361XPNgo2aHdAXuCn+aJZykmuAlkEL3GtA3us2hHiHAgCMzao1ZtrjxhgnsB2iEWoegZsMLGy8p1qFu/G4GM6NUiGaWbwpH7EWrYjncxFA==,iv:axCpZr5h4UtliUauiquMxUvkWvroH8s6g1qyrhVI/uc=,tag:KiuFanZ7aql2wigiA5dc3Q==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1ZTJFUjMzYll6OWt6a2Vu
            b204Mkt1K3pRbFgzbXpyYVRkVWd1VDBuS2tvCldlNEZCZjl0czkyakgzdEY3TG0v
            SzE5bGFCUnJnM0ZQSFZLcGt0REFhamsKLS0tIEZ4WGZtcGp3YUZzTURnM1pMZElG
            ZjQwbHpZMTI0WFFhUWptSXlOQTJ0ckUKxqEpeFJMDdGjFyJm1LUA2reKlRh/YTqD
            L00HSeDOakqiO6/H/5bJgaW4MPwXI7B94tQmwM8KvwO+yugwZQKLbw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-04T15:57:26Z"
    mac: ENC[AES256_GCM,data:HbTEMhZ8Lah5sodrUwKryStvIRdE6DuEl1kc+aSCPGS25yJYDN4kiON25DiFJ9si/dlHsNhgxqFGkDWOMTmUhTOttzMzS9AW4mnMF+qfN2jK8dQweZYVZJybXo8MPhWRJr1JXUwQKoWOCir3/r5ulJ/hUek/MSCOxLDsmIqHHMM=,iv:yjIa2mBuV1HUobynJj4sY2bhVJ87xQ5CV1693Ecd1d0=,tag:9JAqnp38b1rCYud9zdI1AA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
