apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:QVpYS3PjOucgz8zRxXoZ/DCWiNzy3iZS1D1xmVmILmuYzmhcj9zeOYBcct8wQMMNS6z07IxKX8BHuN1GdZ59CUqxr8EDT7d6XoLk/f1JOGbLCOEbYjUU4m3brbRyxGE32fjOOnB//rdqQEXsZTG9aqJ7we2WLu1ySg==,iv:KMRjfnyKxJSkyIUL+j6RG9nD/IHYl+PZl0/KKhCprN0=,tag:I+gdQMuJbqc14y3b6wICiw==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyblJCT09xOFRycFRiRTZB
            czFzS2J2RjB0dlNIck1KM0lKdGJPZUlKdEF3CmkrZlhXbXY0bEh4aVAxcVQvb0dN
            enNlYlhTc1JMZ3lmUFowTS9LWnVoNnMKLS0tIFE3dTA3Vld0T3Mrem5OTWZaZmF6
            WWpkMjJyZmZieU8vWXM0TUdiOUFZL1EKy7FaGNz8a4zOiC9uZFwrxJRdIVwfPGIA
            xlIFe6mljrrys+pkVtg33UJHmIc7/ET3NoqHeuGQeLgFZkdgFFXKvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-28T08:51:56Z"
    mac: ENC[AES256_GCM,data:z308WcquDt/3Vk6IK1B4e8ZE+/k0tBMe4hS0CdW4qIzVG3pxFNdSG0OZH2Iq2mDVvW+Zee8LJfwkHUMBF1BKQ0SBNzSJJ4+S9uTwh1P0aNsPrYqpCPa0/x0Cqd0dXKl/b2V5Kck6MIlzY2PsZaBKVonadNyNj2ZqOACZU2IaD78=,iv:REEoqaLdm9XqSHfUapBuDldr2y/5Vm04iWIKkBZtSvc=,tag:F4TQQ3cCbkdGJ79vE601kg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
