apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:LagPqbaF7Mewugqs3F1kZa+BsmA4fX0XsJRe0/idvC3TvBqX1oYe7ZOBZsGP7wKuK+AueIs+0PqZ6HX7R2sOBl+PEWYZJJibSny0NnuVDhfNFzvb1plYhqWvDyDFnDjFIB0UwJ8NrVjKHTvemuscWPqt3Q4ZPLAvAg==,iv:zgxoF0De9Z7Acz8hcdESncIenWq/elFTAkzy4bBnprI=,tag:fWesGJ6bIvmpU/8MQTTOlQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3K3d1QU9zYUVPMlVUWVEz
            SXhKR1FUdDVVdEp5VVhQT1NSUmFXK1c1RVRFCmZ0V2pXbTlWZkphUG1LT3Q3OFJs
            aE1iVHpMTXcrbVJnSFNsS2hwckluczgKLS0tIFdSclltTEs0d3RHTjJGMGgrQXZM
            R0xVNmtZZGNDZEVrM1psMkdVb1MwUVUKDOF/FOGcbdwax4RUShv5yPKlWZdJgOL/
            01PkNhTLVzi7ITRbqKWNdRDByM9O50++YvYKqOQbtLSS9uvzd9Kjeg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-01T10:20:52Z"
    mac: ENC[AES256_GCM,data:PoC7mMJIRPiSQDyLDC5pqT/WtvvRpjTjBEFYEwBY00lA+gEC0rwCF38WSZth3MSKAfDXNoCtwHirY/MuGyJnrOPFzZaYk4A3n7pWQ/m3pV6KjIUHWqZnPJJTjd60D5Qxxu3NXGlgD9RUDacMK1oOciVhVX0K8614roAylrw3srE=,iv:UAZv0kXsExwRoOZuwTqclgb0Qhs+NwqZVkSJvUBUtUM=,tag:qWOFfk0D1UoNDyUJQIZ6qQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
