apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:oYzwq2vLWaepvvt/5yc066Kdi87QGF7tPnEXvd5LAhMIBG4FOktPlnBta+v9Z6W9hdkA97vk7G5WIKAA1wt2h7rLAjTlyeo/3SCJdcxyZw6CxuqfKp/v8Kw9MpPfWsb9tswcdgvXsYXc/hOKUlbUbrRr3xw8pr7m8w==,iv:zpv8kq2sJHMC9nYOc3xJnqzBCWlYtMEM3Tl9SSTnwbY=,tag:+PVFwEC6Qrw7pYFgyI196Q==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSUDRlYzJJUTk3VEljam5k
            Nkp2V2NlOHAzdWxDN0t1cE9SUHEvdEhLVmk4CnkrdXc5M0dwcHRIY3FSMzZET0R1
            WG9iM3EwZjJGSGVjVGhqb1J0TExtRDgKLS0tIGxhMWZQZXh6d1U5enAydUt4OXhh
            T25IaUFuOW1zaWtwYVdFZ2JRMjc4NVkKvlydBUDQR3OJ6P7nPZuBOJ/6J3SF0mK9
            CDNjXRAjFQjqXwfrBkJsndXvBViDDiOQwVA170dx8h0FL1hhOP/8kw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-28T11:58:21Z"
    mac: ENC[AES256_GCM,data:WWExVKUTsI0YsxOifMH5U9c68dApNP6v+KD+SgRbkMgFBosgavh+ED2DyKq7V9chGEi/BGfH/tCl+SgII27dwt5dcONIVELKBaEpXvQEWLW0iGo0uBJbOy+E1DatKP7VFRIVsgTJvn6ZvTRUHGXqOuqRGIdDcamS8hCymD0uH3M=,iv:ztHiGcLzw+QFe3gal46RMyNDhhC/yUZ9tRX1mJMrVok=,tag:d0eBjh9fGfOdMXMntAR5JQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
