apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:1QzsYcWRzGe5j1CrrAuA75rQpVeseEdPzSxDwlAzk8o2ggs947KQl6T9puhpL3+xhjA/zz5tPaOcZ4ddXMg2wOptnqJ58PWW+fYHRnHcUFBMJ4usyBRDwd2blwErr4afuMe3WWv4HINKRBM4aFituZAthALEMi5PhA==,iv:/wEVmAXmaIerqYEwp68WT66IlHf3Qhjqn3rkT6lEH1Y=,tag:GrrDFxpCQ/11bQgTwMS0sA==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxbEJ0NEdIUy9UQjJGZVhN
            UzlsM3k2UHZ5UjZLRGpGSjQxbk9hcGhzc0QwClhyVjRiMmQrbXFPbDBiVUhoNE5Z
            Wk51SHR3K3k3ZUxXekJGeDhZbmxRbzAKLS0tIFM0WUpXa1g0a2RFbU1WOG1Cd1Y0
            aUdwdlVGdEkrK3FzWThhazF5MnRjSUUKOrzDT4DUq7Aj8O9Fn9kL/rIwcGfb4/zn
            cnKUD+PzXnrU68fOBp8rt+RauHxhO01F+6z9ymdPwcytkFviCyICQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-04T13:06:20Z"
    mac: ENC[AES256_GCM,data:lfqwI0O0YFhhiZso0mkw/ESQ24KyaKsua1vwNuJgYjkCrx+vfoGq64knqZ2BZK/rDIm4MUj14igwJdV5Ki4mrKT/wAdnn+nlKNefuXOAcMa5b/Gp99gkBIW1D63u8X+bkfVHZz2Pz2+dFtL8k8eJu7DAzv8xbI7WPiaNvv+0gtM=,iv:OIcbLPPFYbLbLjJVxcXuS3XM6CXV3IJlFAhlBUZcBsY=,tag:qSZKDGJ/9+lYq4wNDl6Iqw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
