apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:/WmOPVUMvCLmE/EDQgPprN+FhWX66BPIOUOxJD+YAZMkYTS/bUUCKSrYyQKJoootJnLocFmt3neLClypiE4Vq0Qy0bl88cBUAkpO2II/oPXOL0sh1tFYidR86ua3dcCnZ15NBiFqkTtvW0sfcJE6dEhseYhNWF21BQ==,iv:DHYYhKGXCk7jI1UWPpOI2V9QwYDrz0ptwZbrU+90aiU=,tag:Dm0h9i+dqoQM+3lD5Krz6w==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4RnBQUTJmK01DR3dPWFpV
            ZW9LaHg0T1REWmJNb0RXNzdaSE8zWUlPdW13CmhRSWIrcWZXR3BzcWVmR3pEVW8x
            V1I3bitZT2tkR1pLNU1ncldldlc0UDQKLS0tIHY0bmhBNkRYSnRPZFhyZHRNR1dk
            WjA3aVFyaVdaeG1Jd2pwNnJwZjFybUEKdbSaJa+WbWpDyjE2Ib3VLgM+gi6zk7uk
            y73C/94SkjF1vFssXMYckSJU8aDEDufIczb9Yut5H1+Hiw6HsK/pdg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-31T12:08:53Z"
    mac: ENC[AES256_GCM,data:wuxyokAx7M3JyBgXj8C4h4IXyKQK0UFDx3lP3NwTKhjggtF+ZqmnieDTOVkhvXCdvYCrp83HURsoIJtdgYVN/XJIXk3pbh894/pa8W9ZSD4wgtTRbZNmDCrUmTC/0yFbdks5X4RYKLcW73lmWXbS9vnQzFCa/LHtOy8E7lofdDo=,iv:AtUmm2DLYRGuSDgQ92lInygwOBTWfrd2yh50xuJIgWw=,tag:Yvli7ENdkM2DI9i3HZ3vTw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
