apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:AnfIZXuZ4adXfKbuXBNRBKeV5wCYgC85bTIJ795ikX3xcka5PFdsbciKUOy/prnVWuJk7mpoNPRgot8Lybtr/ZfMjW2rb4ajGxS80F/CvQkhtOXGVsbtyzN/JSFZxED+IeIvHKgI5cKFKYXHhkY3dzyRfSKtkx6eiQ==,iv:N0PlF6TTHN27iecee86qq8Mts9I9MfD+hUKXgHnvnhY=,tag:FMTJAkekFHXNqoOVdIYGnQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2dnpQSGh5NjgvbHl0VEh3
            eGZLV05RdDk2bnVHcGphRENJWFVNc0JyZnpJCk52S2xaR29wUllCMXR6ZDRwOXc5
            MEJPbnU4YkxSSERETXVFRWhYSUdLNHMKLS0tIDRBWkZ6YlpYZys1UVhZRWRmMm5X
            d0lyVGJyeHduV3RER0FPazlIUmVyM2MKGCEd+PGch/aYHNYdkt6CuFr0uilQSgkj
            HQsy98P+zXrME7VX0T95YR6eVowdFmzZK+wlgfW4V6yYiwPly5BERg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-18T22:36:29Z"
    mac: ENC[AES256_GCM,data:SVmflg5dfLkbwlFZktBdQZR7iCPYEFy65BETLijbsDVOL4lqJX8B5PzKA51fFvvvncn14Uc+VNXh+poTagBboOCXuK1YzLDEvwlJtKAv6wVWb28zym+CwV3gsvPWU7argJrWI8tuoRpYfFMnoLrBg5lBupcsUqxLAp9737OefX0=,iv:SskChVz06QlWwhHrT+4m2vWXaJHlXfXu6aTWRvhfJXI=,tag:xig/G4F7UnapHFPa4cX6Xg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
