apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:Lfml11IY3sqJBFrJVk9t5fDMbljVW+4pNgnQOT912TBMELNFXPg0Z8xWH4uV0GERoz0Jv8uJ4hJ2ALrvhaisYA1pllHG1ArXE7J91l1Hp1I6RxpvJW7J32wY7WJGSXKWvh2UkD52SRqopo1SviCrUWqIg5qT81SYzg==,iv:cRCW6H96hZSAsMT+YRoE/AuyAbHN3sIvVjyJA9bmt+o=,tag:TLyZrrc0dmvyM/CAFonhUA==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoMTU5RGoyWGkzZU5WRitz
            ekVkNjlpZ1VUTUZZV0NGaDEvL0VicFFDd1VrCkM5UE16QWpUdW0xdjI3OXBUelRX
            TGtiU2x4TU5UNnBRM3llcDJSTHRGbWcKLS0tIENHSUZZUXBKVXJ6YmgvUkpmaUNY
            UE56V1BNdDhXMXliNWV0bjdFRlp5YVkKBJlVbJs+i2M4RHQve0xzNbsQC0RmO71J
            zQboYxFV3WfgDDw15TEfRouNKL4V5/sE2efTDEba+CMjVilbGSNAmw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-08T11:44:05Z"
    mac: ENC[AES256_GCM,data:4VxZ267qQk1jsnhi9TEqlp+hrX26TswNw7xrrkfNmjtwuK6XNbSDZLM1NG8tlC+2PnzCEJMpD48AwJpTb3sSzw4HGJtR+2LETP8WN4CRUctZ8rDiZwgDrIUcYO69MfRqjsQcMG5lvqGZ9X2ZeBECQiWMpCBRHdwkFU2xrPvuk+Q=,iv:VuI+KS29lh5bi/VV+d8z8OVx6EIxqh1WOWuRoh9jpXc=,tag:xdKKEy0uKWSoALu6CTwcwQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
