apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sinusbot
  namespace: sinusbot
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.truechartsoci.org
      chart: sinusbot
      version: 7.5.3
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    global:
      stopAll: false
    credentials:
      minio:
        type: s3
        url: "https://${S3_URL}"
        bucket: "${S3_BUCKET}-sinusbot"
        accessKey: "${S3_ACCESS_KEY}"
        secretKey: "${S3_SECRET_KEY}"
        encrKey: "${S3_ENCRYPTION_KEY}"
    persistence:
      data:
        volsync:
          - name: data
            type: restic
            credentials: minio
            dest:
              enabled: true
            src:
              enabled: true
              trigger:
                schedule: 20 1 * * *
      scriptspath:
        volsync:
          - name: scriptspath
            type: restic
            credentials: minio
            dest:
              enabled: true
            src:
              enabled: true
              trigger:
                schedule: 30 1 * * *
    ingress:
      main:
        enabled: true
        ingressClassName: external
        integrations:
          traefik:
            enabled: false
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod
        hosts:
          - host: sinusbot.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix
