apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: bitmagnet
    namespace: media
spec:
    interval: 5m
    chart:
        spec:
            # renovate: registryUrl=https://charts.truechartsoci.org
            chart: bitmagnet
            version: 3.5.0
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
            interval: 5m
    install:
        createNamespace: true
        crds: CreateReplace
        remediation:
            retries: 3
    upgrade:
        crds: CreateReplace
        remediation:
            retries: 3
    values:
      portal:
        open:
          enabled: false
      global:
        stopAll: false
      ingress:
        main:
          enabled: true
          integrations:
            traefik:
              enabled: true
              entrypoints:
              - websecure
              middlewares:
              - name: auth
                namespace: 'traefik'
            certManager:
              enabled: true
              certificateIssuer: domain-1-le-prod
          hosts:
            - host: bitmagnet.${DOMAIN_1}
              paths:
                - path: /
                  pathType: Prefix
      workload:
        main:
          podSpec:
            containers:
              main:
                env:
                   TMDB_API_KEY: "${TMDB_API}"
      cnpg:
        main:
          cluster:
            instances: 1
            singleNode: true
      metrics:
        main:
          enabled: false
      configmap:
        dashboard:
          enabled: false
