apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: hastebin
    namespace: hastebin
spec:
    interval: 5m
    chart:
        spec:
            # renovate: registryUrl=https://charts.truechartsoci.org
            chart: hastebin
            version: 7.5.1
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
            interval: 5m
    install:
        createNamespace: true
        crds: CreateReplace
        remediation:
            retries: 3
    upgrade:
        crds: CreateReplace
        remediation:
            retries: 3
    values:
      ingress:
        main:
          enabled: true
          ingressClassName: external
          integrations:
            traefik:
              enabled: false
            certManager:
              enabled: true
              certificateIssuer: domain-0-le-prod
          hosts:
            - host: paste.${DOMAIN_0}
              paths:
                - path: /
                  pathType: Prefix
