apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sonarr-anime
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/media/sonarr-anime/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster

