apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    MEDIA_NFS_PATH: ENC[AES256_GCM,data:ISxs5jh1VJ7D7iTdEN/HI1EEHqCSg4zhOA==,iv:1XMUXa3fwhLulYfyuTRJCNZ1vuyCN6EjytmUdpunoSA=,tag:1wbbmnD2CD5a7S92EUDWgQ==,type:str]
    CONFIG_TRUENAS_IP: ENC[AES256_GCM,data:oWb37q7wxflfX1lQmnQ=,iv:9JZUy5HtZryqbc4rj/7nZDLZ5m/EzNraD6SBzTitcjw=,tag:aZ2T+Z7L3/UN1h/mxcg1/A==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3NmlWTmI1ZHBDNldGZmdJ
            eTlyYThDWmg5ZEdoOFpha0tUcXkzTytzeVFRCkNsakFuZEIwaXFyNGF6elJSdEtx
            RHlhTjFrR3JwZmJXYVFMVktUU0MrVzgKLS0tIHlyWXg4SlRzWU5wc05wY0JlMzlF
            WnFtODRNbGRVanZ3OEtmcUN4UHlvV1EKE4kF7uRG98DOIDVZYigP4UBFemOVtXlu
            Y7FSB4BwVN+Kr+CYnkRi+GBaw76gQkWP4NnOi1VDcSVnj3hD3Zpzaw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-15T19:25:56Z"
    mac: ENC[AES256_GCM,data:TDeCvU44dRoOtmCAbAn4KmrdJkjNc3tiae3uQOHC3MlVJgO6vkPoMfLNmHi9Qg5obffzTG85gopT+wtpmJ8YerQrYT/7HPV2M9ldN7L0ISiWXaSKrJtcEM6HPyWPte7wWvJE+LXd1Px8aXDzsGzvz4PBO1i9LbZIcv/H4vsdDDM=,iv:P+Z2Fin6IH/VjUdjYigYw2JP/RJqDls+muWQO3jFMWQ=,tag:O2bI8LR92gyAjM80cDa7DQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
