apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    MEDIA_NFS_PATH: ENC[AES256_GCM,data:Qom0oDGvfFQp0xlB/cefVI8S7Xqo6nlJbQ==,iv:n4+Q/HVWHyaG/9Sinrk7xM5dbL6wLUg1lLtmcQGmwHM=,tag:n/opptrCn/igPVMWOG1gow==,type:str]
    CONFIG_TRUENAS_IP: ENC[AES256_GCM,data:IOlTWpjDITINaX12Cno=,iv:N1eEjC5f/XGXnd5m++KZcK5RdUZJxx2vWV1PLkIzjic=,tag:IXK4zkFiOas6A0AJEp9L2w==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByVUhIVzh6aHZjUWR3b3or
            aHR4Q2kraUJrRGNFMzFVMDg4M20wRVg3cTJrCnZ2eWs1K2hiNVJMTlBtSFJyOG9L
            bDFuTzJJZTk1Z1piYTRBUHVJQkEwNjgKLS0tIGMwY2wvaloyODBIVGxIWUphbENW
            STVkWXZiL3MvWTVTZkJvU1QvNVZuN2cKyVigrEyL0WE8eZ9UvtelLPiydR2dzJRG
            d1CjfpwY9TAXi62OY60l0joOycL5Z58sOvaRg0kyBphwycCglHvaEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-29T18:09:48Z"
    mac: ENC[AES256_GCM,data:c1HG0hwmHM2/jT5ehDeoJK9uIBB/WJbqlHeycrMv1avOstndvATLbOQH6pXp9AyOCyALLZSsPRHADX5SC/NZjzS/dddnhnuahMMgX1sg+yTisAx/IxIyBXL8N5tPW64OZ98hetWXJE3qlfssECIvcDAkiFjI2tJC0Gk0QSN9Eyw=,iv:oNOeXFSYIKl5QdLfOGEnsAaV6COiQEQjr44J0brxljo=,tag:Ehr481CyLP82zkiamQFeIA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
