apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    MEDIA_NFS_PATH: ENC[AES256_GCM,data:hoy3ElYjJfSicK6iDKi5TWwYlxrCOcy8WQ==,iv:pEVVfdVqRUU4c1Cy0KYnxNjZ4S/b8F8lBhkY8M/TIWQ=,tag:ZD1UuoxxSeTVTH6f8aLvcQ==,type:str]
    CONFIG_TRUENAS_IP: ENC[AES256_GCM,data:+s11tdMWyFLD+S8DZkc=,iv:G3sKaso++bgHWNjzSSb8RPZCPRgS8SkTAgeJgUzEPho=,tag:rt8Z498EUfXvwqaUTvU1mQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3cTVZT0Vmcng0M004V0Yz
            Y2t0bkE1Q3g2c0lsOE51T3Y1RlVTNlZmYXhrCmFMS2JkT1RUS0g2SDFBTStLc2oy
            NHhTRlZ6U1AyWis4SEFEdUU0eEN6STQKLS0tIGlFTmNHckJaSldPd1hQTWN4UldE
            VXZiTGdBTmEwajVtZVNwTkRkdUdjOEEKCpG0XI5bqyWwF/tnlKCBWmuRtjUgoCmy
            sUCzYRfjjCJ070cWVbGvAZAakfdqyttDt2kf+dLai3ngmaGCUsSZpg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-19T08:07:56Z"
    mac: ENC[AES256_GCM,data:hfwZAhUTX4exKDEFFfrqBaaGAK6kUzD90Acjzd0dxDAw+lxuce2yJkEONJN1UdHpVJ+tJoubCaJ1QwqiHFInDiG0ifc2FA8ivJGGkhOF7wMKJ9B5gWuuXTlnJh8H31lhxtdMbFo+7a67ugdbv5f9xpaRTgdeEtamdxHgO9L2x4c=,iv:V8/2vQsY+aoyfu838cwoHiSLqFejk/d75hwwYb9aCUg=,tag:DW4e5N22/p4TiRvkv/gF8Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
