apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    MEDIA_NFS_PATH: ENC[AES256_GCM,data:fpxaNsz1pISD9YZA6P2RrEZ1Znc/cSDqAg==,iv:9YCPsulgBsTGjwCcQIpFAl7wscaPl9wsX7ViURb9T0k=,tag:EX0/tMmzn5ZnE0137Hi7qQ==,type:str]
    CONFIG_TRUENAS_IP: ENC[AES256_GCM,data:WfhuHUQL/cuy5kHmshI=,iv:dcZiWS0U91LBrtSuov7LbJ65xvxgbz0dpphVRj5a2W4=,tag:H9O0MsOeThhfyOyb9nfZSw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3a3Ribjd1VzBoM0R4SXJD
            OFNIOHdUc050TU1EOVQ1a011bGc5YTFzaFNRCnZ2NXpvTWFLMTcyRUpkNUxOUTVz
            ZGl4MHVhS0RPNzBzS0oxdWduL1JQZ0UKLS0tIGd2RkdDNENVUnpCbDJlbThJNjMv
            c3VqNHFYMTNpNmk2cGNoWTUybVlJWU0KBIONlQdeLVzspavfoez5BPR+SrCzsg+d
            mOGgezTEcRgKBGthj5g71TvznyoHyBiSFzwZE9mxVEHd1nwLFLbdTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-10T13:33:44Z"
    mac: ENC[AES256_GCM,data:oVbMPLTt9AQ5AFQefy3/jKgDJNt2moiIj0uZwMix+6zOV9TlcdbUcfXaBr0jhi8m1C+JQTtG9yAvXIwiPXn4eWUjpzWoWjgToKLUqkcjORZQZDnTOCOD2s12oDeSzDZEZ3gML6CDxh8kRv0kxijRH/0I0DlqThm9MxcWC8B/m2U=,iv:qOQngNk5bTb23MJBBYHtbwftRozVDLfmlhRSESkfx8o=,tag:9CFbhVnSLF1W7/fifWJ61w==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
