apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    MEDIA_NFS_PATH: ENC[AES256_GCM,data:JFk8klQWySB6LLYKsM3o5aZQy/xAmllXBw==,iv:DXrw3AL+NfWAr2OPGcpFjOFjoHGT3YnTfpoxq7cEg7w=,tag:gKR3PmxvJjQm5bxFQ9l0bg==,type:str]
    CONFIG_TRUENAS_IP: ENC[AES256_GCM,data:8bch+ayg7pNsZBmOG9c=,iv:vEo1/7vHuhNv7SxULryhh6w7jA4wa4AztiR4wKq/+TY=,tag:CAOUToVJhzWniNxM9f1ePQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFUGQrNjRwYkJZU2U4V2lk
            dnB1M2g0eHhVR0ZpTlYyVzAzV2sxckhWZUEwCjJEdk1RQ1cwL05aOEI1SHN4c2sv
            T2x2Qkl1a3lkaDFwLzZRaGVBWk5zMmsKLS0tIFIvcnlId3VjTzc4U2NsWUMzM1B5
            S05kSnZVUld4WXJWNUI5eGh5RnNiNU0KLIfa/1y3saE7+k7qdeW1qgh2zUn0cBfV
            pvldn0DlRVmnZwEtK2ouVbnmJDOdP6w0bzU05uj1jGkMPLRd+gGhEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-11T14:57:15Z"
    mac: ENC[AES256_GCM,data:/Iabhw5/tFd9ujAwenftO0r3rs6rN70zC69blApYwSaxqXzXVm06XPj3xQs4Hl3AL/n/opfnCAypbrdFqwVRhCr9MwxNCmdmQlyh8HoNm/8JOqVqdx8cyoAK+ZmxncSJmx3ejQ62WZiQ4kQdGe2CnoMYuiWFll2NC4ubb8aGZqA=,iv:A5xZgSoN3Hx1kzSYP7Z53RjBdNBJXyAo5cYpg4ZtzPU=,tag:p0HXvKKbvjxfNUCKaRq6qw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
