apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    MEDIA_NFS_PATH: ENC[AES256_GCM,data:g8X63uASzzJC5jawSnU63D8K7nlNlyM++w==,iv:OKrdjFVoMEaBJsePn5SgSHJoq8wRyUNYIFg1Z/XGmDY=,tag:ngKh0O8q3TJJxMpirSGutw==,type:str]
    CONFIG_TRUENAS_IP: ENC[AES256_GCM,data:hQz9SQl03XIddcOqB90=,iv:99WuYsZUSx6+3Zp0O2W9YV92tCGKKx7z8ULwVmjzG2E=,tag:cV4brJH7TB10R8kPe5WlqA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQQVFGaDk3eUJ1RmN3anJD
            ay9rRmtVL3Rnd3VWT1ZnWW1LUTNucDViOFMwCm9CZnBGcW44RWpMUGlha0s4L1pE
            bWdQWWV1ZldrRS9WS3lOQXZmUlliMmMKLS0tIG93Snk4S1VHOVlzTzBnZVJNbjh5
            MFl6ZHcrcUpHWkppVStaeXowaVRYV1kK0Zt+4rI+pS3h93IP4zOm4mI6GnwuZXEu
            QfpABnwbFT2XXdl5rb1ZbsB3wUx09SxbkY9cktfUt0mrhzOWIuAFzw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-24T12:34:53Z"
    mac: ENC[AES256_GCM,data:Gb/fRfwBTg7RJdSyLBK+WwgH/fZKIenslPCli2YUHG+ggrarJI5Vm9F+PEMsOTK/xBJhDyoOdfcM8LmPo2d3/ff5cJIFCBD5/97kmlMA+0bje09oL0az5W5yPtM4fBIo3VYjPSmLLcfESS9uLkIyB/ETAZVk+XH/JNN7h+VN6Jc=,iv:i8vqktVJT/5z/pHayEadhQXCnE8//gOFFz29S6i/opM=,tag:J8IvvbDK9E9MeCfjWEK08g==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
