apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    MEDIA_NFS_PATH: ENC[AES256_GCM,data:jzlLD++pIAPGKRkInEq1jSFzhtcG/9o+sg==,iv:Jwgl1VXq0lHufqP3KW7xGTnzgrsrsALMlN+PJzc/rz4=,tag:4I3vvXNgq3xTjYvVuVzo0w==,type:str]
    CONFIG_TRUENAS_IP: ENC[AES256_GCM,data:jcF7zxjnym3MAk2P68A=,iv:F48p3oOzAOvqMOnqFKspZnitnsF48t5rxmyyywn7UjA=,tag:uxbf+qzinuKMgGRkL0NS2Q==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwTlpOWkYzZEdKNWxpMmN3
            SE9rVHpBcmtkdGgxRVBiMWZ1cWttTEQ1NWlzCnpFWGNaaitoVkVRT2l2WitOMklj
            TFE2L3lGNW43RkJjMjZwSVkzU2oyWncKLS0tIHJIU1VSTFQya0J2RWt6bWVnTUc0
            eGFucXgyUHluanRPY0NjZ0ltK3FJNmsK1hBAc28cTwEbwG0TAbkds0/J9Yms5d3M
            osLwbbwCyBy/v3beva1O+h6NM/bfO07bf4ZB3xsa3H9qC4HlGYo/Tg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-01T10:23:38Z"
    mac: ENC[AES256_GCM,data:dJoWRzZ9/gw4hRVmbw55MtdZmXGmdvlc/iqVNHzY/tUfc9gZJJcC0ev5ddjQg3w+f7T/ejK/12hcWMUr5Bs0KymBpr7R/qyXyUIpaB26RRh6HVuYhHmeSx3XnzfSeOO0S+EhkAV2cgJIpr1UHiWN06D5pvrXM0zu12oDcIfu5dU=,iv:XpHmGdLduzwEGpJdteiAj2reIchdYED4H2TFl+ODhUk=,tag:sTEhW9IUjoTIe6pJG4hxEw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
