apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    MEDIA_NFS_PATH: ENC[AES256_GCM,data:vDKMKx0TsaYTKzzxgdu87tIJTypSzV9V1g==,iv:8k8wxv4Pj0S1PQ2rybYFWai/kdy8oyygwJrbARabBK0=,tag:fl6h7s+V6L7KeJ0qoEoyPA==,type:str]
    CONFIG_TRUENAS_IP: ENC[AES256_GCM,data:7yHEfRokB1pFSQWXOOw=,iv:SGzwX1xI8IhDz1pLprmA8aeOlfXkxOo+phRf4ruPTgg=,tag:Ntdjy75IRalEYkOcLBp4iw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEMUtKakFrYkVDMVREYzVN
            cjliWGIzWGRyelhLb2hvbXpIYmFBNGdOSlNjCnFSOUxWSDlHVkUydW90NGswQTg5
            UEI2THVMRWxNR2oxNDR2L0dDY1Q0b00KLS0tIGRrMzZjTEhIb09RcEpHZ3UwcVUx
            dU1GdUdNdVZJbldhU0lsRFBRcnZoK28KZmnEj1E7vHBy03OsrthJ0VUJKr2uwrMe
            FyKSLNZh9drC1SSZ7YldNEae273NVmbF5MUb/H2URkFv4RRHVJvBSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-10T13:50:44Z"
    mac: ENC[AES256_GCM,data:idEZ/G3rNFbkwHlSWVeUhjUfvDA05vZisGoydX2ajAaVND1n9gqh9DzK/N62unWzPOng81o595nxLmE0FJBv+LN9GPBCY3IXQxjS2XWFHHd89R6cVGPwEECSNGoJV3W3pIqLQgyFu3kNsw3ybGiqi+d6xxfKjbKswI4pxJVL+Nw=,iv:PDvTbaWcz0fePietyND/6THhuaVs6LP9eyukrZ/ZH04=,tag:Q1CxRSOTMFh4UXYUd9CW7g==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
