apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    MEDIA_NFS_PATH: ENC[AES256_GCM,data:DdMtqHTnqSqUXEXXfSvDZBuLURMS1FXIEg==,iv:4iBILEHCzmKKIK/7Yy43efSAxGJCxiPtvMakA1/8a0U=,tag:XXIvzuR6BMfgCT2fYAkwwg==,type:str]
    CONFIG_TRUENAS_IP: ENC[AES256_GCM,data:QipTiDKqdkl7emx9o6o=,iv:ViuKRwdrHKoIXKRqIY8pWSNunEj3ZwpAoAy/hRRPytE=,tag:m6CMo2lPOlFbWQ/4iS8pEw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2UmVsSjFUR1JTaXVnVmkr
            K09iUmNTdTJFTzR1QloyYkIzN2lMbFFrMkNzCjk3SThyRGNBeW53cG1BMExLdUpj
            MVBjMTJpaFlHSndSczBiWkRGWE5UY00KLS0tIFFNa2MyMVdTR3ZYczhSRWs5WEha
            MDFFT0FsMmVkeEViN2NDeFptSi8rd1EKK99NqTWNAkZ7SmpsJP0xCPPn35n30+q1
            sPL3NgH+90HEod2PpwZBm9DwGDHBlCtZmI+AU5nQDJnE47jrO2iqPA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-25T09:44:20Z"
    mac: ENC[AES256_GCM,data:jzrrE6qpmDh7ZmV8qXz7ySHU8TlvUQMrH+ylVHIp6R1ei2wkOZPc7EoEtaXH0bmhRqN66NjJ9oGamoQDYLtUWS5aePPf3VVkLWLbJchfnTJXS5bililQTPuRYjuwzcjVwdEKaNpFMG+purWsgWjjrTvsEZEeAqn6/UK9kzbhNwY=,iv:3/0L+JWx0Hempmc2E5U1thT11QRMwbmT/eBoUDKohGY=,tag:E1ZRSGbksEBCiEoUa+ITfQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
