apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    MEDIA_NFS_PATH: ENC[AES256_GCM,data:M0wjV+GdVa96bg7ketMrIY8Ah3XBpI1WLw==,iv:b85o6gDS2M/KrCxNrkbGSdGE0K1v+yUycVq9c3FK4V8=,tag:0BVfj0PfVNgqIEUINpfJrQ==,type:str]
    CONFIG_TRUENAS_IP: ENC[AES256_GCM,data:3IQWjFU2HHTal3VYQdk=,iv:q9iDnymrrck9UqlOyF+gspRhm3fTDujsgh+qL125cvM=,tag:Q/Z9eFxY748uWeYBDwAVxg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHbGs1NU1IbGVudnFtQXp6
            Z3ZJb3gxc3lWTG0zSzFjbENsSEUxcnpzYjB3CndHMzJoVkRPSHcxbGNjK0M4ejRx
            Y1VIdjArNjhBSTh6SDFlT3M2RUMyQ3MKLS0tIDRKR3phNGZhQzM2RGc1eE9zOVc3
            R2RKbkFyVVQ3SVpwTlZpalF2eXpoMTgKl8GQO6Ih6QSwWrI65tm/FxyOtFIkR/dX
            FEvAMjP1xO0PNlqyUOVFZ0lpmy8Q2er5pb0lRaaRCfu9Qp4CboYM5A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-27T17:52:56Z"
    mac: ENC[AES256_GCM,data:spkmjVadIpLF9zJ7vERMUZlsrP/26/hVaVbZL914j6v2yEKMOVT/UtjALRGmMdT7Y5hNJeN0AShhbi3LNJJWu/1+f0JpMg8C9UpxJC33C0lmMzVRUwach5Qo7DmS1seEFyTnCB3+aYkvgpCnFPE7ajK2cJjrbubiX/ARwm7wt+w=,iv:PHkmbiJyvhRkibd9CnJwG0JvsBjJkmNcIOXpan6eUw0=,tag:wa8q59s7LeRvp/L+AYz4rQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
