apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    MEDIA_NFS_PATH: ENC[AES256_GCM,data:VwxuR3ZJ6fFnGaJhC/Wg0qesqVusqJPbXA==,iv:X8NpDVHeZGmGNxYXg9zZOr+hLflLd5hz6/fh1p95Jno=,tag:0UxYg+tjVWvcKqZl4nS2zg==,type:str]
    CONFIG_TRUENAS_IP: ENC[AES256_GCM,data:Yb+kARCuVqBwlRuFpMY=,iv:Tn33uOt9tBDfEFKZZRszz1aKfehX7aRqMcQh/HaqdqA=,tag:JySEnp7+K43Gv7rPXUQk1w==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBOWpiSmtUVUlNREluZ2ly
            ZjEwWUsvTS9LT0dhN0NxdjhUS2RzZkxTeFJrCklzYUtQSUVsNDU2OFlFcjBNUG52
            MVZGeFZoWFc4U2pXMkVKNkZBNTlnc0UKLS0tIG1CZzMwZzU4Q2VKQUdIclgwbGxI
            a3RydEVYZk92S1lTYVBVTnpRRTNQQlkKtL3pijpyQqBZ7eGLRn4A3XFPrfLmdytP
            hewI/1IqcIl1Ez3PwIVWR6ppU2NrxrwRMLV4bxyjgERB568u+W36hA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-10T16:49:10Z"
    mac: ENC[AES256_GCM,data:R54eXdKlcBExGZuAHU/SUDEeMXB7GXxzpu1ZoWdsVlr4VBy9YYgFNglqEeV6KSbcQNpJBeoCbXOJJP8xJ8IglqQRC9ki18me3qJq+injjF5f8ab+eQq5tmkmEkXlbldhl0zODnmdBXhSFvH8CeYqZEJlvOY+zS39UEznRK35jlo=,iv:Af0sx1oFxyZYKwh8wuKvqPgXM4Pk/P5+HrDs4kk4WS0=,tag:3lM2dXoYQB/TlICQTnEY4g==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
