apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    MEDIA_NFS_PATH: ENC[AES256_GCM,data:AsgPYX3CLaXO2hDhslE8qu7MlsI5PQ5UNg==,iv:ABD0IEWiYSj2szTmhg0aL8RyNvpIzEex+eAHDrfOUpU=,tag:AWsFkUV4uJ6+CxsyvGGHNQ==,type:str]
    CONFIG_TRUENAS_IP: ENC[AES256_GCM,data:tDVJWd7eNnKMCmb9mnA=,iv:3hP5acixo9SmQ3vizcghBOFlWKxEiM4/UXDltBxShqE=,tag:xO2TcCqtossf+X94ewWyww==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwSGJDeHVLRlNVRXJTWTB3
            R1RpRXdUR2JISENFSFdJTEJYOS9ETStQMkdBClpDVkQ5SVE1YzN3bCs0UUxLNnBa
            QmxLMHhLWlRXUWdSYW5zYzE1YlBiaEkKLS0tIEhmblorS003WUVwRGUrTlRWaFVX
            Wlp4NFlRY3NOaEd3N0tMUGF4bU1aUzgKSqnJbWh1opLnJ6qvKvEF8hukSurZlejK
            umbdI/dL2tE/mhic2EFzbl3obib96WrNiPCa5pcildJaDXG9aSsvFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-11T15:27:24Z"
    mac: ENC[AES256_GCM,data:psR49jVtFNPenRDfzxZCJqIfrTZt2tt2TjtvcYZyQZMUH9BIj5AxjZJ1eogjC2LhxvV8jcnNOZYjEn7oQ/S2RSBjCwGQLRhEktSZuGm7+cFI6msC0MEBCt81QPxSYSbiezOmtJf6rHVkKZGa/OjzKNRmUNU8x3qtvBVFRhxOtw0=,iv:E3Z5HngvQ72WXst+AwJgLMqW/oQUnpW5w2JShZVVSmU=,tag:FWEVNaOlnJKLyFXhUNYLQw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
