apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    MEDIA_NFS_PATH: ENC[AES256_GCM,data:SOmu2fOuV1UuOqH+JyxiQ7GounjfXcKJKQ==,iv:byIpKnOhgcEl2BCnsQR7seTxh6SV2GiWEvI44c7gjUg=,tag:XB4BZwhhNf5T3I3qjBaBCA==,type:str]
    CONFIG_TRUENAS_IP: ENC[AES256_GCM,data:eixRyG+bMOPTtEhQ690=,iv:Vp9VMPnO/ByPSs5n38aIW+3272tf119cc3D4UPelkW8=,tag:/Z5i9N+G8SxXwnlQZsB8og==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwMGlUOHhGa2ViTGdCODI0
            ZlVQV3BYb29FblNEZURPbUMxd2YxVVVCa1hFCjJZWFppMzhrV2xQT2lsTzN2Q2N3
            ZnJpajJEY0pFbUdCZ2RMdjJhcUkyekUKLS0tIHVPaHRaanMwb3U2R3R3cENHcHky
            dVE1NEMwNVBteVFGYTN4V2g2S2k1TDgK3NMdN0ICFHtNRTaJ3wGZUJ4Su5FIXIXp
            dYTldaNGq8aZ3ARdO0guFgEKMzU3uyZ/QuCwCxD9NqKSy8ujro6Cig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-11T14:52:32Z"
    mac: ENC[AES256_GCM,data:zCAfrRoMsUiSI2ikGl2RujH51rEXsUjG2xNRycyF9jegucgGXZLDPPF7OSJthI1nD/41T97mC+0Dst1cNC3sgtQz52kVnkxbT3k+pdyxscWfPqdnZy1ZULDgRrCqJ9xuhGj1mxIJ8iJ3oOnOcy+Mqij7oRbCphJrlwGePpTDJe4=,iv:15ezityr8LAPgyJrcUZLjBFwf4MC2L4XMjtkJJGEpsk=,tag:VtErSU02LolZlZvmCaZUKQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
