apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    MEDIA_NFS_PATH: ENC[AES256_GCM,data:4FaZOEYWqsAqMkVI9geHhlCO6kSiakO5lw==,iv:rjGAY7rq+OrFhPu55CsapEBbx5rHHzgFM+cScHgkUSU=,tag:FTxzTGsp9otasExUIrUxpQ==,type:str]
    CONFIG_TRUENAS_IP: ENC[AES256_GCM,data:kjbxVpC3nY9w7OVO778=,iv:wkgdkJWYC5MXuTc+AOWMnCsJWgPrjD1kVzIt7XH7mqk=,tag:qkMeSvicNzTblPVIevbVGA==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpRzUvZEdWeG1YT0dWOU95
            eU4wa3VSeUtxZWZ1VS9xNUNoRnBRbXFNZ1FZCmtpS2ROREFhMUtkSXlmeHlyblVC
            dWNvaFN5UXh1VjB3OVBzcUVSdkp0Nk0KLS0tIEtna1hsaGk1d2lpMWwvcEhQdGpO
            Tk1VWlBaKzVDVVIvVXhqeHU4WjF2dTgKvjaSDHOTeAOYXfPffGW/7xfIAn5czTgz
            oUV7LCHPsqh98pzN30VfDEJN5PGJI8BP5lBUW9O+hSaOZBCR+g2uzQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-19T21:18:14Z"
    mac: ENC[AES256_GCM,data:dCBrKrJmD0YWyNFfw9itStGanH2jTxcFrYTWY8rbxWapBNeizmSlhM6kOfsCNWEZ/K148duHzfod8GmUHkwz5rOaZZMNLgL/snsFu7vLOBR8s5En5ghIKA9+0c0M+VUl0QWeUnu2mSh/PqUb7yAQMVu0FEoRSlyqceI8zcR67AI=,iv:hdIbu8c6OFBy7iaU8E9wcef85bF5RpvhD2lfzb9/rxU=,tag:OOnlUiZl1xf4ueF4ayduTA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
