apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    MEDIA_NFS_PATH: ENC[AES256_GCM,data:d19MeOTm5PXkKzg8B46bMscg8WBmQa/3uQ==,iv:lGz8bcHtzTk780ArfjlEyVT2gQTdD71G9Nn1mCsq6TA=,tag:/sYxzJJ9h7aTEBUkBAB9Ow==,type:str]
    CONFIG_TRUENAS_IP: ENC[AES256_GCM,data:/m86FAw8qa+UqayF2Ow=,iv:bCCO78lsiPxqBvAeyUUxGya6Og5ENhWypA8/YWQoqig=,tag:/y6dhmYovyI/vL2Cfd2Wqg==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnbjhQWFJZNWFOQU1xbmZs
            NDR1STdUeGRnS3Q2eXpMa0dCNU5rS2czeFFZCkt3RC94bVJlTVhFcERKa1QzMUI1
            cWd5dzdQd01HVndseEJJS0IxSHFEeEUKLS0tIHEyOHNJb1FwVUhxc3VFVXdJSkNM
            NmpBbGtCZGZzVmlnc2lmT25NMEhyc0kKccr2IJykqQaJm/NaAI7j8JW6I4xNrfC4
            0THt6NF0zBGE94b5nYsquIQnknFqN+Z9eoU4qDwp3D7XYqklB8mVXA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-11T10:57:51Z"
    mac: ENC[AES256_GCM,data:Vu00W6gXQc1ES6Z6rA+/LcHB7+Xup594TpLEP80VpZiVfWKLuXdDcVM8EeN7AikON0jXUUiO4QR83e7QBfCMMySKP3Lc+uElDG1djq3ncY1vuRzof7gQ218qIpEZ9AtOwU5ffzHEsoj79CwjS3qbBH9gD77KQFiQIiep78Zc3b4=,iv:RSpreOnPOxQSsBY0DGrqf7YTbqePIHi2ptSQ7FpOY48=,tag:cjPwjy2w6MqnNm3klpO0LA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
