apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    MEDIA_NFS_PATH: ENC[AES256_GCM,data:x4lhe+SdT8JIBb6moYEzUdwfKXdEUTFt6w==,iv:r4nOQue9OrMjpGhn6YFW//jgLw5ewYnezwoORFTgAvQ=,tag:1DC04uj6/nPOiXmzfWVSyw==,type:str]
    CONFIG_TRUENAS_IP: ENC[AES256_GCM,data:pjYZHTmrIp3l1X+gQuc=,iv:0+tqejtBYnIGHqGsoY47FTp0HYwu5kzhQcf/Ty48pKM=,tag:Um4KhrOmtnvh4x/2ifcZ2A==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvY1hVVVFmQ2FXL3BmYVIy
            b2tDdEhzdHZIYnRucStwRkNCdncvU3NFNkRzCklVSkY1M3V4NFd5NlduM2VJeTM1
            Nnd3emRNdGl1YWFyNHU5Ujh4VjhNYzAKLS0tIExyZ3BpRVpicU82TVZFem5LS0Uw
            OEQyeFNDcXRYMEpFclRMZWJWNXB1NncKduuGHP1nrAqt/9QiP+KatPqsU1lXeTx1
            0pK4IEBpHTO5MiLD9QcxBi6xSsTiO+wgT5be/uoWwgMbzQeaT65eNg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-07T08:45:09Z"
    mac: ENC[AES256_GCM,data:cHeBFL5ICmGYvuexs1BgHUCWaRJA5O1b17sAbOtJF4i1Y/NM9WsUASHiMGTWrssAy4EsCHzbC2+fnxuKxOWVOFUAX6eFgrEfAqS16Zn/som7l3cka/5aLh1KF5U2VoUMBJjtmDs5MVICHe+Po6/+DotV2sMoKV/TWLmjieQ4tjQ=,iv:jOk2cVerrMRazReeGWJf3mTgk6UL22bQ3u41fMRAVHI=,tag:l+evq2+RNns0d/dZLLnegQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
