apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    MEDIA_NFS_PATH: ENC[AES256_GCM,data:b57q4zo3HDOHwqcYvUyap1tlSc20V7ulnQ==,iv:PFzRDTCgzLqEU/lhx4bx/8nDesU0FkC4RQZe0t0uar8=,tag:51/0vhyI6W3LbOzA+V8Dfg==,type:str]
    CONFIG_TRUENAS_IP: ENC[AES256_GCM,data:u8KqxltaYKf+lMXub74=,iv:Z3IHbMYmSjMgvhYzwLUkBR5EGW2TE7p+BSetORqyiPY=,tag:a0HoseLkgLrchsTxoCmzxw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2NEY2QWZqakFIYUpreVVL
            azh1YlZqTlFMbTYzdy80N3VLQUdJdzVGTEVvCmdXb1hUTUJvUGZTZ3FrMW9qSytB
            VTRCVlB2MThvaGRGYjNOT0I1K1pKaHMKLS0tIDZ0UnptV0toZjl6YWZxTmRSQzJq
            a1lzRUlFa3hBMUZRWTFiTDE5RUpoMFkK+PDGQGsOsr2LlidlF8iDSIQep+W4mqq2
            AzkfOOxpJaA6lf2AFdWW7xiSPIEFD7EJQIXEGtC6VY7fcEeq0fDlSg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-10T14:14:40Z"
    mac: ENC[AES256_GCM,data:la5YTFDB0Ob7FyehwWzB+t8n/oRuDxjuUghgCD4keXDDtRlKVzP2P7dGW75n3d+uH/KYOZGmdgbu9bt/HrOLA8Da1Y6nHF5kjTUFUdcaR97ffMwxL1oB/XEJnq24617juEUgUQ3CDanaCVDlPMKBwkzTSr1QH3aGhtCJEc9fwe8=,iv:BiLhhdkZasCcQa0j1aV6bFECsowp5h8GjirY3kormj4=,tag:5nL598a5nxkpgjevkK3JIQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
