apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    MEDIA_NFS_PATH: ENC[AES256_GCM,data:NnH37xJqsACxXC0eJeMRfgaAiTmIinbhvw==,iv:gVBV7oapGVqBgwRLdhm65XrYywzJppPAgFopFHEidZs=,tag:11H3PUCC5vu3WpVdkTUACw==,type:str]
    CONFIG_TRUENAS_IP: ENC[AES256_GCM,data:8DQn9zUwkTVezInVgeo=,iv:ceUQZ144rMm9ArRwA3OSW3eeY7lyeb25LZqVWOGnJ3g=,tag:ls1r7sVVLK3agnKUKSE3Zg==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNVTArZlo1MlFTMU5sa0Nk
            eGF5Sks0ZTlHeitPeXE2aklNV0hQanIxWFNZCjFRNFQ1SW5aUTk4NmpZeHJZTjl5
            a2MvYUZzUXJDOHBvK2VsY1NxSXpHWGsKLS0tIGVBL3lVcHUwWldSUllHbGxUM29Y
            MkxhNTR2ZDBmK0I4bVV6ZGFQTmJnRzAK/AxBMCsfEksBp7a9gzwzWPbyRI5d0Kj6
            2rHjw+k2OAzT7Z9rNBVV8yztcfaNdDuLxJ6UU4MiSGIq14K8nzr0Aw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-28T10:18:49Z"
    mac: ENC[AES256_GCM,data:jb20ZqZy3cLvuofcG6GsNOM7N4R0NWauT6qtz5GlpuQPYeQqQ1nGGWZmSKgVN9FgzjUWTS7zoYa8TafNse0wV7gW07YejlG1qJNrQML8gn0hZ0nW2+B04QIu+lF9VcWSTQDEanztWRSSiitA+yFnumUBTZTyU4hh86tORZe78Xk=,iv:VHE4LUMBxm+PHpAZ7OwQNDAdYzMgNwm+SAAnX9LJkSQ=,tag:yWUKwQiLAnGpXbT7lx5CYA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
