apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    MEDIA_NFS_PATH: ENC[AES256_GCM,data:zLTEiA70v6P56ZVQRnOGiYC7xreSSlTNKA==,iv:fXDcv5aYAoOZL/QNb09PNwcO7hmMra/TY3HttdVxSRU=,tag:0gvyy1vXBG8ok4dCmYNXQA==,type:str]
    CONFIG_TRUENAS_IP: ENC[AES256_GCM,data:M43E49G6vzKO7j+3z9E=,iv:1TKO+VZ6OSpkSLHV1PrpTL6jsrkQjeiVcKYQJdmCb20=,tag:kbIOnoQV0IhG/fbYX0xupQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDRytEQWkvMHR4QXhCSU41
            MnVXSENhSm5sY2RxNUhqRnh1Wkk5WHRXRVNvCktOa0NWU2FnS1NxWmZmOHZ2K0RR
            N01YNGRhWFdWeU85R1lEdUJkQ1g1azQKLS0tIHRnUjB6RDN3aGVubHlqc3hEWUZq
            cTFvd3J2VjRMamJQU2ZyTTZJZktsTlkKQ6/iSeeNyQlJoIdyLF+w5oiuN8MlvuGP
            OPTrhQVqcQtnKzg87T3jXDvruCTukEHKc/ereGZi3gLf9WMv3Kaksw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-01T10:20:52Z"
    mac: ENC[AES256_GCM,data:H7hgoMellpoHoqiRRQd7+5qkzzN/agxUrRm6vMDCp3E8XWTSRqp/lxFj4oeafu1gz+tnQH/DYBOBnb5z/Sy7WokoqXlQMJDBSZ5mL0W/5/VgQoAbvzumSKNZYVGEbGz9OheabOYcb3IDR3KRYWi554p/7AxyAFb1C8ftU921HVg=,iv:XadEJvJT988u6RS6I+ZxsVWWvlngKvWbAYfhzqiC9Z0=,tag:yYdeeU1klsIWdOZFe67sLA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
