apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    MEDIA_NFS_PATH: ENC[AES256_GCM,data:UuqEZaoUl2tKj3wN6GPsXqMEJMMunjhuZg==,iv:1GGSFdjwf5jC9x8Na0BRcOSrUEXSQHtLGP6lsXdYr0I=,tag:n+7DBPgsBuQGLsBtUxHPGQ==,type:str]
    CONFIG_TRUENAS_IP: ENC[AES256_GCM,data:wUcf4ymYmVrDwQtjEjg=,iv:Hk3nT/CU2NZt7x0uKH6V5TjoPXmB9lXTe4Kt8c5bTqE=,tag:4MKeArctstNw4mJZwdVFJQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxT284Y2VvZkdoOXN1akRj
            Y1BQL1hhc0lVMVZvajcrM2pNU2JCditiQW5vClZkeVc3Nzd2VENuWnByNUlJWXJj
            aHBkazFrNFY3ekJ0cVhjTHAyc0RPbDQKLS0tIEkwK1pEUWVqOGl1d0pwZDJLeDRV
            c2lXcEJwT0lNdStyYlFsRXozck9iQnMKY5zVJuN4FDqFYF5RhOQX+FyxcB787K0f
            MrQ6dgb6f3WTJuwmB5eDiTEImtm3BkraQ2BqzAP2Z3hP7zS2sCOoqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-30T12:40:45Z"
    mac: ENC[AES256_GCM,data:JJYxrDvvRhZ6iP2jMffh1rNiclraAddPGRmgJ5wLA+r4F1aEmh3/a/PUhB40AS70Qv/QliS0OWb+l9M8vMq11tOyylUFWDGMPl8iogYga1lRE77BrU64DCVlVr39hl/KQIrxQ3/gIXH6PQgY91ga5RCkrvYx8f6kwpHP6Ng37Sg=,iv:4wMjjv0vQd+Mco7a6PqrugPlUORc3Pt88p3j+NiIGls=,tag:9xIU50Fh/U5Y7u+WVPYbIA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
