apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
<<<<<<< HEAD
    MEDIA_NFS_PATH: ENC[AES256_GCM,data:3a2/yLkNhNDio58J8DcDjWoE1BNfBQn0eQ==,iv:ij/6EtJ815YZRn/DT2/OiaYDoLucAzvm3Yn3yP3u6mo=,tag:suIgTr2j5EmAxoFsSwQoVA==,type:str]
    CONFIG_TRUENAS_IP: ENC[AES256_GCM,data:gjZWyimbgg5yXasi65M=,iv:60zJ/mKrkUIbPSgAl9RqEGE2N7uauY33jBTuhKyFnhs=,tag:lJKA4YhoB108w2iuwujr7Q==,type:str]
=======
    MEDIA_NFS_PATH: ENC[AES256_GCM,data:l6nxoO2Y232FnZ+0rw5+42fBJIBc2cMPVg==,iv:Wo1R6S5dpF2S8C0+7xJeMtYEU0kFxgg7p8N4gFkyrkA=,tag:xOz5zjK1bLBN35FwSBDtDA==,type:str]
    CONFIG_TRUENAS_IP: ENC[AES256_GCM,data:PAU4yvmYCGajCrHzCfo=,iv:lmouvPAhYP52Gq2IC8ZZS0Lx/Oru3GEisqOyUu346gs=,tag:mijSVm2ltks+YimGUUUn6A==,type:str]
>>>>>>> 48708db (kubeconfig)
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
<<<<<<< HEAD
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPSHRzUCtlM05QTTFOM2pF
            VlhDZmRIWlpXV0NrRmh1WUtjNS93ZzkxMGpZClllWmg4azZ0WHNYVm9XekVad3dK
            VWxaV1lzeG5JQVhrbmdkc3Qvd01HM3cKLS0tIGNhbU51WGl2SVAra0ZteEEwNHIr
            QWRyMWxtckVtRVc3VVJKV0lxZFAwa3MK8CqNL3tkWlWgQd1OgaI0fwPKDUQdWpRf
            TJZcMKzMoAkZgQ+pFfCc+bUnth33Ewh7Ea+1nhycBFIw3/O4oYsMeA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-03T22:50:00Z"
    mac: ENC[AES256_GCM,data:ZKZ5ZZxN/yR3q2yDxN9Rpf7tORqPzHDewEEPLPdg85xycA7khhMRls5o41IOWgCj5GEH4gGMh3QcU7YjwYaI5wlmXvtcgDl1MMO5fOPj6seT+ckeM8yd3BRM6AzpFNxznCD/lSjYjoszMrK1RkZVTHf4aIRt8Xoylu5S+RuoOpQ=,iv:6/zQiNiznfiNWwUXlsiYtSDkqQha9Ho6P/CxXPDrND8=,tag:nu6v1flmJVWkAxHxqW9W3w==,type:str]
=======
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArU21RdzBicFhvYWRXRHhx
            ZG9Ndy8yRVBUdEtEdU43QWtGNC9RTnplS1ZJCkJ5dm5ZRUtFS2pKRkE4SVpSU1Bp
            SXFYRjlodmlIS08xZCtHeFlXaE85eTQKLS0tIE85dnRYekZVOFNVb0ZnWEY1UXZi
            SE4zTy9vSmVTMFo4VGFja1JwbEVPUkEKNauSNY0ye+G4b/UQ2WXfUrlz4o/DbNFf
            rrYkNEtqjbHAAB7z+KUMFwOuRIsl+AMgyrMroUdnL+6+B7nI9bQtSg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-13T13:57:01Z"
    mac: ENC[AES256_GCM,data:cQ7gdUgCsapiMmg1v5t8kASECDC9rbRyyBMrL3ST5L84gl4eO8UhpYHQU8aXSeEN2+EloN1P744G7lgkpK0wRns+YptJrmYmSGjOTT9DmYz15+LZ9qy+kHnF8Z8o6hzFuC32/Dp/SWa38CBDao94UQgNuiCaIYuqsGST58z/wo4=,iv:8CG0oL2dLLGjf+JbTz3NY+4p0a5b31aWRisVKu76qms=,tag:6rBrrxzJJCp0otapnDEDeQ==,type:str]
>>>>>>> 48708db (kubeconfig)
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
