apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    MEDIA_NFS_PATH: ENC[AES256_GCM,data:hWI1Li8oFHuMPMoD+Zzr852MdeWZZwQ5xg==,iv:fiKgVOPKIqGoa+zibo5gqtm8mQ/huqNVc1Pu2o5pEk4=,tag:+D1XhNlXWkShyN8Xk7r+Cw==,type:str]
    CONFIG_TRUENAS_IP: ENC[AES256_GCM,data:JQCQoMFz88AJCwQOphY=,iv:SvYm9RBRLtej8x3hFsBGKXxez5KQ3JVlIivhluQjaS8=,tag:3r08NIzBlM62FoxSsXL6ww==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPL1RKcjJtNU1UbFlCQmFL
            ZENnQTBqakpLaXdCbGY0NlcrRU14blRrYTNzClQxVTJvckYvT1M3QXJLV0RrdjRh
            aTJ2RU03bmhlWjBBdmZTV1d3Uk9IbmMKLS0tIEtraFhkSjg0Qk00cTRmU2Q3d0xm
            UXhzSngzb09haWlETGhZQytBelJjM0UKVfE9RFGOWODGCX0SiIdsNk2CJN4maHWe
            jZMErfV07Y9K8y7f8+so9YiGyQ5a4DxL5p5X/3bVFg695Optr4BntA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-11T15:02:47Z"
    mac: ENC[AES256_GCM,data:YvBe+BUmtawklLGbwVmrv00e69czPZ9k9/GEZBG/ZPlvjI/GoJoY4A5Up6hyLrl/bezvr3H2R9Vi1O568PRGWQq4DC9Tnl93Nc6Z9M3wMFaf4winyEZEGEnAlrP+Fa+7xJTWF93CVWg0GXWHfh16eOObwEgWC1h5tCuTxq2K4DE=,iv:NuJ7LOhN1HMGB5sC7zgBhwAaGdxUhRyxIwmJHt92GPw=,tag:5+vUT2qF8FVrpi4jqX1N5w==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
