apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    MEDIA_NFS_PATH: ENC[AES256_GCM,data:X8EGlPrMXZWCyv7+AO68QRA3EBh6QRfTqw==,iv:0U/nuXrpZBhTOLFIt2+brR99vuhu8UvFYryqoiVcrng=,tag:PNrGgoEUtBHKNlgjzT3OLg==,type:str]
    CONFIG_TRUENAS_IP: ENC[AES256_GCM,data:mgJqNyf/1IwqpI2NOLI=,iv:h8IpAY2keh2UVuckjSqQ4G8xH8MzZSl6KTNY/YZfItE=,tag:jZMmfA5cG0E35auwhNK6bQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5UkJsZmRSMnNDOXlJN096
            NWNhd2hsUHhicUh3MTkxSUp4d1NIb3FNWDNjCnZnUlFqMkVmUTdieXh2ZjJrRWVV
            WnE1Uml4TXBJZnNpOHptR09oWkFBalkKLS0tIFNMSDRuL2VKdHY5TE1QZlUwNER0
            UlFwdWsyakZsaXNSOGJFTlZoM3NHaWcKtY8mQ4++A2UZMOMPsjij6MLl7DszpPlx
            X8cL96Mo8o0b6wucFzvjFF0IH1GaaNjLpBp2Ua/Zw3L7Ug3PMTRVrw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-13T15:00:20Z"
    mac: ENC[AES256_GCM,data:LFoXXLoKLVAV+51ZtBbKr4tAdVzUDhAjhm/+KjJnU2xvPbMKqkYFxXiPaSin5BdlPV8diCazTiDuSAmvq3VTDOfOIY2VzKrIPp9hG4pwofWSBR3CoL9y9hCF3A7Iuh3EH7pIyQzFQtRmcwyO8jXxuOkl3Z8wCWk+hhxJ2XJJBrw=,iv:QZYaI1pvqnxrYVkxoUW4Y7kTZBzX/UsOqmzF8JgrjvQ=,tag:zMFlNLRpNH4ClCS2Glv8kg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
