apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    MEDIA_NFS_PATH: ENC[AES256_GCM,data:mKr/ONNmwbPtYAMq2FQt/CTlolURZ8dGQg==,iv:XkTmsPO8hcdYcVHo9B2Lp/qWMb/CNW+SEU+ybm7XJTg=,tag:6p7O/+Rznf8L0QQNmDismw==,type:str]
    CONFIG_TRUENAS_IP: ENC[AES256_GCM,data:6NnRA8MhXbatLGQ08N4=,iv:vBeYjrDqckY+EPUDgb6/NijdlEUz9IEUBQE9MRC6e/E=,tag:DTtiDnwiT7n+KOXQlQ68tA==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjK2g5VzNuODVLKysrQmNj
            VFlhbDRNRjJxL2IyWTZrWk5JZ3dFM0VSZWhzCmhCbTdjcTJGdzlnUHlKK1VTQkpZ
            SEgvdDdYTmhrK0xoVE1ac2c2TWRHb28KLS0tIExwYUhEOXQyb3Avd3hiV2J6TkNJ
            MXBDakUyam1LK0ZodmU3QjAwK0dDaWcKmPFibMQcl6+QAn5Y7wMiZ7HJFKFotREy
            uZlPrCvHs6QTphDrYqnJ25n3kPq+G6d6k3mxy0nWXeWtCPkBz3Jlkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-11T14:48:55Z"
    mac: ENC[AES256_GCM,data:AFpkELS5u6CMnuPXbWAujcLJw/7XOxzQvBMQMgJ1XtqEqH8dh8AaznNwaL9b5jZauWDwwJ46m1cSlqquHChrO6lFdR9DyW3bF7YZjww4FbUoUXpR/SIjG/1rMTElCc8/R2f/GL9hy6ZMHC5lxIu4q/JGkIjPXX1yvMD4KvRRRKQ=,iv:Hx2O+bE9j4Z7YxsMjoUDlH2gXnjR6mYuLBv1QIXmOuE=,tag:kkOA8FHsAUSgcBLAoBKK1Q==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
