apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:vyCt/7ROYl2dsY+rOpYkPS47tvWZbSeNKjPF+iwguAD885fMRKZZhUy30+ZTojI7k3KO6hevwQt+XDCH3mdiCXerAOSPJZmGiu7Ctfz+hPysrx02sF8EDom4VKtm4ZJNh08zxifweQIvOFWRaqcxT/vQ+BxMPN2/u0r2HG3nbrQJsHuBclW57IndGcFBHo97lCsQ+pjrCSL2j8z/E8eSpVGmAIEBzk4kQifYm+J8ntRJN7DNnXxkcsn59tM5yqT3weOoxLZUevubyqwpIv3bzLxawBuIffRDw62saT9wYdhPjUsJ2jSUAJp+6J2Uz6Yjc6ES9FJGtgM0t54cMkCzUtiHUN8guR1m7ArFt3wctz/Jg57mKoVfeHiGfOkeX6uU,iv:jSLn19VCx5O041Fvgv8Lge/jUB/sJS85cs7jBIRTxdk=,tag:1908PQs8IIPKt2AnxhZ4kg==,type:str]
    identity.pub: ENC[AES256_GCM,data:JGA4ocW0HqQ8Bx96vALF4to2KHAmdsFB7DtKacz5WW3C8IIrHIV9IgwWvywKM93gMrfKkcfgAxBltUgQ3IZzUXmmQ2yuNKG/FgQWGld/b4B90ooKAHY/rWGrTw3E0bTYgchkKMcMHV65Bi+59GfM45UJbuB8CrKN4X2ks3oLNeLn2cnt1FfHSzk1XokOkaxaY7aNn5XOKV1mW+DnLY5ggl0xYiZQt/NwO6vbi+B6ZvW0HMcOP0Mbf1iD9RoGEK7SFSXtZH72S5fewrCasg==,iv:+/ARXjTXtuicM0XisJGerzsZwlB5gBUC+q+6s6HdsAQ=,tag:FMZuhfLa0Cg7tY8IJH2ajQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:FQbQ69E/c/5c/l5R5i94J13BIVk5VB+5ob5hNBrb2rkZdRxH5DB9QCnj5mWWw87HSc4s5+6viiZReQkmzbqHJ1HQcarw1ZpXOIbGOuURHhezaTghjuO3qWGRa+cNH7B3zR5dUjGFsyQgZS51/R4/CSl0sqsJPzlb1b8CEU4mrHO6vEdePdkhLHCHvzI2TLdCtiapyteykhqhCX//fZ4/xTnSjxjDpLQA/Usm,iv:fT6+e/1pcE6K0xRxx3p16o61eSruXLIoSticULRf4M4=,tag:Sjo0U6RwS5fvUC8TPmT5eA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4Y2crZWo0RVY0bHIzUFdN
            cW1OTzV4dUd4UEgzVGFuaThyVmpjaTJEU1FVCkZzUEtjbytrdkNRajNMU2NBYytC
            cFBoMjBPbjhlcXRnQ042REhnWkZ4b1EKLS0tIFIrZjFMendhNm5DN0hSV0NnNWk3
            elc4KzE1aWlWUGQ3Q2hoQ3l4VW5FMVEKZYEJiEC/M/jMbbTXXKlvaFy0TuxjS+qS
            FII/G+sCSZ7pANCU1vZ3CgSg/jslAFKOs1Iw+/0x1QP6TnZjkRzBhA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-19T19:17:09Z"
    mac: ENC[AES256_GCM,data:m67BvyQV89MRsOMGrjuQbIXjPANTadJpFJ8YgnN7IEaJQVeJJ8giC4PO/sRG75wRuVccHx93T0o3md1OY6auRL4i6ZKQ+fbZPxKRLfZeH/LG4VD+kpSBmIsAFYlVvTvrzFl3u/xE2BUL7enEpXfXQcwtMk5Cf9zNpZjqtXZNNNI=,iv:7OkNlVynyTMTCDsNCcGAhYTTYYrcMo4/RUZufQcmOFs=,tag:84luc5ncYi20lfGBqdQkVQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
