apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:0oNCsJ3mumJrXM4KpysIzLHMGcLFtHCAtLvg1e9F64EyNMdQov2BRzN9Mj6obSBEKe/Le7IoV8rEarn4lUD750ZE6L4kbf6FxVBiay+IpbRCHma9Xykw69MYDJnb8tUt33Oaef+VpceGhxsY9gdYF9xBmTnYo6nERG27sxj66zPvHB0uVu2ZlL63wE+4Y/7xihwLld3u2Ep82Cl5fy+yWAxpzbTW2joy6Xl/bBnW5uHhGfvEGkeAEpoDqL9PImFrSliaiE5sNaJAXmx6m/nKBAv0ufpQ9rcl+BZgkUZxUBfukL/3ud949HWXWwDwsUlJI4VT4m2NZWlKnl3c0ORq1fXqGrLUPAselG8wiBmScNOwxNKVosTOiJuej2HfSBWT,iv:a4N9LMykSdpeaQszFiCEyf65fklpy2eBhROeMbHQscY=,tag:Snqwi6Ha3kMQrmhFvP1hZg==,type:str]
    identity.pub: ENC[AES256_GCM,data:mneAIfDt3hhwEk/+bRxutgll+4LzCZteQMvliXLDorxGKeEwUER2BNG/jZrTvtsuAJMSuq0MPlBcNSgdJqZ7vbqj/OUM08FKj1xVKmGrwhiTAOkbcpKblvBpt6vRa9/9KZYkVngfQgyts6S6pMIF5BAOsUdyQsZxQm9ClxmaR+sXQdCuNrryvKiIqv55MSVHxxrY486+0Rg1vs2eX1L+T8+L/VpkhKFiVpf1qxxGGCf4GM/ZexP+kA1RNKZDdqCo7aB1zevuEwqSBdAj+g==,iv:5ZRy0usmnuoemNJIL/B6wIQuhT4SwMNVvDutKHaZaSw=,tag:hvWbliGDZ4XvimyiJuCasQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:yneBYlBdufdwcl8z/klyPw1l4EJ6Gt1aIo7zhKOXZiqqo8vity/5yg9IRNdtK9ELyp0E7bwQx6/rjPuqQUiOnjK4hCvJw2Qy06Nldr01iZnJKPECBT/y2gws/seLI+uvZ2UPlTSzlbhDnLJs2pLbBL77sxmX3cMFRRBY82ErL8YzwTQVkFTWraAg6XRVpkHGQSzfAG6fM2i8HODT6K8IVJUZCK4jyP9n1nhm,iv:kNcfTgqiYG5MiU7Ww7wWSZQxNDm5IhbtGKL0KnhGxBo=,tag:FuFy7RfwbIx4Wm2Wkhz4MA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1T3JZNm0xWmhNc1R1R1dU
            NXJmYnozcktmLzBzOWZXR2RacGtkWHFQdUU0CnJBRy9Ddkl1cWUzVVhnUlNGb2tL
            K1hkWDJFZW52YkF6WVRtTFZHZGpWbGMKLS0tIHpmU2dPYzltYUlsdTNheE90LzMx
            RmdocDcxZ0hBU1NvSVlsd3hLYkM4NnMKozS4eA8GMLjsZFXqURzPWTuJ5YMoTfoU
            FNZhmC5TFNHI/owraeN0rioMC7qejIdMDHIlhdyFGgG8UU1PtMRfyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-10T14:14:40Z"
    mac: ENC[AES256_GCM,data:+k/T/LA82ir6UCB5rTsB1vk6LGD+NoTtCzvc9W0T3PMjulWMGtUexNs4FyDveqsFBKX7HUG7oQmPY4TNdZZYNMyUnZsLxXzves5x0HpKn6JZo0AdH0LNcIwWLEuV1ZuVNxbrScz5wBAyyiv1HHgJZOImiRlRBnhSO91hV/3rx4w=,iv:wWN75s2wC3dTH3pV0g7uQFIehTUr4nCNLxdcPeDzgHM=,tag:7c9R5NSalHb432RTQLTC2A==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
