apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:zp34cQzReeVsPphqFsaaJF10+zKaQrDDFRV5IQQnvI+uZ8fRgKvnBMZUNj9QTPpDjoe7GluUSpzWqkktYxiaG3bct/axyPJhLlX9qhNixS0k8IAA3yu094hpZ2u8M9NK0gkg5hrNqV4y+LiTXbvOgYILEN+1idkLsINLrLzYQr2y9A8pCtQ/OZmaUuM3iUvgUcPyjCvTxdhNaEcunPeHVWskwSDP1EZbTocvVNWfwwn3qwylSOcdqtUcu3L9tZMv0OkUjmyDURCZtuSVVeUNWMF4h8c+RLyTkAOtYFEw6n3nTpNfy9RLYjBxCcpubUA2VXRIk03EXNgz1hF/C/efnJKpb8fLLNc1+JJavDJcOvHm5eZiBRIFDYBDSij4rb8e,iv:bLxlkQ0tKIzHzhRAw+DbJkt2CQuCyfNrliscaGvocmo=,tag:eNGGJJ9QHUmASUlNOvcAKw==,type:str]
    identity.pub: ENC[AES256_GCM,data:zcyLbrv+0TqpQtvi0Q1HjNLw7kncpX/6SdYSOevuZrfdgHwzukyWNpyc/T6+0my0LCZLZntni+JbhKF59wiKyRuOSpOKF7/z7WDiSgkQnYokEIrbnfGkZzmcn0C21CvA/fJRpHZ738shz8mQhjHR55c1W3mFh/0U3rPIgI8NIKBLd0sXGWzc+wbd/CV8QOdKyBgp6Pk/tl0cq5KUnu6kuFcvUCdggz/G5N3kFWRp3VoF02Ds4E1/ubcvDD/seY4m0qZTsa47748q0PAosg==,iv:hd9QpyxcqRZMeMlyTe0VcGvw93hncRXbVZRqol/b6gc=,tag:JZOFvTTHKXrd9Hx0SETyrQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:iN4H/ddy5I6q5McMTHvR2xinktu5/HYVty9Sd193WqBmaTg0vH45+DJrI+Q645oCinwX/U9b4upHkwmdYYKJhq3E4JBJXfqLhUJrGQeRrJ/3oRipWfgJFaOoUoQJ7OWIcMRZI8tTtAMfNXkadWZC82YSGTSP7jV4Os7/ceNnRI0Ent8XMwvQagwoDbdG0FyJAzdWxzee/UFaWyCpTl6OExTBJp4uJsTK6q8B,iv:2fJhXW/xWJKN7aLjYCejKfTcJ+2Kmyy6BPy/J97CoQY=,tag:D+EzWgTzuFGJa1NNr4+llA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKSmt3WVpVdXhvY1d4UDZO
            N1BwazFIdHdaazluZlBSUnpvbU8wd01nS1hVCllSQnNFQUkyeU5JaWczQ21LK1Vr
            MUgyU2xnN3ZONlE0dGErQStPaXVDY00KLS0tIEkzVWtMaHMwSnlMRWNPR0ZSQnl0
            S25PWnJ1ZW1ST1hDcVBOdDlLNUs4K00K0F4+oEXRNfsd6nLodiTFK6BUqVsss67x
            a6eSyVqxjYPsEwBTPQT4YWhiSs7gBO/DM0W5TBUHTjlmrK/TgtAUbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-31T10:35:12Z"
    mac: ENC[AES256_GCM,data:3YMF89Cii/hzIznEE5OYCGtQE0dkJ7MLmVBlEZfBHQMZzsHl3/ikbjA8agbXbbwhOEwop1LtwTEAjgmDO0RVSW/qOdMLwBeSYlqsnI8SBQCUQhw0NZNQ8H1+HY/G36KwFyt+eVOLeDCF9WgMARz2j3ArYDxbQ8kNtb/kgWiOqzk=,iv:dQ1SGKKUXRjT3sd2YxypQHLY/kBBcBzvhTMxAoKiATc=,tag:RL16DMjGvXWd2N3tZLcJjQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
