apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:enckHSuRIGPcGbk6GDC/TVmKfVEVeFxxDUqbXK74bBjtUsO6hlE+aBqOHHOsm69Va+kHYmtVjtEamp717ZAVr1BIuKXv8GTKRvs2oPfqLNe2SyYiPd/FPhszInI8YKweRUmJxHWUIGvuOugAojeDuG5MLdDeQGGj8athwZ2WHscdAJ4jXD1hVOlMrYU1RoGzC37mYQJ3awDrOgw7eAfZqBJunQQq6ciazyLR1YdVWfbt8eN/FOHWX5h7TJqU2hvnfJYxOSnXq/UwmoEsY18bAtkfrvjISuH7VNWeVem2ITlWo6Z1Wms2yMOHvjYaen6PdmNtVqzQkqt5L2XnRXix4stWBCVpOe3AvJHFAdlbbXZVcONn9RcxLilD/Zdx/Wcb,iv:pd1FRjQ354C6UNLbzYxPT+GQe2BdJRQK1+9z3IeRFw8=,tag:haQpn4TMR04JUaj6m9PO5Q==,type:str]
    identity.pub: ENC[AES256_GCM,data:USle3vqq3dV+Mv5rT5BOHzDYfgb+jdmuHhZi5Ll/RaFvAJjOe/Q+D+Pe923TeVicuZrcmQxh7Tuqo1tOApxG6UVqEYVO+p92syYV8ZjyAY7Lf2kLu/+6ClWjkRQ/ud7u5J9xGazpVoTYMxoCAAYh4OylIFUCx11VH5TqjtVKgezEazDl1S3LQ2ouUABZUd/stEEN9e6cy62I30r3m7Bmo559AAzemmy/NiQNCI8S/A6DJ8hZEvx2flSY7l07MvBkBe4ROc4gzcJZEsd5mg==,iv:phNy7DdLxjbSmyTpgC7f2conqcfXIo71riS7NddWT6E=,tag:3Jji+YnvdQeHq5bjhDwy1w==,type:str]
    known_hosts: ENC[AES256_GCM,data:Xs00IV+WjZkvO4KK3HuWBlO7eR/PUnTEXpLsMEPhVxTBxF2yHOD8Ti9j+s8jU1qntzJ0ryPdM2E1TJoQCblrreZr6/rMgjPFSvncUkroal0lJIhOydBGsPOsK9jgtEDFTlLDK7NRkLKg5am7lNCnRVFdmTsvG1ntHVtZwnqHi1sJZFwKHgTGUfocXupx5KSU9mX6PcWEsW1CWmHlYRNNOavATa2zc/olzFWV,iv:Mtkg1n+89Zw0pfuESmDgW3rGCbt2IoY6tZfXASdeLK0=,tag:CoNwRx8CPu9Lls9k6MBnZw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHSy9iZVpNOW9hUlhMRHZS
            QlovU3ZQemh4c3BjVGN1M0RJZXlXS1MyRG1ZCk9SOEpZY0tVdkxnbW5BSysxZWF3
            M3RLSXNnRHJlNjNiMVBqVmk0b0dlMFkKLS0tIFVoT2dFQTJUUkJKK2lpVjVHZEw3
            eWZvOXlYQ08xb3NxT2ZqVjNaTFNlSWMKBKHKGVrQKJmup+HmCzeMt9XQrVlNHSZI
            poRJF0g0Z7iIgMUTlF3TLM3Sj0UKmZp/trnfvMo8Au5qngxQkq5Gmg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-01T10:23:38Z"
    mac: ENC[AES256_GCM,data:6f/1ktQn0j6YxEG796Vre3x2GV8W3DVl0y8h9LYTXoM63Dx2JJ59K0+2/mMFT1N9C9JzV33Wf229dBx6Fzdx+oyxif2/uEY7LjUSH1a3ptqJMiF3tWAWELS5i2yr6pXypdT2OpsyIhZCLk5VQCKf2jDi8xwWbgoNEhOPUVABoqY=,iv:k6EtZgUEDU8IxQNqIrAmIodufABay1ePcPgTbHvv4lE=,tag:pNc5EqvcCu0FGptSFUuJjA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
