apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:ejKWBfy3Z7wr1sVkM0s03ZirMFeP9yYxY7sQ27hsAtXubKstI2cIz6F//t37lPlCImbYi9Dtm393sMl/5hbSgw4ilwc6lzwa0VB484PiAMm/Y4H4bfVYotDelInufr/hDzIhCiGZ7NJlHM9QvjaMIT/pcS8+6LrI1oEYqDpAM63Af0ENUh0C5F2AEJzXF6tKr8YAA7tj7h89tYWzTgGRnnJtusSciXZZkAEn95ituut8X300Bqft3E2gnMMcCBQ3rQd8BFekayGyhxj/bKITKw+l49pziCPOswZ5ETmW2jaKdw2o0oN8VZZkJ3KBe2bEO2XyS1kzgh3plv3dXwDM0CczcftkiW1FyGHJWzJvE6eVk37JF5+D7RVK/0+PkNIB,iv:0cmMtN2rt5OF1w+0/HIf+qPAnRmHsOyBtwcnggbO3C0=,tag:1BJ8IbsVWPrfTwRo0q0Jgg==,type:str]
    identity.pub: ENC[AES256_GCM,data:2pIn2ZxDmkQlxxzfKh27TSH1Do+l5VErYVpngwsLkl+z3OihMLw2b8O4Ja4ja5BiH9E32L+Rem14cEeMuhIt8RmHRem+r0PDUEhatFFV5F9r1MT+tmDPKkngRVbpy4AsrsINSKXSq07DiOomqewgx9mDRZ+FMBK24YdfbriSvJpFZN4hUEMXfHIsYSNhsKHONsJ8megtcUm3thEAkjqefszFOmCHMXjeLBU3lnXV4gvpDwaNICiNEXu4BZt+9ooY5lFLfItrXb44JqyxHA==,iv:7sRlEUf4pRLjNH8gHDFRrlm+nz7ttw24i7FbOGUElWs=,tag:n/I6lD3r5tZGKq8KMx8F1A==,type:str]
    known_hosts: ENC[AES256_GCM,data:zi4sZQOBQY4omnYChgEKiBjd17i0xAnXbXUCihtkJKgxWl4SjKb5m3X2JH1nCr4fYIIpvP+DBcXmd3a4YFiZmKF5Yvv5DifHQfYBl9KURwA6LVaowtJLmd6GfGMvpWVy4bBNZUS2ZlBZyr7l61saK3wb9zMOWForVs1RceSNForgGQ7PMb8jAMcXDLb3cPm9gzJ6GQe2MaITln+oLIXYGyZ1A1QywnRGjlSu,iv:3iV5wYzkOx3C1ijAkwE7Oopk5YGCCE2GNTzcP6ySiPE=,tag:oAJrK22MQ9tsfa1K6HgT6w==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBWldvby9jUzE5L0UvNm1o
            MzlOQ0tOcnVOM01CWUJPVkhYMXNKZHJOeTFrCjM3KzdDSDQ1T0haN0RhZDVudHZZ
            UWNNYzhqa1VWOGN5S202c3cxTzlQcmMKLS0tIFlPTkUvbTZsZktoeGFVV2QvQ05r
            dEZOeFJpcGtob3pHTGc5VzhoZk0xL2cKADP5E8ZUsLIJmOlPUzzYVlH93FQLw8o7
            k6CiDO7sWtTEluUlT6LSegDr0ByCxNDbHCpLcrIr7epSvkz4vkMJAQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-19T10:42:12Z"
    mac: ENC[AES256_GCM,data:1mt1aND5ovvkrSVgnFrYu1FFO86u+u10Z8v3UrLmSafoqkHJ/NtlgwaxMxPapYjPyn+jl1ZKhGON2mFBSwzmEFmNx739rgOPHH0WX9UCCgVQP86dsBS8bsH5F6AFm21D7tbg/g/o3VERxomzNcAppqvJHfmuEydM0TtI/prm+Hc=,iv:FJYFRyqNucxJmKwMMSaEpSUYXdctdyZrd/57m0wYRec=,tag:6c55x9KblXrnkxcnO6OYIw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
