apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:sfzVzzL7nQl9G+5EzGHZn7GExD7O1Inqox8587a8bhyzZy0t8e6GzX9MlJMQxbBSMd9A7Q1ehGx5U5ra/W3ga9XM+MBw1u4a5FHjkxCVuYxJsE2c25rcWzs3QscHko3Q528ztwKeY4AdXbjeMK7sKDciZxPkA7jWQnbisUnLQufVqFGYqyw6mK5Z++04X364Xq4fcQzUWMGwSCqMDhqlESo65KhjgCkXK/rXLH0YH5cp86X4EvBTDN6dyFRUvE2nXhIKcPqI+dTKsUW1kAJYmZRxcs3KHuqq9l88iOO/LlyXKyOsio98RdzAA1vwz68XbjIGpfS+eBNXUqXIm2UMI7g1mvpGuMYkv2oqDTUfEtZLityZu6XcvhENUn13fmFp,iv:tj88RNounZBa70thUltcqESlv5wKrycQL/pmLXEwkIU=,tag:i9BV2m8tBs+mojWbbMre5w==,type:str]
    identity.pub: ENC[AES256_GCM,data:L1uJztYExxtIt5KyK96TG5Vbqd7X7Ugz77j1YCKiTk+WKdr+SKNnohaovJciXSvQUnR8M1lRJa9gwptOYg0bpZ3C4tUOU+xVwub761UYNwVl36fSAjjaRCMKeQ7x7werg37FsU+2Zv1KisOBkONzrU7yjbX0Axuu5/UKUD6NlJdc9S5LXWJndXj9lASR5uRmknkgMFWjtg/9NMaamyz5fXfLvFkQOIWllC4IZcgspcNFdDlASq/JPSj4Y5F9nHp6Jmct8I4VA8AV73GNug==,iv:N9nYhZrqmXMPrJs/4PYURwZ3atxPeZbTRYKt8Y7lknc=,tag:17z4Mmeqnnjuxw9hXIXpAA==,type:str]
    known_hosts: ENC[AES256_GCM,data:L+XlwfGoGFCbTTD39F1VoQIR88EU03CcPfmRMJPN2J98dBxs+30TXhIPUCXSNryaGeERDjax2P/QXpGZkgBKOs0v6ED5wRWcKc5CBfin5gGGwLhVhfVIappgtNvf99hXlRJ58GHubsVNXWbCMy5nFkoEf6jfjSuP3ejXXzxZ8hm2yzkPIUeZdMEqERw/e0Y/hIzGaDtiBZIKnEZInqBpc963eddhyLfGOXep,iv:wrt0hRY2dRVJxzyRMPgk7lylF5TKG8WlmdTZ5iVvB+U=,tag:w9QjTiPZ5WBFRsAMrQxluA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoZEpNMFVEZ2g4cmlObUUz
            dzdYU1NSTTZNQ0Y0TVVDT1VMeERER3JMK2k0CnYzVkJTcGVMY281Sk1YYjlWd0RV
            dUYyc1BiUldJY25pV0hvWGJJOUFKZ1UKLS0tIG54QUFKc0srUW9wcUZmWTFzY2tB
            aUpROW1wVHNQU09kczBTaDhxV2V4VFkKyr711Z5Sz9DO+L0IXm1LHm1pUy7qWmPz
            +2SLZ8/J4qwTEBk/ZE1JKXyuNwbNcwMnlr5ukH9GIow1eb25Ct683Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-08T13:12:33Z"
    mac: ENC[AES256_GCM,data:le/2gE1U+d43qQ//oAQRd88ycgB+0zQ3ll/sblyPy+ZuPxgVtYhP6BagfXw2kSwZxkkzp/mlooKl0EKgIPbtHk0in4hKyiuYvDFkSzqf1wjL7nUwSoAi0ME6b85tebDSejPjl8O6pf+1k+FYemiFdKIEAF7VbnHBnsy7yqpIslE=,iv:+zMCcjkga709y/uNl4GVHwxMmRHZZbkIlsE15e3OPco=,tag:vm+rmuykCW8m8/Ty7tFBwQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
