apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:PvigcNbVSrq70sLuIglcFczPSWbrf03abyT7Kx/3sEfscFpZan5oKUy0Zvy1vGrXX34UanSfPTbEzO8mI3cKbMvyNvTl7efUDleM2VWQGFqtsK/pnXfTIFOIGf3MPKo7jTf+ZCxM2MzmpIt34NtzL/AUFXVa+3DqtDZ5jqNpwrvVCLTSspUvhDjSnJMs3YPrbOHo+PysTa9q099tpaURjNEhAWavCZxryh8WsowJN7VQhOcKgqZlyecZYEqdH/uTVroyt1+XJZ8L5pAlI+v8czBsh0lhHxSaiWKl0rSO9P8eiwsnTThVHKtXXnhBjpjS+dYIpeSETaZFlvAx3nN1E0T5Y8vURHgFV/Icg6YzrdudecRpHpiHqnIs1JEECeL2,iv:SErv0DKQPsxIBMoEFNOkftQoDckaOVebXb4SQU7W/ZI=,tag:nx0G2PE11be60+TIjmO/dw==,type:str]
    identity.pub: ENC[AES256_GCM,data:sBImiHdpIE8vNwOEBZiof2M5tZcSkrl/Vjt9DlKVL2lEaetpiAPkSzhRF01g0LaCXANbLKf7PoaMYOKT7/SyCavkHpTgOe2hLC7QMO/98JNutyZDMiW8cU2G7INIDHng5gDQjC24gbyaKDkeBmtN57kfy8riCA9vUS4jbQ/B6b+z6/JKwG0ygwV8Qll/GUm3587xwvHPpwAglaJdPtEj3CRbvCD7OlTwv0fwDkqiy2ApPPr+3/LAeGeZORCtnbwCG9DXCrrM5W8FMLMxEw==,iv:psP3Ais/18ExDF5+dqMzfBiTtXLwsmxsFA5NiW08e0Y=,tag:jjJ1KouwbGeoMW+al+SXZA==,type:str]
    known_hosts: ENC[AES256_GCM,data:bqCSGjK0Y8EAolGvnZbMw9DVbZizJ0MC4bjH3xV/YwwqEWDXXw66+iUdgBk4KXFVcF/9d7GLdyACpwS8vHUy32rnyvBMhw/7JtGIwaKc4VL5q5Ob97aVWjf3aJlxS2kAwZLGHSr6XNc9OQMeFzJby+ETfOzFg0QZbT/JwiksRZFaktvEjSfAtexlenaDt45hKXipDWjcmh7necfiU9GoRUhM5IhxmaMpRDRA,iv:o9B0T3HxIPMCJ4ZDpRCcD6cyFn7ObXkdG8RLm98BQdI=,tag:XAC6ozoDbAD03utqo8T/hA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3T1FCRHlibzRwb1VOWDZv
            amNkOWhzWkZnbWIzNDdJTGFzVFpaQ3ZEcVJBCmVZU3BnYUJJcHlOTGlkMnlNRjY0
            S08rRVBGbzBUaG1Ndkc1eklkcWNHTkkKLS0tIGYyQTh1TUEwNUFWSVoxTkkzVHlY
            eEFMQUNHR1hyMmVWS2NZc25WbnhJWmMKVxTgoV2a7AQ0zYapmFO8826JEBkusEoI
            LlusENvuQLFmP5n+c5Rve+vUI2ZttHHAc70qkGarYiWunUjiDY7HTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-11T15:27:24Z"
    mac: ENC[AES256_GCM,data:8wJSXdt1+yxDTGLQogENILY2CvfN734MoHafKn5jSd1wRTsCF/yB89Op72/54rumCXWnPB6WhG7R4Orm3O1iC2MfwylFPRr1x1uXV/92/LcUrGFci+cpKOEA4CHq6hXfY0ppl1X2ZyRKfdc6AA4OKHCNWfydAIbWPz+7L1RnxZQ=,iv:kQCY+H0y3lmnEkHbKH2lAJWzoJX/Eayx4adyloFPFAs=,tag:FtKpyMGF5VAYsaRyEAnLzQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
