apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:0Z8DDWZWqva/trkEktLya0D/YelMsa5GGJRrkxDR3tipbTnoB+4GqVJyNxMTJX8InVXrISlLJZ3YA4ezsnZvnFwBhE1w/4FlWKhplWIf69d7TzT4pR7lMQRRe6RqxY25ia50UOmPPDMuuix0Ea3hvgBF9GGHfPdHJygSWBIFS4Beyw6esh3UPWyxDMYClYZLWQWYmr5ruXp7VRLl/1jstCbW5fhN2kpeCdKnY+7nQlaVAco+1c7pVuUp8TvrwVJMQKuH9f+Qu3O1HQgM3IHwf0YmrvRS5sk+EQ3OkZswEQdGi+a9xJBzm8ajmoRTH49XNC8cBK68bBmrb5JgR4/12Z0dZ2COJULL6rLAUabmqMcYROIV2rkZh2K+CeuQoCrf,iv:bljol7HSGU4UHiGQ4uNjcbrO4XYylvsRVTQFkz8wq8U=,tag:a/e5mnLx30D/KJDj5remmA==,type:str]
    identity.pub: ENC[AES256_GCM,data://SvDU8hBB52xMz7etMd4mRkntXLy5j1PCv3fhhPZtHL+wk5701guel5bVM8Sv9bLVsQhpnZCvRyL6mFJ3boaUYJk8jgDVVtjq12EA0lBocxPzlrusjRP9CdIlHe4NF7FJYExunnOAXxCAIpn2KcwW/h9RyA7RZkv+VsFYH7cMwo3XmyWvw6/9k/Srs1HTX1+dq78QW2wQrZKTnwAeYMmwd6E0D7WiBai43qe8asEFB/jyXA7ZzYUS62v4h8xXnDWo0PxAgDIw6uzIj99Q==,iv:GC1b19M/6t6YAbtSA7/vOgEy6He1P5M2lEBNfYkch6Q=,tag:Yq+0QN+iKuNagoy5g3j6HA==,type:str]
    known_hosts: ENC[AES256_GCM,data:rQohTYD4Mw6Zng0Q70imKzF+HDeYtVD5tBAWmHa1LfhBA123ekcLM2pX72RSiwrBVdwMMZPQWm27BYU4nR1JmG59f2Zdi6u2GdlR8TcnH8BG0J5gKNbWM83sjEfZqeiK431uGNN+7Zr+xJIP4/7MmQ9jPbMUwLAiT37xGwyW/bv+y6+eIqaDpvb9W1cyzPRFM4r802tM3F4WLlKqIvUmPigDE3kpBPEA/XVh,iv:9piVUgu2A3707tOD7X4RIZ9ZdXz4Jt3bFoQmB3WL7R0=,tag:w+3Mf6T/kyd/aWsXAPB4/A==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOd0dObDFiWGlPZncxT3I5
            UzE2VGIxck5kaWhNc01OT0ExRE4vOWI2cGdVCjYzWEN4R3B1dXpBSDVTWndhYkh0
            eE5wRWdrMTNtdGhvd0owTU84c3BBcW8KLS0tIFFqdVNjTExlVkZYTGVDNDRNREVm
            dUs0aTFycHphNzI2MHU2NUN3aXBuUTQKu5t44hoJZ06oc/qPaCHgCqFp9GIMMqsS
            NuJLgj3bqFMvWeSzdI2a29M9jOXk5THOriDBAMt+iJDfK2lYqeGp7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-28T10:18:49Z"
    mac: ENC[AES256_GCM,data:Sr1bcIvMbbdHJPCaE+QHwQyotskEkvLyOqCw7ddj4JejSw3xIwyhnocZ3IQ0ur2iflYdQERaV1sSrYoay9JbZcnBj6J19ub6W0Fx+6Oj39fgpTe7mm+TVadhr7uX7NWofCntd7zQqZUEf+OY3NbRu0UCyuqMhJ876ma7XvseMyU=,iv:0XqjlxfOh9xNJneY1N3xfzuSHYuefQQILplJDedoPa8=,tag:aJCg0F8ucWusluwYl9lhYQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
