apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:7pg9BPd1crkWtGyqmnwb8YVjUijEArgNcRrJ4j9jE6s0NI/b9gsRkTHfjgmlx9wWOE8RoGkjRcoG8n2V9FArWTZmFKz9YWzqb2o0pGEEbHTTB5QjY1WTBO/wCMSNlC8nbMzfOdOwXYwL0AgtSAt3LOU12f7X8nxgVrA5YFGz05zntk+W55bZ8q7pTOGvsNu5uXyzpGTthQgjlFY6PsptKLe5uaEKAGr96R2iD4mgHpvUtOoWgUGOQ2GeBaO8zpnevzlf9ziYHSqGE0d+vVKafLVe9uGybhUXBX7lrS8A5uwJ4yuOJVhsZm/HutFJH0adXteMgby1Xum9x9b/hjkODbqkLl5UCod60r4qxRPwPqZjNW6K6iWnalpXs3zeSaod,iv:yQCPsRg8A0C7EyO+fb7/xsYea7nBdtR1xuPOmq9ji7Y=,tag:cQab6tGzjN266v+Rl64KrQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:y4xTRglJHGKW1xnb2/CbyuHlEP4jfbkzNYryyK/aBFS3Ila+LRD+h4xkra/aGBH6ubyg1UGISVDQpL1ox3JII3+4AbLPRJxxZxsnw489vYW5Lkj/41phXeQphE4JdWyWiBxBHTfaJ3OEm/IvK/AfJ9H+VtU5b4ipLxrXOgpAD2r5Jv1eunci7wRWrsDRWCaFqui/Mh1En+C5SePN0KoSxHzcnpQZ1TbSnO0ZMpAvNOENcl32MNE9CQzySnsGGm5JaX/EwqXyG1kXJgvc2Q==,iv:c8mTPMhb+x/pyXPCv6TUkYTe9jye0uPqavz+IDC6JHk=,tag:DHF2T9L+9VLD7bP/q2w9UA==,type:str]
    known_hosts: ENC[AES256_GCM,data:t94DxQmxEIRoa8kZPg/ukDiweowg2DPCPNm174FzKVd0rdF13WTWuneQfkIkB4w7sgCD8Tj3fJOOxdUBgKsWB8epbYR7u5UaEdMVmE7kMur/aLB8QJ2Fp2VtFEsY3TzINgVGpkeU3zFcDsEvo7A7qqYzk0wFTKIR09vm+vi0+WjDnu5rhzH6UzXV2zzRf9qhWEpJ2QylwT3KsbTSCqS/wZ/XZfdotmqgZb7C,iv:WuZbtiapXRkPnxbzh4s5IRGDcRzBmWAfwhddVn3+yvE=,tag:5ae3No3nXGi/GbF3x/q6Xw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmWWZHZEVWajRzRm55ZnQ1
            T2hxK1dVRTBjbEVCWFdhZDVWekdwb2IyNGhBCkthaEQ3eU9VUDVSaU5QUzIvSzFE
            VWZvRWJxWUVSOVM0dlI0YlVUWHl2cXcKLS0tIFU4ZTlCYkZpMHR0OW1ISE8wN0xR
            WXlvbEs2RTZ6K3lRTnZYTzRHbFpvNm8Kc5hzjWCAmpxXtMnViztqdGdRx5Covn7j
            Ev0fg4C4CpWOIePxNBU6u4AniBonLHeKnUwZt6raY7krdzI6xVWrUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-11T15:23:57Z"
    mac: ENC[AES256_GCM,data:S00lWkLuaneWk8hQMSW1/IWRqs49kFr7rnh9FmM8UM06/KClaZ0AuYF9gObz1Nl4qGBtoyu5/mu1p+kYR3YrCnfg3O46RbPnf4TfiuG/9yN9K7nRnQ0sW8OnIlqlXug9+CxFkVoF/Pg9lfYjLS+bu1hZXM1eAx65roFdERsPpLM=,iv:FCBhVnDBH/u/l5gOTJtmmhsvhkzAvs6DSCJPe4OamYo=,tag:Ahg+fzIAF/qsX+88vwngMg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
