apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Geb+IP4MwwUJW/ebwCO9hXTz3N+g7E9resE1RwdwVInUJVGToVib/zxeQIIzZSiHAkGD0fsCZ+kihxOPEVdj87/JEyr0qWbowrghgBmGvPXlto4eL+cC/CiJ/hSeeQmztqt1ea0/cJSA5vPmhfU+KYKO4yKj0OtOGaMnK7Ni4jggqnay4udS4wOR1S6KiD8X9pSYDyym6loJm97zbsuFYPHxs2U9p3gLRDnWSZJvDv6Dh3wZ/RShFexf9qgK3gjaGYSaP0XhGVZdr0IRdd9Cm7NkviNtJxiE7KSE5QnnHv7CJfQ1DmLuJuHlEENjfy+kebEvPTzTZYRyMOy5JjPF0B1sy9agsQUaS/ZpBNM3VatKXx9jJnKkZ0fM438Lj2QK,iv:73NBt9Wi98Z3oDgvIJwgXz3e903ekKYt/Jou3LtTnfc=,tag:nAFJoUMiX4zITxih39mWcQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:Yo5Gl37wqTJYL+B7LLWp+f6q9kHYiU/wfaEoSYkAHseRwcamFtTNsp3xZ9IoMZZtQfQ6KkXJKOadSV8xNFNXJjMBeKwYNt8V+lf6uOx2hFrW8klD7oZAihqHj91Nn1Rd5D/Fm/bb14IKwdGuKtZEuy3V+k8Kr9EweeEIphGijKgr27VbkG3uxjE6fHWjqIA5xQnBft/SeqQjAbImz34QFj9+Px/tWYBceZw1YR+KaHgC3+EctKJG2DA0RhZXDD/KWL+DJLO0VFzd0PnPZQ==,iv:qR8tDxjOXDBRnGjj1kuuQZqum7HaSasvYJQaceNtZ2Q=,tag:O4jZjQot2l6mAN3l6Gy/rQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:hPsUtPn0/KgcBvh7zIrChxzjwkjDow9O9sLdnusOy/dS2TAE9W7ymD0yvdKhpD4+T737ebBFEUuy8HPfi5UBLNwWPPxkRb7gJ4SsrmQzu+V9LA1Ik0vuOIkWZF6HQ9EOagavImC0d9VWbg3FAdOPt1lFbYsyT27NLNHRL0ZNvzx4RjaHG8mj5M+L/eIrc/frXEzpkGKAfO+Pp/QAF9+9NC9gh6mFH7gDROEb,iv:ahoZMMtpxE/mTH7t67BvGlRqy4vKSwHN11eLQfh459c=,tag:Twvj5Obl97VLVcMNUNCQLg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2RDhCNVltdlE1Z09RWEta
            bk9zUy9tOGJkK2R2T1BuR1cvSytNNmNXREY0Ci9tNGlEMkVqSHkzSXF6SlNGVGZ0
            YVlSSTdqUUVhc0FDUnhzVUhFcjVKUGsKLS0tIDJhcWhEZzExSXhHR3dIMGhLVGNI
            bi9ocnpLSnVsemhpdHZ5VVhqRVM3OHcKlCSpas02TFo/gyX/LURVbpF0i3r8Ktsf
            UxgVLz5tm49DMMIMOxGzOf8Zh28fhWhzkoVoZFo+W/3x2YtxL2kguw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-11T10:56:55Z"
    mac: ENC[AES256_GCM,data:zictwQXFw7207sQ6YcsCIOg+CmdFqzFtSN1DWTytKC2/TEhqeKy2AgCSN89QQjmt5/pOa4JpyB/VYWEcTgEfqjcFcI4jmQocjC6T7JxeruVtwG92JfTbVZA2e/OaVJ3Xv+eFod0Vzvlvi6j2+Xx9R0ZAIZ60lmiXTt/Qid/Zkf8=,iv:FxJDLG7QiDVvWi6rva4TUqXssidIZGxpVpN1d+bPSC4=,tag:yX/v4QxmaShfI4mr/ei06Q==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
