apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:TOJQJmYAc5NcZDuI/QmitjWmPy8vZ1OmP2CQGJCX2EHLfU5ZLPvMtGQ3yXYllCslzsvawmGNt0co16wGqPR7XfJYixuH4O5q3EB60Y9V7YKAVJBFZ8A9Ukbdj6Rv6wuMcomJu1bxrkgtFbvsEQYHGmBF0YgSksqFsj8lYOxoOY23bUc3yH9Uy+BQHJLwMhbK6SxeyTE0nstHQriCCyMldE8GB5Jbrv6GYDxbrmRoBaWmiZBOqkJyX91HZkkF/l04zPR1mexDcEcycpzlk+m32YSZopjgLZBMvIGowzRJ7QRuc1nJd7yknwZfcI10JLNFTUY1PRpFzEZ2y77X1fNffnGkBQwHL4RKMpXx+un6hVq/fU4uDQKsTVczDYM5npOm,iv:/K9i40ufgCQxhpAiTIpGsAzmfLZ/Pba2QWUuYIKDfPo=,tag:jBaEa0XVJbOZlckpzehIHg==,type:str]
    identity.pub: ENC[AES256_GCM,data:zRGdywpygw4xRwcyXjeqeo8YnHJAhIVOPown2OwLrz+ACmqPEFWVR2/ImjbSD/JpukWfiO5NoyM9sE7eTLoa5qfqALjqhh1bHJxRXcdPYnHtatLWYCacNaPmGDp46VwoKBjfgKETsA03t5/7e10VvBiJj5Ypey+HX2astJuiXKMPMaMrhW7Pz5WSf79plIMgttR0DxHuhKX6gTUXDZqeyBDBM3LJmBRTShy7gL43ssTQY4SqY5652SR3Y0e+iYNsLVbNZK1MjGm4spbFIg==,iv:RPt4cBOYhWhwanrt+0dFXRxftgfpuZr2Fh67USoRPT8=,tag:aQ31ZuBnbWUlU2ubv9TcTA==,type:str]
    known_hosts: ENC[AES256_GCM,data:la7oAj039eDIotdw98MLn6x+4Ku4d+6uMwD6TJBvUsPnOosmdAOSOOn9UElENIlML3qav9Ib5bpqw9kmV2YnBeaU+i4JUTuTe0Qt044VwWVBptm1M0muRIrYjqUHVR8jqfJa/z/6mbaoAySAxeyIMCyI/ygHYd7HsID6ZNivWIZWYtXFt45Fdg9PXVCTQoWn9/dttL4XjWH7hdT5ucqlnAzC7SfoQEELcaJz,iv:fjfyrbws77KbBiFGeZ4KdRbpfYCfM4X5P3fpTbeDVEs=,tag:gPKywNGYZfawB6BoSezHZA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZZGU4TzBZNmhSUm51V2dy
            RW40aWJ3S25senYzc1lmVUI5TXczTmFEODI4CkJES1paeWE3NEExNG1KcDVlN1pY
            bFV4bmgxNVFkSWdYMTUzUUFLRFJZN1EKLS0tIFAwUGVoa29UNkhkVU1abFB2K1ZK
            UW0wSnlXck1aK2N6RnR3d2h0TGFETGsKtsolTtHwa1Q9JqTt2vbqIHAYBIyhjLRV
            a/UMa6BO/1vOw2zKXLhs4un6aUBhC9qKcoDNau1QdZg5teJACcOnZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-01T13:40:47Z"
    mac: ENC[AES256_GCM,data:G4t0Fur3Rw7PlEMiHphLebZNF8DTjV/5xU/gsyxvuFMsWslHopkybZ1Sn/UxaovtfXDr01Zbz+c/vHRvT2+X5bbl7uZO31u0ZLOXLzNTB4yZapJJbfMvDoxGXE5yswfjUe8fqCG+r3VWA6Icul995vG6nI46OA0I5KfliWaMwJU=,iv:VS+oIK4gKXmUmFRf97rQgB+E23zEiTAOvZ15M8EU8+Q=,tag:qoP1QCrsCTLf53dMpXMJxQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
