apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:MGEEdciFzu5/24dcwOn9PENS2YYfjeaYO+oQmsWhDM07eT5ELUc8pgBhGVPQrVOMHMhU3Zm+5eqmkvRATse5A1uVwbB8y9osNGuj/q9vEFAYBY/EatVeTlAGuNAjESDz2WVwc6Sup1feC3xyr4TJTFGaoucnus36/neARyn2issjz3ud+IqG8WiW/2LZKrlvF4c/QMOXwI01pR4VCmho2QFCg+8KNHYYZ5XARg1aAbWyAFRowx3xm7z+vAx3FF4hWtXzOqDYUtEPl2FVCvA12eKkyCrj0lIL4Q79I4/wt12qJvK+KhC+LGxxeOHfXMszGAn8Q9SITKEI2315IM8xN113WcDWRv4JKU6b7BFD3N/SoY5XBJVt0fJk2IZATbEJ,iv:ZEky6PAgjJuv8z/81KnWpxlXJXOknE9QHwK2tgg8ycw=,tag:mOkY9fqu7AciNY9cgXRPqQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:vrp7qPT9dBLStNMe7bpSOqq9RC2ovdkSwHhXoh08ktnXCj6GrJhZTb20Ks7uVMKgS2DcE9XiI4DJHQf0oVNUzvC7kR5rJYdc+RmS3iPKxCVQJ/V8zACeaZwuldbRqo/LJnLxJmspfPDj1wqVw0QlbJqzahu4R7QS8uLBMzlmXTpqevv+qul63TAq4maRsjNthTwx5WILMShzbuWoQbWAQXC9qbKBmQVdzh2LXw7zLnRiXUC40JNHT4a0qH813t7CN3Zs/4HPPSkO7TURQQ==,iv:7lgpH97fTV/CITdvlkEusQpLMPNaF5utQT5AVfjiMrA=,tag:ykJYnQTAJg5lkb3cpzs4Aw==,type:str]
    known_hosts: ENC[AES256_GCM,data:Fs0TuAcljJVRX0H+QUuZK1u6gbhcyLGfjPGLoYZ3zbyPyLazRDyjtoMFeUalaI1c427HA7aYXk4/joF0Pn83gG8XGXubNAdPFLgqHdqKsf6dVvTePpzxmgAYRPmDii6eN7vJ3B00yJC8/bMClVmO2pTyurWcLkrjDUfZbjCZiXydZTkqKfeRB7xwpIG99fBG7wU3ZY6HS6PGsOG39WBRJhx5foQHNLQGessM,iv:FzI2x8zojSHJxU4G8+YfKtPKEDUvOR6RmKzpUhDO7Gg=,tag:osXKtbRvhmXRnR4KhwQTyA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4RWJSNEJWNUtvVE9rSU85
            MWs4TkdFVmp5Y0hhcFVyc0gwS0JISlh2L1hzCmYrMEcwUCtZaVArYkkxcHUzMXhW
            NlpsbkpyRzdBeHJ4YU5jSmlSUXhLU0EKLS0tIFVFQkpPaUwwaHQ5MXcyTkd4SnNl
            MmMyM0UwYUdqL2tDMmpyNHBFSTh0SVkKMuzjYf8ho/vrDHA/rRIvheYqSwtCQjKE
            iside6rQVhX7JDWxeu1eS04L3vQc0Ln8qwp0y8gbHWvatfKRFB5nSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-11T15:02:47Z"
    mac: ENC[AES256_GCM,data:VRce8zBrNqUmafg5oye8uEcgDpSIZQM5bdw9r+L+kWBMinC0jOXL5yp/7AsBDBlbQK3mE91M4CkY/JINKfw3wY0nYdrSnU2b/Sseo4dV7oblvu0T0jLEqQnpDhwJJMFxoOioInglrQvYjpHCXcXu3cZY+p7TefZqx38kzadi5J0=,iv:1sG4GJL9ja3huPUVIbCyg7nqOMYq1TT2wCmNLJ4k+5Q=,tag:REF6CO46ZGAUkVH3OnXZNg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
