apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:5PWtqwv8LSljVW+sYKMpes6C6zKl7S/LLZzO1snK6TPHdtZUTpteUC4kMrqP1FFU/RMkhy0ck8VnrC6SDycoO8pk9uz6x75EzcdzWLqOvlJrPOZ6Ht/Vx68MQ4Ci9tKDfJqWkPmadLi9QmRtgpmqjQiHNMMCorJm5opadTcX6CHTgLsJNaOHt9PfduUbgxLDdR8z4mozLPfMid3mV6Lj/t48YrozwkXOjuguzIZacNiZRfnNT1RZzqo6WPeo4G/Bpd3j2B5U/ZeRKrqlzHFTSX6Gn28OzalPA6r3NEp5RMX8FIjxh69gQXgaffhwRG6ylkHhyzsYGidwdBepb5VRey4xUI+C2EdN4DTslUfsXs23v/xxaocTgel+AwgWMhJp,iv:PajfEWkHgOPPUvG23AJz7c8bNEKSO3K/OBpZ67vNVok=,tag:XmMD1mFXAyG3u/nizr/8eA==,type:str]
    identity.pub: ENC[AES256_GCM,data:/lZ1Mu49O2q/zr3KQ7N6u/HfdBgq9Bgi4qhRc9IuifbGHIqsMrocK5DB4N2pVNjrHsswYny4Nl+GhZkwKymdzySKKXALRBqd30FiVmnnfuwnF88pFTuppoxrXuEPsNUIKC2LP1MkIcGVBA0JI2DNhsfcuNZO1o0/P6C8fmhw6sX9DmGorDkIkw0WlLRa1rVaq67eJxvYpuAQof+om3r/2PeuGQvzDlDlwk2f8FumXIze3smIdGAw4MBaNPngsohRZ8Dvei1rQRtguDKU3w==,iv:qz1aBLMkrUiqI09miGWSYe13ExmWLs5Tl/z8TGFBQfs=,tag:RF/H38Yh6CSwGPfOruFmwg==,type:str]
    known_hosts: ENC[AES256_GCM,data:NwME6m/Hvd44p+N7lexsw0QcXZ4WJqGQXBZdrou0rs2oGAC54MA6xR3rTgi5y1Lpj4qAZWOSYj0VVbyJ0xniqejt5TwlB7kfHQdooWS6c6V2Jv3FNfnmUlCX+rJ+FOxp2bPaO0uT4FdIy2bA801Sxg0SXUr/teWOJ3SY+KUYdiCm2oH74TJnzv1lQHxXyN7Nkfsd5uFOaylcraJhhc30T3opAGQ0SFzDxE68,iv:NvBE55gLxl49EyURFNP0roAPNsSIbIcRP+IsIJJFtf8=,tag:t2xrX6041hibktp+leRsgA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKMVFpbzdwN25aVkZVcWth
            NytKY0VpM0hTV1V3c0RrMGI4aHAwNlJIL1J3CjhpVXhyeW9nbFJ5aWx3cWFCL2tS
            Um9ONVpCQ05Na3Q3QmNURG9UQklTaGMKLS0tIHlBRHV6V3lrTzNzd05vRlQ2SEVp
            UkNucnJaaGl3SkFSbVFpQW1ZZDZIdzQKmV5CV32CADAAk9G3ndnjLCPg6b9xNaTY
            UNGKS9GwjiYNmFqGCOIMNJHiMbudcupJzw8EFPrw5bub0bWPiHE5vA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-27T15:37:43Z"
    mac: ENC[AES256_GCM,data:asoaJ3E41dU8P8ts+7OADqnxBVJgFReybzuE/mMb+5qpRxpGlbAAAlplrjMzeRUtKh7y5wAa+xIklshKFg5KwJCGKjjFARzdZuPQ9ic23JfpJ7PFz/TL7W/216s14MJsT41xGG/Ag/JgRYehEP8Hi9iPUcKUtnQa7kXOYOWS8eY=,iv:4TL4TxG3EICQrOgfaGw580lsUaUuGzH3nQOzva5dnBc=,tag:Jep82egtrGVkSh+7aq77Nw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
