apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:vXcy2JrXIOlOPZo/7OqL5ui6iFYkzduOTrPcY9azcERjEaazJVNW+JBn1DmCxedpNQVUQO2WzmZN9bd72IVhoQ7vwSGLdU72rpTwWKEJNQNNuHhS8dJjoxOnidMyI/k8CALg4k18OoFhFn6E7hhCmz0VTmCyxYzw4feZPpVcTP9+WtK2uv3wCLXD0Y0AQ0oBnrTFRDnjswcGBK5FfQwoJ7ni6aZxtaJf9m2UUy/FqVwYIVta/ZykLyzXoEWmLZPFrHY/2Nh+em6wTbFI2vtDrlHlsv0otTMTE5DPuEZQB+osesO2EwbC9xFUSBn2/cJAsKRrGSjm4t4ldLawlHyAj7yTJCEz1TyFvE8O6VLiJPeCM+qfH9WRXUT3cxHMX4oR,iv:c6cBHMgmj7lZtKHV9qNqJqpIE4LeE9rq3JIgpwgkZ94=,tag:XcuW8/40QS7Za66xFy9nrA==,type:str]
    identity.pub: ENC[AES256_GCM,data:zl2kx21/0bDj9tM2OLN8esdiI/80pstNofFZM/23QDgXc3L5RdvZ7qpHA+GnXXi/p/adjQYNbBDZ7s4bgYLTuT9N8WwsSKrCfiu5VbXHTfBJkxGJA7Tv5Jc7XjeP4e0QRZbFsVsaQDxqYVcNiZDmMCAOFOoQEdy/RX4ObAk5svPZBdFHK/J9hTL9cTRv1iPXWL1jT/riI31AR/xMK/rUOR3b/7jALVPmIoLRS1npFJVOeOWCvT07Jknz8ivjQJsGsC5rqSGi1sVXpRGVuw==,iv:/PinG2A9lH4xFL+dsFHuEECp9igQoJjyUYcEGMYfjls=,tag:llGxQovtDnMi3mSL/SR4Ig==,type:str]
    known_hosts: ENC[AES256_GCM,data:oWIlFleTw627lPXIshGvlltVCitjJZxvo1N2/S+CQp3zhP+V0pHpvQTJyQrXHmO5YlZVy2/UnbHuCYD/lhCcSzx7KWZBmL2SuDNWunTP07V6RQm4tfYQfJxMBfAmW3FBlZ2qr27RZTcyNIslJ3EtRMEGvTYuiQgutPDLy2UGdHKvKnTu7FRYUu/pX55rU+GfZLQ1fkqYHhjfN6tfPxro2o/jmLNjCoslptaH,iv:JqOgew6h/gj0RyxyBOc+Vcje2NaCy/h6aC5ZNMoK7dY=,tag:u9xjthktnlZYPGVdGsp+HQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaaTVHTktwZ0s5eWlYNG9L
            SmpVNkMxSVBwYW5rUDJQbGR6djZ2ZFZxejJVCnl3MzJ5OHJWeDdkTTBrMGxURktp
            U2JSWnBZV0FnVE5wTGhFT2J0VHR6aDQKLS0tIEwyRkY0N0ZDUjV5bzBRc1pZRlhT
            aG5OK2tGMUNEMzgvZHluYk51TGFXZkUKMobUODsS6Jpb+CfUuQD+4xw/EOI+WEyo
            piwPrFcizjuSlUsIIuHojfAYqLUul6PnA3I/GkZVYCcrYDiln7B1bQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-19T10:06:26Z"
    mac: ENC[AES256_GCM,data:1yzwFqduwXGCcr7vvXBxIwGo5QqMuPM9ZIBthgIKnfFgflbCaXYjJUyiFIEbNhUZ5sNerHEdr9Y4A6Mh4WacAMG/NENt/zpf/sBrb5DX/FE08vFH7qU/dIzhzT7lbihSFtcLI/ZUk4Qi2IgNmlg/0diti9e/DnhM834xj9kXLEA=,iv:s9jJkKUbPveyl0001wx4P6UflBzOO3DaH2vD2xvBwyY=,tag:wftiRa8IAj763VPuZchkZw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
