apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Ub5XCwW5vu9T1E55w5KpRuNWzQgFu3Cj4p6r7Be6RTRQOX7ieBW1iF7Ll0GdjDEh7ixf+VZNskS9uIG+GelIbvGzuQoPFmvihc+Pyyc4kb5kesqoiQUz+tC3X7lCjudyD+dm3KlUxu5KSJo/RvmgPf26mjPA/gxP9YM0Gg4lL2TvPjJ08ntxrw575LqvArNoZVriurbb2TGLwYkrdZC0nv9xVHcejjm11OtMEUCQsKCC1v4bv1DZECV6Ux2yXPP/+5qIIHsN8j7n9Nk/Bj/cAntDLJMLnvB0GZiK6zNFYID60FA7Ko9gDiEdF3YUlEhdINjDZfRmBdBf29LyC2q1dIzkHJLZdSN+6sOWU+Sf0X6U3m4ofrt2ImW4+Ab9jXl4,iv:McHmZg4v1IRb1DvwG2/BdEXeAAeFXIlLWz8CtZ+t+ac=,tag:dNSuaseeBvsB5oz0l9H2hQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:vA6wuJxMiOgMCwb5bK/eqkUisrrNyZINWXqytTZ5qDMWZ0/eB94m9FBIHipncrXrfoe1DYGc56UBwyD58IHbhbhdOa0GNDe84fO63bbbCeLzdryWQCZYKsOOs9+jZpZ+sJ3LUr3ASTfCgRY+8TuiJkEJOk7oZXVcP7YZOlYKx3IzEPqz8PRqvE3yPpoCAOWIv2cFN49Yx+U87gV6SxK+qLYRvpIES1VPiR1Uo1XtcP+vHz0k9JE0ZKwmN1gzmnqi2Q+r0lEi0+mEMvqyMw==,iv:xNLFBK9ScVnYIwxh6YGm0907ZNeqkePTsvPl9DK54ww=,tag:SrCcbBLz6vA6p5vscWbRtg==,type:str]
    known_hosts: ENC[AES256_GCM,data:lVMxeGnNSu9bLxFv5wtkzB9HLQ6YGSv27Af9qIUf5GrfBcr/YhrNIS1mFcFmJHCbhtTcp0W+h6mopGeXLZcylt+IRrKNysNctN8NWyg+xgZxVme0OaaGK413jTfS2+ReDuzPWQ2F+j3n6WTawGU2Z0G/UoQ3aXb4u920U9+evtMWdopmpN6r/fgs6seTWRDsWivm35LgheXr8YDeP7i0ahADmnyFDhxNt8HT,iv:SnuzH11ClY3uCCiMnP5645RowZjUJdjyEqWwkjFfFVU=,tag:CRDxjIJJLxcQUsU4do+Wug==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0QWJaVzY5N21wRmpHQ1U1
            RVNvWVNBQ3E2WERNZjdGNjA1UzBNRlIrcVZZClREQUtRRklCbWMvODhEcklWdTNG
            RzVHM3kxODhnRVF1Qjg3UkJ4QnBZaGsKLS0tIGZGemNoRU91V2pubU1MeXRMM2oz
            Rm1kTG5maUhuQkh6R2NDa1ZQYytITmsK3Mq3YVUUVSeYp5rawVeSZttwXkLmLhcJ
            vbewZpDO9lBsoe6y7ZtPEnh/dtP2iRH+eKEXXYsjnsWq++mSDsyAZg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-10T16:49:10Z"
    mac: ENC[AES256_GCM,data:SerXkwLPtWHJ1zcfeKVWJadySu57pzhQnoWm9yHiv1aW613nqNj4PmsPHgzom39pcrlbfjcVBQ7op3vimMBIUvhNbVmIJXI2yrYL4dj9ygdOCVgXvklWqGcASKsPnSoGC6msmJ6Yx9JjFh+MvuYzLubWkiRzPB3yKCKjr1Qy7Ew=,iv:MlJLawQHWKtM2diOq7TNCDLPTEDQuO6Yzsd8KMDP8To=,tag:7xyXtCO4AbX51hECRP/xZQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
