apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    test: ENC[AES256_GCM,data:Kw/rvto=,iv:WHAR7no+d18YeQLPVY/HP8Cl38SCmOep7UuCvJTvPNw=,tag:pNkbuenV+o3neLaZZV7nEA==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDNGcvQ0NVVlAyRUR3WjdW
            RXJUS2dxaGpyc3BvbyszbG5BRHExMTNGZlNvCk9DQThJaWtZTExCSnl3M0xXa0ZD
            bWVUTzk5TEMzeGIzdkxqUVNrMVY5V2MKLS0tIGJTbHhWL2ErMm1CeW1FaHRQN2wx
            cE9TNFhEVUNob1pueHVvZ2ZRRm1JSGsKOTEgXIiceGUA/C/S/YEypYiEln6HuevO
            i4wNei1smXsoTRABqfa33Sq9piIh90h77YO+/MgRlog0VjcbXOY0wg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-31T10:27:34Z"
    mac: ENC[AES256_GCM,data:dURhmeHoJX0pbbYG8dsVfp/P9IKftoH5CFp3HFUl/KbQXGYoNli3fQHDedQCEzNcsDNrVnOh/hjTm8AC2vWFihwbsL1JMuVmAKi+UvSighldllxjoLPvOVD/ItF/kb0oWJ3yyn4XLlCPS5hQuP8Ye4PVwxKnwQeTbW2VrR+zF04=,iv:cC48ZmebvLtyrqBdctOoh+giFwy/Mlqx3uWuUG7Xx58=,tag:CSFUHmjD4KhDD60rzv204A==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
