apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    test: ENC[AES256_GCM,data:K/340ok=,iv:bbiQl453RdUCOpX2sFSIaklzCTUtLdmwU+TwvoZdfiQ=,tag:fYDmmYu50UNd0kZ/aSMoMA==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoVU5JZksxdzZ6aWRxc1V3
            cnFtTm55VFBndU9uYkJqRGRhb3VxWk1BbFU0CkJFYWlBd3dhNHBTRmxSajlRektu
            MGlubW5jcXdURklRbHF0NjQyOHNMWWcKLS0tIEhYMEdqaEtTTmxCODZvK3Y5S2ZC
            WDBXWGNad3RwRFR0TThoZmdmcmZaSzgKJ5zBELcSPh5W6nb/wPPkIVQmAWw2gCWg
            7ow2ISQo8SuN9q5HQlYqpMWVHTFwPHTOcSF4aLK0NQX7zGjqlfgYzw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-31T10:35:12Z"
    mac: ENC[AES256_GCM,data:2y5XWGn1yNxz3eHeV+RNJbF8ryzulX4Qa8YlIickU+XXZe1gmokoILeGHu7oxk28UTN+R7gRZWdNSx8S6M6BB5Z59oe12xTeZBWaDXxnGhu72PexeR9C+yQSp6QPaSnjPnlxZo2b1DzrIq7xLqMe+AOuTVsTu/6E1GZq09HfGLI=,iv:yCZDLt74hJmKUc3XqY0TxdneLxe+ncO/xb8xMqPMVh0=,tag:G4cqWZI+vAFwyycVUbCqzw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
