apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: teamspeak3
  namespace: teamspeak3
spec:
  interval: 5m
  chart:
    spec:
      chart: teamspeak3
      version: 13.0.5
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    global:
      stopAll: false
    credentials:
      minio:
        type: s3
        url: "https://${S3_URL_MINIO}"
        bucket: "${S3_BUCKET}-teamspeak3"
        accessKey: "${S3_ACCESS_KEY}"
        secretKey: "${S3_SECRET_KEY}"
        encrKey: "${S3_ENCRYPTION_KEY}"
    service:
      main:
        loadBalancerIP: ${TEAMSPEAK3_IP}
        type: LoadBalancer
        externalTrafficPolicy: Local
        integrations:
          metallb:
            enabled: true
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                TS3SERVER_DB_CLIENTKEEPDAYS: 90
                TS3SERVER_QUERY_PROTOCOLS: raw
    persistence:
      config:
        volsync:
          - name: config
            type: restic
            credentials: minio
            dest:
              enabled: true
            src:
              enabled: true
              trigger:
                schedule: 30 1 * * *
      data:
        volsync:
          - name: data
            type: restic
            credentials: minio
            dest:
              enabled: true
            src:
              enabled: true
              trigger:
                schedule: 40 1 * * *
