apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: chromium
  namespace: chromium
spec:
  interval: 5m
  chart:
      spec:
        chart: chromium
        version: 8.0.0
        sourceRef:
          kind: HelmRepository
          name: truecharts
          namespace: flux-system
        interval: 5m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    global:
      stopAll: false
    credentials:
      minio:
        type: s3
        url: "https://${S3_URL_MINIO}"
        bucket: "${S3_BUCKET}-chromium"
        accessKey: "${S3_ACCESS_KEY}"
        secretKey: "${S3_SECRET_KEY}"
        encrKey: "${S3_ENCRYPTION_KEY}"
    ingress:
      main:
        enabled: true
        ingressClassName: external
        integrations:
          nginx:
            enabled: true
            auth:
              type: "authelia"
              internalHost: "authelia.authelia.svc.cluster.local:9091"
              externalHost: "auth.${DOMAIN_1}"
          certManager:
            enabled: true
            certificateIssuer: domain-1-le-prod
        hosts:
          - host: chrome.${DOMAIN_1}
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                CUSTOM_RES_H: "768"
                CUSTOM_RES_W: "1280"
    persistence:
      datadir:
        volsync:
        - name: datadir
          type: restic
          credentials: minio
          dest:
            enabled: true
          src:
            enabled: true
            trigger:
              schedule: 10 0 * * *
