apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:Xr9c3XBPh1FCAffmrtCdX5GMlxcgCtjwdd+aodNvg0Q=,iv:IcPK5GU0tkHg3BYfNu1+80jE72DcLV97izLgjW0c9jY=,tag:wreb7C9WPQqP3B9P4UfZgQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByYllQekRjWkt0eWFKMEtV
            RzQzZkFGZXBxWVNvOUp4dVZ4ZVBpYVpSbG4wCkhiaDZ3R293alBwVnZGU1JqcVdW
            Zlh4Nzg4dkFQdWI1TjloMlhQNk5DaFUKLS0tIFhQNk5FdXowVldlckduS3Rpb1VQ
            YWJxRVVNTEJURDVyWElUYkg2c1BRancKIi8epyQtrwrKDa7YT2qx93XLmuOrEbUN
            9IfB10aTI0zgzcHRRC7yIwSVBsDw3aaGL4QGV+0p6xSFONds0PgIdg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-04T13:06:20Z"
    mac: ENC[AES256_GCM,data:QpXuvt6K47pKAaSG3SvnS98Oz6z/gOKTn+UcK4Ud8EV2skDUYghXtyahTqCHYzLjWAo/LTJ1JbRMdTq5gl6UVDXgox5IrIFYndbnYs4uKLn2fUkl/TD3GuxXwSie9d9ZcpZpIFAqFkgJCf7LHg7MW/YOWspccVf0xZ2MkydyWSY=,iv:D9xl47g3Kn/qe9niwzbg6rDb5DmGfD8kwqO+pb/KRtw=,tag:S/ZX/FVDR7NI3hLBMRAj5g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
