apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:kygF36YxoT8NSPqXQktLEdtff6fv7VsZQWnY+LoosbY=,iv:HJbWXkivYfHb0UWrDRXVUWoGYmuCg6zQiTjC1MN039Y=,tag:Jeri9gbSZ3Gs9yfvbVZQ6Q==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUb28vc2QxT08reVRiaXlo
            ejE5Z2wvYzlsTGdQZ2ZDSkdNUDJ0cmlGRHdBCmQ1UktNczJvaTREOGw5V2xtQXh4
            WVV6NndNUW52WDBpMkpJcWFSQ083TzQKLS0tIG5RczRTeXBPT0NPSTIvSnlsSXhh
            QWVVYlNUT3dwY0R4R2cxbGwzNFZvTEUKob+lxQJo6kce6Paq/bGC2RVMwC9sSmyX
            yQ9aOZe3aV2h3Cig8MKdDWrBolJyy8BQUACdt89Gb/FfIst+BKai6g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-28T11:58:21Z"
    mac: ENC[AES256_GCM,data:IeCNAjDGpDbmRw0wMlzphtc2V4HvUJ97TtjUQ5awplQ05goEUL4r9kEAU669GaRyg4XiOtz17QHOz6MMAZTlR9MtNWi+zxfGJJLWYNtOawAGgv4XpQpsUBMvSLLWWfDfDCCmyiBgRWhWFLQwPgAKUOBf8PhFPasBYlMYUyYppOw=,iv:bq4Tm2T54/QLDATbgUMUNxtjkGGRxn1NwHSrsVY6QAM=,tag:+UYLTIx5c1P36GCNCNtq0w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
