apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:IyE932tWhB0EUX/iI2JetaHwJqSmPmBPoEEaDSR2nO8=,iv:sMGmGRTjE4mcyqtwUyA8X9TgvJi+PtYcgBCoUzzZoAU=,tag:YCm2E5OCdXuY6VR/Gtrv5Q==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsSlpMQnV5SzhhSlNOWEZ0
            T2ovNW8yMCtEWlJETERMZkhIWXB0R2RicFJnClRmbk9taStNR250a0lHRUpNQWU4
            WmJBUjJpT0VSWVBmZzZVa0w4TlY1N1EKLS0tICtuWDJjN0krSzhYb1Q5YXg4Slp4
            dkhtSTRxdWJ4NGF0RldjSjVURURmVnMKryTSDrE+eLbMv14iq374OqgONX8Tct+y
            Uc6YWrz/quWJMNzdAqT9tudrRMChnCfUm5Tf0UXwBMeuVRPNsb22rA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-28T10:18:49Z"
    mac: ENC[AES256_GCM,data:rhRfw3nJlN0f3xqq1lmxAuGrcIconbB1CNWLx7k/S9vPeUrvRsj3CsFFHqzO0lf+z6oN+NnwvYpvF0JX89GuKmbyrCLklQnsevsedHJo6rMIn2Ki59ScVpPli2YqFsvzAc413fSZQgJR8Kp/DT6341+4sqObYeTRct/8DwU2XME=,iv:KQWuoDe9vxkt38GyLWlDT35bWXvv62l0cp45aYMSLOg=,tag:NLlohc09+JaLabQfXilsCA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
