apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:Fp3s9GlsbvBv9TTqWWJ2aXrAucGjihL56j8Vus7F6Ww=,iv:u2GeeZwdjjCkpdWvqb4gvK8PYh9lFjssmhAh/0AJdBA=,tag:a7z4CzVspVqupwHl+6s3rA==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6cGxoNlhDSFg1c2dHSW1D
            WitQV0g3d3R4RXBJblhlZWNLYWdxWitraGpnClNSQVlYTURnV3g5OFoxK3NxTldk
            bDJGQ0lyOG9xRWhmZm5jMXBna3BUd0EKLS0tIHBMNlloS0FERllOcit5OXRqTFZO
            RVV3dnhvSXFaL00xSlZnZm5SUGVMajgKsw3nFjWd8URDjb1atPlrrTQovO5QKP6o
            ZtFji2WcakIGzGBL6nJ+egc3JjMJdUOjoItKJg6GkRDUzP93qOP9bQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-18T22:36:29Z"
    mac: ENC[AES256_GCM,data:XIOWyqQBXuQtCEJ+yX/uzqhkmzphoPhV2nm6uTsMBK4f+gi63DGLdBbzX+24yOAQ2XdENyC8lI0OziLfxrgRsKO1uPgH76DbN3W/IPvcldTypJnDI3Uk4/uVr+RhtutNk0D48cpiMJWqloQMnv5+RY5q7J5HMa+lcRRx6W3E5Rc=,iv:iEGwwUc9W9T4VetLNqnQI2C2TL56L7klafajRqXHhHg=,tag:zn/0Na7+ZwjQSAubcihaWQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
