apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:Se2H0DgvD3q2ZDcJ4V4C/m+7eRRT80YLk4sPtn/fnmY=,iv:S/s6yOgNWxwA+9DPLAadWZUek8LHs37rk2XIciS2Q5g=,tag:I/I0Vfx384HR/IcReMY9FA==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyOTV1R0FYZlMxNllIeDhE
            U0hQNVJXeStvVFJUQUdtUjFSRVlyZkpoTDI0CnRVUGNuWXRmR252azcyc3RDRXNE
            OWlOMFJyMTc4azJpSFAvUW1jc2I0VGsKLS0tIFRqTE5ZT2NURVcvWGpuUC9WSlNY
            bzIxcndkY3FKeTV3TGE0UG1IVDFablkKXFErfiSQbNvI5AmgDhDdB4cQqNh8gvjD
            sJW9zwIRcPG5RqNwmhb0eKnO4HtzCNIVRmCgJkw2uk/r6oqT1IDT4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-19T10:42:12Z"
    mac: ENC[AES256_GCM,data:w/Vre6ayaEB+Z92sKtzfXpAeA/Z8KixmadYZEKE5z+JyyD709bghMqQfwsUNKSA/jvICctXRX5hCjftUysFKFoLft+kthg21MAROc701+W7nw2W+cYNv6PAeG1i5kaT7bCjE3SSMmWDMZfYc1xNSMTbb2LC4OcClTIpQOLRh3g4=,iv:ozRCG5A1QjAwTqRPT+2G4bGzaTuH9nD/V//NkM3OTQA=,tag:HqkXflflurN6lXA3e+3KIQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
