apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:0daqHQ5P5U15ZhS14fjq3xh2xSlj5eSLERXYSmLSSVk=,iv:e93VUhcShWIikcfKOKwfmBNmuGez37YYFVUFZ8jJG7Y=,tag:3skZtiJX0cLfRrfdjogFWQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBMVlVZlF1S05zazNLVnpp
            aW90VTNyMUc3bzJVTmNnYlUvdmdlbjJ0eFFNCkNSTG1kTTRja0RQV3A3Z3F6aThO
            cVVMMDRldFY5Y01PeXdCdkhDamNHeEEKLS0tIGVKVmpBRVh0K08vUm1hY2srQzJP
            dUVMd0l3Vzl5VUFKYTZDdzZIZ0ExcmMKmIC24cJuGlRdo25Mqscj9zST4kUeYeka
            AjdlfxVBMvCvSrTS0f5wSUqaMZZ1lygGIqNhP84SD3b+cK7fCVOS4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-28T08:51:56Z"
    mac: ENC[AES256_GCM,data:7VDM7hkAq54WUtoUJpX9iZVYnvj3N1q5pFzb+nx+4BXA5VCBWdrNp8VoxazLWnbujRrOs9eg3HGeteo0fVq3K1GE1LqBHBWeKp2Qma8VUGPN/OB5+/uTrTqLYBxB9LuCZ8ia2u+swgOdwVNFJu4Qd4ydAFwM85WukJsFqqlN1rM=,iv:G/HsRi8bT9TtfyPsAPtECLumQDCpxvPzyrpaXZTLT9Y=,tag:ojGRw7lmgttqYClL+1e6fA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
