apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:AJa73dlV8llhIxLcyn28n7Y1vbKRjwuBiPVN774yqtU=,iv:YDoCMycAemcWBO6zhd2yKGs42KqFAzXP4w4gFdHwVSA=,tag:4aX//VyVheK1vtoWY2TvDQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSbXF0QUIzVEN1SklwTnhV
            QWYxNEYyTUxjSXlzN055Ykxrd0Z2Q0R1WFNrCmFPVUhuOTlOQnVjOFk1aktEanpF
            eGZ5bFNiendPTm5tYnI1cXVzUzRiVXcKLS0tIGkzUHMxUno0Qy9ueWJkNnE2RUw0
            a0ZrMU15dWhycjh6eno0UmxDZUp6Y1UKx3NSC9I71GXNRRs25rIkj8QwxcwF3hWQ
            BODl+k2wqWyxjG8YkDJnwdnbmppoGjomqJboUVUHv8hiUG76tSyqCQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-16T22:52:03Z"
    mac: ENC[AES256_GCM,data:AfhtjvH/RgiIk0iQU+NlQ9yWt3D/ojDjfSO9g3UtJEOf2s75/EEZbqXq8Ps1s+gwl/d/MxgjU+NdKtZlTvlP9YHWSl6sdT3eeW10IFrf2BCvC+OuxBmlMp3SbE39QohuDOSyKvidVGCVJIE/JKY96Y+ViqM6w46VSOsAKYAdz3k=,iv:Tu6VJyDTh91jBHTkEL5OsSijvJrwu3eqGPyTVHZXqbA=,tag:vC5j1It0RagmdhHz+/hKgQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
