apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:vdnk32Q/ErbdWJHfEzsR1i15bLLXW1NZpz2Ulcy6JuA=,iv:SD8IPo3Cr1h5XWejnKT9O/md0YhP6GaLUKnBsXhtrEY=,tag:5TuQ7AYNysrLKUVySwtZyg==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3L2ZMUlptM1ovbmcrdEtV
            UUVUbkpYaGZad1g1YW0waU56WUhJa0pRWEY4CitpSWJMb1MvcTRuUmVXcGYzbGxI
            a052d2lRMjJyWHhrUHA0NDlZb1hEdkkKLS0tIDBxR2VpMFluaFpYQ2QvYlFXK1RR
            bGZMMGQ5djdIcWM4K3AybHlRMkx2dGsK4qmEmSTqJi3FEh01xoDEQC2KHGa5EIi4
            y5GlXqyXGBX4D/TT3loLGE0wmK9wQZ7FbUX5mzHmXvKYa6zsD82DMQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-04T15:57:26Z"
    mac: ENC[AES256_GCM,data:t5UCHfqqWLth7lcTZ8KzoXZf9mhe2EQyulis/hg+l4hEaRBWjnRcdiFYkZi5WnhsVW8U8wF9lyQLnLn1ZwagEIKUhIiiJWqhT1MPdyRSWNKIe+SMFf5+WAQq09E788Qv+9OPGxqf2e2pn9qUGzdUWiN1DLY0nOWdPpmPQqwcUf0=,iv:C0ordcgdgOiQ1JhIuSTtG+0DNBfhFyY4n9bi0vUokQU=,tag:XPoNDPCVcUQsWGndI3F9Zg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
