apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:LwMy0a6b9n6yb1nhK2sf8NXfYHSieu3LbJtMl9IbObk=,iv:6ch6hIwxe55fJsJmE3Z1VkCJ/ohVDL9BDKSx3RV1hDA=,tag:bDNUkZo7QpGw3gyo9v2hmQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByVDRELzlQZzRtTjdyZ0FG
            WEVod3orcGowWUQvRlhxTGZDeElVc0I0SDNNCmZwTUUyaDJzK2VpUjA0Wm1FdTls
            NDh2U2lnRGF2QUlYSWpLNGVvZVd2Z00KLS0tIDNNMTQxZVZhMmMxVHBzRVlha1kr
            VnFIQUUwMU15aWcraEE5UnZBZ3ZES1UK3DbzgvUd1DrjVM+OuNGOZvzaeY3PBynA
            HQc4cOWy10T5CXidKggDKuxS78WmkbQACC7ZRriJpdYRz6B+96qqnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-19T10:48:56Z"
    mac: ENC[AES256_GCM,data:wsR1pbNnbWSKOlbpukt/kC4dwjzROBwhv9z26iAj/0jIqBiykywbhm5uJeLcmb/VB7vo7O3eyuGEY6xv2D7VfTPOIF7gXNPjfgWzvuNhjcC6AkhhMNAMrH3+LKsd/42iqMwird97d5Hk9Sg+rxu58rQbQVeUXgGyWhUwGhl3sK0=,iv:QD5BZQ1fzsOcuu4vs53O5p34UZN5CWEmwuqenrJou9I=,tag:fOK7xNHRhgBm9TU0wJnfOA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
