apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:jCD6qu6GRRqQC5CpZq7ONW2SqffJbIRvcypQk6y85Oo=,iv:eDTdkqjvFYNmiAN7XUqCWxh7Iu/IIlTbSBgPSyWQCiw=,tag:MsiIT4DJ45CONAsgrwUVVw==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1MzUyU25LbzViVTc5cEJC
            T2JqenFueEZxVDRta2tXczBNbWdod1VDSGlNCmp3dDhyc3NJMktGRS9BMFVDMkcy
            QjVQVTZ4dVZnY3RDeGs4ZEFCdDV6eFEKLS0tIGtrU3Z6L2dhQjVhSjg5dS9KVlJl
            UzBIZnBRQkhiMUFLakRpVzlOM0IxUUkKwl6ugtB60RuymuCX6YtFl5PTTWb5sauB
            s6Q3zXdiL8WVZzxX4mwMfOFAo8QUoQ31OPQ9+owY/vsi2fSi2dHCGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-01T10:23:38Z"
    mac: ENC[AES256_GCM,data:2oWP2cl4JnAAzlAhaEduak0Ca8TLYDSIyiufX0oo71377Z7fowLnSOuZJHuRKUIk1ziSRsFZdvJ4sXcRV1/yS293d7WSkwQnrTm/i/Gke5bihXhu1KC6kaiW8iNIiXYRU4WD5LYMKnwF1GjliWbfeWpIuukd9Sb1zTXUVzk4cyw=,iv:sEib5r1bAjhBgs7rPuAZiB/z/vMMtou/B2yv1kLlGAQ=,tag:iHJBn5UGnm6jn7XfWZrn2Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
