apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:SQi3FGmXNwxyFgjBKHirDq30GFmFl534TVsj4cntYWU=,iv:Nhvh+dYmTQ08kd+5IjTOSXZwrWaHZ7lMwlnEm/dUk4A=,tag:3YVizynFmRZKtRtf/uXDbg==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwcTk1NU1RM0VqYXd1UFR2
            ZmZtaTNBWGZ4T2t3WmczRlJFWlhrR0VRZDB3Ckl6bm1HMDNkMFU4OHk0VWpva2Ra
            TzFBSEk4OERsLzB0MDdsZnB1d2daQXMKLS0tIHlERDJMbTRVelRscGVla1orMy9K
            djZXRDlSS2Z1bzUwZld6TGZ6NGxZNzgKqPWaDZKwbagHENvZvnwD7LhHrCvIp9UX
            wb2U5NIU+zE9Y8/9dseU7Jl2Ih3XMzE2lwWZEJKvLECWfAuV2qMCog==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-04T13:09:01Z"
    mac: ENC[AES256_GCM,data:737QkkybqTp5LZyjLrKsKAztmzLdeMH/8Kjz/VeMnSpbOwC8rDajQ2E92TT9QXmDcWFgJEia4cMC2xntyW2E0NCTyq/shuqyU0CuTjhzAZJ9/Z5Vg0RkYqNscLVt9qvicI2JmS2CVCdG9wMkG+hv/TwyckiE4IfTlFSzpMWICLc=,iv:Y69PSDBuHQZM0qQbt/XAsdE6nmWRvcBqYrVXKQvE5Q8=,tag:c2jkYZL3d3lh0ZmNq/vupA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
