apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:bHISOWqvAHMi1m+2hLIzJIXSyD5ru68vxAuEkqhVZLQ=,iv:0G7bQImJmYLQl26tDXo6mldAjUeiVWvn0LO3SlLSvWY=,tag:hCVapKo203vw7tNji6rfbA==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1d1MzZWkrMnlzeERpZW5y
            YTV6RitscGRqNXJ4aXFCNXh0UWF5ampmakRFCi9pdlRMblZnVjVKc0ZsV25WcmhC
            a3lza3QvSFBqTU8ySmZmbUZwNG52RUUKLS0tIFBYaVYweHZGUW10SWF3MHVBaXdL
            MTY5dmswOVE0dStqNng3SURZZDY2U1EKSIvxYtuvn25WzxPy+vddYaylUDXnGPec
            3l8TwT6gz+lgjcdqLrDCq3VjyPzP+1Mej4Z/kArTbknUcQLoWUdUAw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-15T21:51:13Z"
    mac: ENC[AES256_GCM,data:7ENlktxs9kzq0inEYaJN09tTNmZC7d3Byrw8N4CueJ31rfxNDQYReOyX04+MYOekSR017nATVFZ9OPQtMFKD59cIGCY/PkwXPKbOdyDnNYBicSCt0XJ4OfwbIMC0SDOXwH5jVjeC1zO47tdI5lSYUfThBWGBzw+K/HgtK20AnuA=,iv:P5+tW2cDdDz3djqqcYa1EvEyneit5RW6jYgzU2sgMeA=,tag:sndYaFEM/hEDU6s8sOevQA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
