apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:lt8jyq1A3QSEth0K0xZ9q77uTm6pkGyUoYjYbQ5rm9E=,iv:an5wrGIc61DMnYdoHoe+DIMEeJ2XmfZ10a6ChM1mx4o=,tag:6rnxHM3pZLyFwsUOA2izTg==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtQkRWeS9MTHlVT1owKzcx
            d1JUQmRMcVo3STJPajN5ZnFFcmcxYldUTGt3Ckk2dTdTbEM4cTlFTi91RGdVWGpC
            TkhxbzhORVFQZllzV2k3NXYzMU9TUUEKLS0tIHhLWUZYN1k5UjIxbWJEVHNqWkpC
            bmIxazJlUi9BdTR2WnY2YXh5Y0M1WXMKWRYFzQpeZ4GN9WHMq4tATPSsRWS395ti
            NCx9LCRfCml+633SAZ+8XBZ827tpJRhNNX6KZQqEQZdCND6vczrPLg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-31T10:35:12Z"
    mac: ENC[AES256_GCM,data:3W5cGJl55t09+nOv6gLjD9FocPuDO5XuwLrPUtkIyxZfoFLzifRhV1ChD8A9+JeUqNE/DQAaoN2T+/8xgM4o84MJfJ7hy/ZANGCLu+Q8bJm0OkNmx7amPoZ9wcHDFIymTVdqb7eaThXinBOTyDmqM6tGzD5L2vKfqF+h0FkQcSg=,iv:aPQrr2jF4Ac1mE0o4RoIqFTG7r/F67lSZEy7r14SV+E=,tag:V7FE1PY/4+DMeu0DE04K0A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
