apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:VtxF4aKQzshx2gnyyDf883vujmM3cMpmNjEdVAvyhxY=,iv:0FIfX/J48f8WiaKLAgk7N9ZtxSef0maJO0Jf9uEUBHM=,tag:J3IySAV4Z6zDGDIdiCHWAw==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0QUtaYnRaYzQ4bkI1Z3k1
            eStZMlNWMjlvbFU3ZVlBcVhtNk45ZkZNaFdzCkhXRjJEdHVnS0gxcnlzdENkWlhq
            T2ZNaDR1aHFXb2QySTRhY1kvZ2xUUDAKLS0tIDZwcXJPUWpRMjJpMTF4c1A1a2JZ
            dWFkOEQ5R25jWjd4cUdmMUhQTlZNeXcKDuAOvXS5b/uj3WKQ5KW55zSv5LTqKGsP
            8wa0reams3D4FCeC0p75lH6S0h17jx5xhZmKK11X+bNaEIQfPT2kbg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-31T10:31:13Z"
    mac: ENC[AES256_GCM,data:b7pNt8/ACFokA93N0KGVNdQPTeNn9ulPzIk4/VOb9oDfI7Yg1rtC7kHVGy6MYBMKtuq36muh7tpzxNNqJ+7jAl3Nrrh7qGregmPXvm1lcYNlPmRZ7BiJlUAP61nmMCPo3PNjbGGqUulVrXCmZ4yJhjAM8OytHN5QWB00u6pmIO4=,iv:8D9ApWHTr6+R7ebNhR/yT3zzQ0R8d6XrrHD8rrq8nYU=,tag:8LT47Rvme6f5CLnnwZr+Dw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
