apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:3xrDIao/ncYlfSNt/R8q7Woh0H3++JH00N94P8V0nu8=,iv:uj+xoaplCLMONI25Rn/kJMXhxmsQ2TRNTdGlihZCbsw=,tag:gNTA4VDFUB/PSXCgk2uv/Q==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzTTk2N01YNGM0UTVkakE5
            NTYzK2RVNmdNSlQrMjAxY095eUw4bjc2U2g4CnFxK1lqeDhVRS9Zd2w0YzU1Qm9o
            N3g5YkFPbkRaWm90bG5nMFhjSFRqS00KLS0tIHgvbUs0VER0SHVUSWZtWjAzTVFh
            UWJMQ3hCQlJFMVFrRlA1NHMwVHFPZEUKjY4d0B6Od29EuPNcAW6jXRxLxcsAn+QM
            EN0OSrUiUfq2MydcSjnbNd+A2Hd+FSNKM6JpzqkpJn4DJEmlm6PJmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-03T22:50:00Z"
    mac: ENC[AES256_GCM,data:vvTU8YMp9DvfjzJb+G7cZKUuy5hzxD6qLXV3GR+W1naJFKpjp+YDSI05mDJYNb35hGVCb/4sHk3KKGX6/2UfjNqQ1IrVJHEQS8VVMe4ufyT71fQx+nx5Wk9nSqOnNllNVfjTP/BaH+buXs8YI1zZk03oaYuyGLCOYNuBoraQi0c=,iv:xprnzJOOeuwhVxPSUWr1lQhK7NwEj1sOZbc6nCHBKL4=,tag:aeVuR9rVev4YHr0qdA6DiA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
