apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:cL7S0vJrgbogQWnCnR4YHqmkRXVH2KxIC2vWDBligfQ=,iv:msIRM2oesGFbfJMvKoV4z305InnYauAXNH9tDnKq6+k=,tag:1W9AQydlY4R12zshrbMxyQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2MTluYUQzdTlOWlg4YVB0
            Z0dxdFlwdnRTSDUvWFFza0FxTEsxNkpZL1NNCnU4N1kyTHlsTGFtcEYrVlluMWtz
            blpYdlBFcEJ3Qzl5QW1JeEo2TTA3MTgKLS0tIEpsRmpFUjNUbHRZWEpOemNGeG5Q
            OHNTU0pTMHI2T3piRDdUUE5kcWhhQW8KB/FBOnW2GlIB5loa8wCrDK+/MKXjWWqp
            72LbdSl085CIifz8zVJp/B/LUp0s59g6oqrs2+xJaFPJ7YMcDr4HBw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-13T10:46:08Z"
    mac: ENC[AES256_GCM,data:rI67PRgiyQKMW810Id1ar3ZLbtfOBG0zB9LVwwQnsEfOtRaLdQOzT9qYReZEFR45qUwzMxedZ6RXbBUAO/RQXZwAQJELC/F0ogZJxfJ6NjQ61u8ECW/StAoZq1OZcAztsjeXaIQAL8RjsczoudDQKYP5rciozA/6Xta+zcgdb2Q=,iv:XIwGDWcA+E5rRwSUQaxDOZqR08VacprJsV3dMRsrrnk=,tag:oMZy1IuoLoyiOhjX96SgGw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
