apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:9Kia23qAwx1at32AV6sVuUf4W0JwV9G96aF75+ccaSY=,iv:3zoR5j0plQkcxuWAZIvkmLBn5YHyOTFsRsTt2kTj2Wk=,tag:5G6OrjH4veUfP6D0iJkxHg==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBINjdGeWFkTG1BNmQ1VDdP
            THRrZ0kwQitveHRVM2hnYnBMRGh6WmtWTFF3CmtoK20rdWhONkJqOHhkYVphTmNZ
            U1hMdG5TRlRieTdlWmoyZTVKYWc1QjgKLS0tIFZDdFpoL3BFU3JHcVZRa0pLbVNY
            VDJKZUZ6czIzUWplaWZzWnFuem9jVTgK1qF6WVFXe1jEmkc3UK7SG6GM0TudJmsK
            H7NHCs6qIWoAhcp9e3/Rv9BXPnNMdTxXR2gbygLfGyS5oBrd8cJkfA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-31T10:23:16Z"
    mac: ENC[AES256_GCM,data:jyvaTaTGFoqpnpddWV6rPITDWc/3O+RLm5/pkIf3ggRNrt/Yyt7NL/KsMUnjoKkzrRRoZSfMqbguiilEjaqv8MBEpgdJls3v1v30SR8KwaBkmfbTspDZ0m/ua0GRUZfS1XT60UpbBOT+JUflPnOcKWJ74k5Z7LfUy+oZZfnPbcM=,iv:NYaVFq1g2v4wT7MbCw7cVxhrbcXREtjPb63EZsz7lls=,tag:hICvVL4SPc+03Zuho2w+RQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
