apiVersion: v1
kind: ConfigMap
metadata:
    name: renovate-config
    namespace: renovate
data:
    config.json: ENC[AES256_GCM,data:WZLKBpJn49NrvJVzylcOcZmOQonGji1QnWWNrcUNAYrGdDu09eicd7a43NSbAaVGih62hDY8AAbQfJ5Lvpq0IJWSqleDAbntpZZ2vpASMbA2+IHM+t3CV+prxRQqt854Lxk=,iv:EDcFAO0I9PD44qMPiLhEt0V4FDM0ZeLp7aH8DHPyKTE=,tag:5NBR7hxUYpvxcfjNTGFRqQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZSXFQUmpic095Z1BsZ0VB
            bTNJVXpnM0oySTN2MkpsOGk5MGNWeDlpa1JrCk9TK0pYczdaRE1JOUVkR3BFaExY
            V1JsOWxwWjg2TU5kRlZKK3QxMUZOdEkKLS0tIGxnVm52TlZWSjZqeXVDT3R3bHlp
            TEVyMDRqY1Rrd2JoVjdXbGtDN3JUd0EKvu+7IuK3G1weNCV1l6dzqRmDzirNze+u
            50iMpzuJIolA73T3YzhOkcF70p4J9PkgyQDBQD2tCd6MO42X7FKnkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-22T23:12:54Z"
    mac: ENC[AES256_GCM,data:sdsXwUBePHS8DmyaYC/A+5LGULKnCNbWytGfpOuTBL9fC6cZdH7mc7JTP1+Xj3oXkIbEu/FGB64pu+k4/THKdjDOjaqEzODHQuYu1xExyDKbX6zUYoIZ6R14Ee1+cirBn865nR/b0qfBxW7A3JCrGv7gh593yYHOB2Zf2EGIqVo=,iv:c/QZptajh/EM+ouybkRGHpjcsLf49RXzH3iNfb/Ueew=,tag:EujxXE7+ah1fUqxazGFHwQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
