apiVersion: v1
kind: ConfigMap
metadata:
    name: renovate-config
    namespace: renovate
data:
    config.json: ENC[AES256_GCM,data:q+asg0hwkDmW/+7Fm7N3WbcLfrSCdTUNxxCn3OmbI71y99pc6MunNfQy27FLUbKG9Tn1Rp9fAJyfAXPNToQ3fM6yZ5S9WTz+dk/Intsz73ARNF7ltkMB4VTOtfOL7r5aFHs=,iv:5RYTTDi3PfdavZKQr/HDVr1ndM5aDXA8Ta70DrX92zE=,tag:Ajjgt1r91LueZg2AiekSRQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6d3M5eG5iMEcxZXcweUFD
            aG10Q1JYc0VlV3NrMzErRmtWQnQydllQNzE4CjM1a3EzQWFvZ0pqTU1ZWTNUWEsx
            VSs3ZllsTkJTL09zLzJyV2doaW11L2cKLS0tIHh2US9FSzVDOGl1WWJwdk4xNUNW
            aks2TjBVamZCL3drZ3owczJjZlZTTkUK+c2EGhdYuwnlcy85dEO1Sysll3bNW9sl
            cdtCzl9inZ3RWz3uG69zPU/p6DE3wVfaMcOFAG0CmJwVkcp1pMfO3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-22T23:17:07Z"
    mac: ENC[AES256_GCM,data:PEoCOUOVv8kfT6ZPjeXJj8wfH+71Il21Hh0eLe9T/bDjb+jz38Jz1aruBm3o0veUpzPPN4s/e8dXuLS/0AkJIm95EecCX+mK45eIqPOQvmV21cHBuQuMyqlS3Eqc4ZbVT2yr7FIrlILcKiyAOctkrdCXMnmKtRquGcJJp17ElEk=,iv:oqGrjR7cff4FaWlbL0Lp6OyEHbpZ6PMkgaEv9p5cGNY=,tag:69UdjOX0mTy4+oxTLJ5uTg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
