apiVersion: v1
kind: ConfigMap
metadata:
    name: renovate-config
    namespace: renovate
data:
    config.json: ENC[AES256_GCM,data:GPv7m16mGWP953YVPrtkJg3qCiiglOwQS/oWyH8FFWgM/Rsqg1hVQ+Hi5kLkJP4YGOYOuVMfXjADbasul7msCiEsBqHG7pF7w4yQxffOg5yS6QOu4v1Mux0Y6Hd1/DYA7OI=,iv:5fhtcHHGgBFdyn3TJ5Uts4z3M6MjPBWTgic/J7DUJKY=,tag:4XUTa8RVEmFZz7BimzKkLQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByMTRETjJiZkxwYjVzOUpq
            MGlzakFXSUFZOEgyWmVkRVZOMVp5Qm8rcDM0CnprNnBuT3E1dWtTQTcxVWFRMjA1
            bWpMTXQ5OENpWWhJczV0TWJBdVF5MkUKLS0tIEFFNlFOTEx2Y0xvdUZUb05oWkVL
            WCtHeWRNOWliOVo5c0ptcndtdnVRY2MKurFEGESHiTcf+C+xyyaxOlKRzCZqlXAU
            945SjKRABAcmntVHHHv+VfFKzADz1xcndWpZ/CDE6OBWmsZQJlnbeg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-19T20:19:40Z"
    mac: ENC[AES256_GCM,data:xGghVqH/ulI0aVFBMu3RW/GyAHx74JzKDtUn7/rJALEbD5WYLoxVsvVd6bvsrYf3Tdsv5VatvKv6qeaeSksg7urrzURhxkpKbcmnFrXVOjL6nY0cnBUSwUw7+5eXRCSVI0xvO9PnqVafT3nbt8L3Wv14twPm1fm74JjNq6UMu6o=,iv:f8w6w4DSOhynFHyL+7oKETxIndzGpUK/YBXUJRkX2Ds=,tag:ShVyuX2rgDBTq3kd9qKP6Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
