apiVersion: v1
kind: ConfigMap
metadata:
    name: renovate-config
    namespace: renovate
data:
    config.json: ENC[AES256_GCM,data:fgpm7QLnwbd66EsyL231QfNP8rq7GtQpgbza1Lrhh63KR32/iGJNK8viVaXE9ZBQwPN+TT8atfdztqvOaEZQZSrTzAjPzsp2vNQPFPkqAdvMQ9ZUA86D9ddX+FIaMYCer28=,iv:9fIWIOqr/7qz2sQtOlygnk+ZprvrWFEquMsu5i4X8XA=,tag:Q9yRdFNAbyltjQoIz/ae/g==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k6jfsz28cw5hux3pmpc3hlgl5z36jfwns6stn9l6337dgqyegagqc8jpa3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArVkNreFg0VEhlYlJhVER3
            Uk9FOC9vbCtGamtEWldBeUFrWGoyMnRvblVZCkQ5cWhNb0c5YlBPSFVhY3ZoT0tj
            dVNyNDFKRmM2OWNUQys4YVFnYjVjTGcKLS0tIGhkTUtHaWhvMmxFM3RFNS9sTUVk
            ZTdiSzdwTGxZV2xENVd6MW44Z3lPZGsK147ZrAXjgaGADPq0xYgSMCjtzhnXBJCM
            77fqJGXjfzyLl9VPzw7Yyk7W1U8AOmCegT4fFt6PJRHdWy/dLuXDaQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-19T21:18:14Z"
    mac: ENC[AES256_GCM,data:dwHzCQFE89VB/bobr/ed3wIUW0kAEPYbLyvGPYo1X99Xj2ld3hzuL46/nZvuzNRoj0tZlBe1Uusg7lhtPtF0eD5Y6Zdxw/sn9S4TeLXz0kgHOQSxdF2y1EH4iALnEF4xkci9h/kGs5j43jwNM4sPAiHcy80J+mh5oopQIv88sY0=,iv:rncLoK533g+9SIfm63T8McLCMUWBMLdqfPyuzogb1WA=,tag:PqwmCUGpSR2RlCYGEuApTQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
