apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: littlelink
    namespace: littlelink
spec:
    interval: 5m
    chart:
        spec:
            # renovate: registryUrl=https://charts.truechartsoci.org
            chart: littlelink
            version: 16.0.3
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
            interval: 5m
    install:
        createNamespace: true
        crds: CreateReplace
        remediation:
            retries: 3
    upgrade:
        crds: CreateReplace
        remediation:
            retries: 3
    values:
      ingress:
        main:
          enabled: true
          integrations:
            traefik:
              enabled: true
              entrypoints:
              - websecure
          hosts:
            - host: ${DOMAIN_0}
              paths:
              - path: /
                pathType: Prefix
            - host: www.${DOMAIN_0}
              paths:
              - path: /
                pathType: Prefix
      workload:
        main:
          podSpec:
            containers:
              main:
                env:
                  META_TITLE: "Alfi0812"
                  META_DESCRIPTION: "Alfi0812's Link page"
                  META_AUTHOR: "Alfi0812"
                  THEME: "Dark"
                  FAVICON_URL: "https://avatars.githubusercontent.com/u/43101280?s=400&u=aa7de93e8d79ad2bbd3fd7da643bb106e2017ba1&v=4"
                  AVATAR_URL: "https://avatars.githubusercontent.com/u/43101280?s=400&u=aa7de93e8d79ad2bbd3fd7da643bb106e2017ba1&v=4"
                  AVATAR_2X_URL: "https://avatars.githubusercontent.com/u/43101280?s=400&u=aa7de93e8d79ad2bbd3fd7da643bb106e2017ba1&v=4"
                  AVATAR_ALT: "alfi0812 profile pic"
                  NAME: "Alfi0812"
                  BIO: "Master of Science in Electrical Engineering and Information Technology"
                  GITHUB: "https://github.com/alfi0812"
                  TWITTER: "https://x.com/alfi0812"
                  DISCORD: "https://discordapp.com/users/209056319905202176"
                  FOOTER: 'Alfi0812 © {{ now | date "2006" }}'
                  EMAIL: "admin@alfi0812.de"
                  EMAIL_TEXT: "Email"
