apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: homepage
    namespace: homepage
spec:
    interval: 5m
    chart:
        spec:
            # renovate: registryUrl=https://charts.truechartsoci.org
            chart: homepage
            version: 9.7.0
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
            interval: 5m
    install:
        createNamespace: true
        crds: CreateReplace
        remediation:
            retries: 3
    upgrade:
        crds: CreateReplace
        remediation:
            retries: 3
    values:
      global:
        stopAll: false
      credentials:
        minio:
          type: s3
          url: "${S3_URL_MINIO}"
          bucket: "${S3_BUCKET}-homepage"
          accessKey: "${S3_ACCESS_KEY}"
          secretKey: "${S3_SECRET_KEY}"
          encrKey: "${S3_ENCRYPTION_KEY}"
      ingress:
        main:
          enabled: true
          integrations:
            traefik:
              enabled: true
              entrypoints:
              - websecure
              middlewares:
              - name: auth
                namespace: traefik
            certManager:
              enabled: true
              certificateIssuer: domain-1-le-prod
          hosts:
            - host: home.${DOMAIN_1}
              paths:
                - path: /
                  pathType: Prefix
      addons:
        codeserver:
          enabled: true
          ingress:
            enabled: true
            hosts:
            - host: homepage.code.${DOMAIN_1}
              paths:
              - path: /
                pathType: Prefix
            integrations:
              certManager:
                certificateIssuer: domain-1-le-prod
                enabled: true
              traefik:
                enabled: true
                entrypoints:
                - websecure
                middlewares:
                - name: auth
                  namespace: 'traefik'
      persistence:
        config:
          volsync:
          - name: config
            type: restic
            cleanupTempPVC: true
            cleanupCachePVC: true
            credentials: minio
            dest:
              enabled: true
            src:
              enabled: true
              trigger:
                schedule: 10 0 * * *
