apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: glances
    namespace: glances
spec:
    interval: 10m
    chart:
        spec:
            # renovate: registryUrl=https://charts.truechartsoci.org
            chart: glances
            version: 1.0.0
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
            interval: 5m
    install:
        createNamespace: true
        crds: CreateReplace
        remediation:
            retries: 3
    upgrade:
        crds: CreateReplace
        remediation:
            retries: 3
    values:
      workload:
        main:
          podSpec:
            # Needed for Running Tasks
            hostPID: true
            # Needed for Host Network Stats
            hostNetwork: true
            runtimeClassName: "nvidia"
      resources:
        limits:
          nvidia.com/gpu: 1
      ingress:
        main:
          enabled: false
          integrations:
            traefik:
              enabled: false
              #auth
            certManager:
              enabled: true
              certificateIssuer: domain-1-le-prod
          hosts:
            - host: glances.${DOMAIN_1}
              paths:
                - path: /
                  pathType: Prefix
