apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-service-pikvm
  namespace: external-service
spec:
  interval: 5m
  chart:
    spec:
      chart: external-service
      version: 16.0.8
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    resources:
      requests:
        cpu: 10m
    service:
      main:
        enabled: true
        externalIP: ${PIKVM_IP}
        ports:
          main:
            enabled: true
            port: 443
            protocol: http
        type: ExternalIP
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        annotations:
          nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        hosts:
        - host: kvm.${DOMAIN_1}
        integrations:
          nginx:
            enabled: true
            auth:
              type: "authelia"
              internalHost: "authelia.authelia.svc.cluster.local:9091"
              externalHost: "auth.${DOMAIN_1}"
          certManager:
            certificateIssuer: domain-1-le-prod
            enabled: true
