apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - teamspeak3/ks.yaml
  - minecraft-gate/ks.yaml
  - jts3servermod/ks.yaml
  - sinusbot/ks.yaml
  - minecraft-modpack/ks.yaml
