apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudflareddns
  namespace: cloudflareddns
spec:
  interval: 5m
  chart:
    spec:
      chart: cloudflareddns
      version: 12.1.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    resources:
        requests:
          cpu: 10m
    credentials:
      minio:
        type: s3
        url: "https://${S3_URL_MINIO}"
        bucket: "${S3_BUCKET}-cloudflareddns"
        accessKey: "${S3_ACCESS_KEY}"
        secretKey: "${S3_SECRET_KEY}"
        encrKey: "${S3_ENCRYPTION_KEY}"
    cloudflareddns:
      api_token: ${CLOUDFLARE_TOKEN}
      host_zone_record:
      - domain: minecraft.${DOMAIN_0}
        record: A
        zone: ${ZONE_0}
      - domain: wireguard.${DOMAIN_1}
        record: A
        zone: ${ZONE_1}
    persistence:
      config:
        volsync:
        - name: config
          type: restic
          credentials: minio
          dest:
            enabled: true
          src:
            enabled: true
            trigger:
              schedule: 10 0 * * *
