---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 15m
  chart:
    spec:
      chart: traefik
      version: 30.0.4
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      stopAll: false
    defaultCertificate: "domain-0-wildcard"
    workload:
      main:
        replicas: 1
        strategy: RollingUpdate
    service:
      main:
        type: ClusterIP
      tcp:
        loadBalancerIP: ${TRAEFIK_IP}
        type: LoadBalancer
        externalTrafficPolicy: Local
        ports:
          web:
            enabled: true
            port: 80
            protocol: http
            redirectTo: websecure
            forwardedHeaders:
              enabled: true
              # -- List of trusted IP and CIDR references
              trustedIPs:
              - 172.16.0.0/16
              - 172.17.0.0/16
              # -- Trust all forwarded headers
              insecureMode: false
            # -- Configure (Proxy Protocol Headers)[https://doc.traefik.io/traefik/routing/entrypoints/#proxyprotocol] Support
            proxyProtocol:
              enabled: true
              # -- Only IPs in trustedIPs will lead to remote client address replacement
              trustedIPs:
              - 172.16.0.0/16
              - 172.17.0.0/16
              # -- Trust every incoming connection
              insecureMode: false
          websecure:
            enabled: true
            port: 443
            protocol: https
            # -- Configure (Forwarded Headers)[https://doc.traefik.io/traefik/routing/entrypoints/#forwarded-headers] Support
            forwardedHeaders:
              enabled: true
              # -- List of trusted IP and CIDR references
              trustedIPs:
              - 172.16.0.0/16
              - 172.17.0.0/16
              # -- Trust all forwarded headers
              insecureMode: false
            # -- Configure (Proxy Protocol Headers)[https://doc.traefik.io/traefik/routing/entrypoints/#proxyprotocol] Support
            proxyProtocol:
              enabled: true
              # -- Only IPs in trustedIPs will lead to remote client address replacement
              trustedIPs:              
              - 172.16.0.0/16
              - 172.17.0.0/16
              # -- Trust every incoming connection
              insecureMode: false
    middlewares:
      addPrefix:
        - name: pihole-add
          prefix: /admin
      forwardAuth:
        - address: ${AUTH}
          authRequestHeaders: []
          authResponseHeaders:
          - Remote-User
          - Remote-Groups
          - Remote-Name
          - Remote-Email
          authResponseHeadersRegex: ''
          name: auth
          tls:
            insecureSkipVerify: false
          trustForwardHeader: true
      ipWhiteList:
        - name: vaultwarden
          sourceRange:
            - 192.168.178.0/24
      redirectRegex:
        - name: pihole-regex
          permanent: false
          regex: /admin/$
          replacement: /
        - name: chrome-regex
          permanent: false
          regex: //$
          replacement: /
        - name: traefik-regex
          permanent: false
          regex: ${REGEX}
          replacement: ${REPLACEMENT}
      themePark:
        - name: torrent
          appName: "qbittorrent"
          themeName : "dracula"
          baseUrl: https://theme-park.dev
    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
            entrypoints:
            - websecure
            middlewares:
            - name: traefik-regex
              namespace: traefik
            - name: auth
              namespace: traefik
            fixedMiddlewares:
            - name: chain-basic
              namespace: traefik
          certManager:
            enabled: true
            certificateIssuer: domain-1-le-prod
        hosts:
          - host: traefik.${DOMAIN_1}
            paths:
              - path: /
                pathType: Prefix
