apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: hammond
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/main/kubernetes/general/hammond/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster
