apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: code-server
    namespace: code-server
spec:
    interval: 5m
    chart:
        spec:
            # renovate: registryUrl=https://charts.truechartsoci.org
            chart: code-server
            version: 13.10.0
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
            interval: 5m
    install:
        createNamespace: true
        crds: CreateReplace
        remediation:
            retries: 3
    upgrade:
        crds: CreateReplace
        remediation:
            retries: 3
    timeout: 20m
    values:
      global:
        stopAll: false
      portal:
        open:
          enabled: false
      credentials:
        minio:
          type: s3
          url: "${S3_URL_MINIO}"
          bucket: "${S3_BUCKET}-code-server"
          accessKey: "${S3_ACCESS_KEY}"
          secretKey: "${S3_SECRET_KEY}"
          encrKey: "${S3_ENCRYPTION_KEY}"
      ingress:
        main:
          enabled: true
          integrations:
            traefik:
              enabled: true
              entrypoints:
              - websecure
              middlewares:
              - name: auth
                namespace: traefik
            certManager:
              enabled: true
              certificateIssuer: domain-1-le-prod
          hosts:
            - host: code.${DOMAIN_1}
              paths:
                - path: /
                  pathType: Prefix
      persistence:
        config:
          volsync:
          - name: config
            cleanupTempPVC: true
            cleanupCachePVC: true
            type: restic
            credentials: minio
            dest:
              enabled: true
            src:
              enabled: true
              trigger:
                schedule: 10 0 * * *
