apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sinusbot
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/gaming/sinusbot/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster
  dependsOn:
  - name: teamspeak3
