apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: minecraft-gate
    namespace: minecraft
spec:
    interval: 5m
    chart:
        spec:
            # renovate: registryUrl=https://charts.truechartsoci.org
            chart: minecraft-gate
            version: 1.2.0
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
            interval: 5m
    install:
        createNamespace: true
        crds: CreateReplace
        remediation:
            retries: 3
    upgrade:
        crds: CreateReplace
        remediation:
            retries: 3
    values:
      global:
        stopAll: false
      credentials:
        minio:
          type: s3
          url: "${S3_URL_MINIO}"
          bucket: "${S3_BUCKET}-minecraft-gate"
          accessKey: "${S3_ACCESS_KEY}"
          secretKey: "${S3_SECRET_KEY}"
          encrKey: "${S3_ENCRYPTION_KEY}"
      service:
        main:
          loadBalancerIP: ${MINECRAFT_IP}
          type: LoadBalancer
      persistence:
        icons:
          enabled: true
          mountPath: /icons
          volsync:
            - name: icons
              type: restic
              credentials: minio
              cleanupTempPVC: true
              cleanupCachePVC: true
              dest:
                enabled: true
              src:
                enabled: true
                trigger:
                  schedule: 10 1 * * *

      configmap:
        config:
          enabled: true
          data:
            config.yml: |
              config:
                bind: 0.0.0.0:{{ .Values.service.main.ports.main.port }}
                onlineMode: true
                debug: true
                query:
                  enabled: true
                  port: {{ .Values.service.main.ports.query.port }}
                  showPlugins: false
                lite:
                  enabled: true
                  routes:
                    - host: [modpack.${DOMAIN_0}]
                      backend: minecraft-modpack-minecraft-java.minecraft.svc.cluster.local:25565
                      cachePingTTL: -1s
                      fallback:
                        motd: |
                          §cModpack server is offline.
                          §eCheck back later!
                        version:
                          name: '§cTry again later!'
                          protocol: -1
                        favicon: /icons/server-icon.png
                    - host: [tcpshield.${DOMAIN_0}, ${DOMAIN_0}]
                      backend: minecraft-vanilla-minecraft-java.minecraft.svc.cluster.local:25565
                      cachePingTTL: -1s
                      fallback:
                        motd: |
                          §cModpack server is offline.
                          §eCheck back later!
                        version:
                          name: '§cTry again later!'
                          protocol: -1
                        favicon: /icons/server-icon.png


