apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: vaultwarden
    namespace: vaultwarden
spec:
    interval: 5m
    chart:
        spec:
            # renovate: registryUrl=https://charts.truechartsoci.org
            chart: vaultwarden
            version: 28.8.3
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
            interval: 5m
    install:
        createNamespace: true
        crds: CreateReplace
        remediation:
            retries: 3
    upgrade:
        crds: CreateReplace
        remediation:
            retries: 3
    values:
      global:
        stopAll: false
      credentials:
        minio:
          type: s3
          url: "${S3_URL_MINIO}"
          bucket: "${S3_BUCKET}-vaultwarden"
          accessKey: "${S3_ACCESS_KEY}"
          secretKey: "${S3_SECRET_KEY}"
          encrKey: "${S3_ENCRYPTION_KEY}"
      ingress:
        main:
          enabled: false
          integrations:
            traefik:
              enabled: false
            certManager:
              enabled: true
              certificateIssuer: domain-1-le-prod
          hosts:
            - host: vault.${DOMAIN_1}
              paths:
                - path: /
                  pathType: Prefix
        admin:
          enabled: true
          primary: false
          targetSelector:
            main: main
          integrations:
            traefik:
              enabled: true
              entrypoints:
              - websecure
              middlewares:
              - name: vaultwarden
                namespace: traefik
              - name: auth
                namespace: traefik
              - name: real-ip
                namespace: traefik
              enableFixedMiddlewares: true
              forceTLS: true
              allowCors: false
            certManager:
              enabled: true
              certificateIssuer: domain-1-le-prod
          hosts:
            - host: vault.${DOMAIN_1}
              paths:
                - path: /admin
                  pathType: Prefix
      persistence:
        data:
          volsync:
          - name: data
            type: restic
            credentials: minio
            dest:
              enabled: true
            src:
              enabled: true
              trigger:
                schedule: 40 1 * * *
      cnpg:
        main:
          cluster:
            singleNode: true
          backups:
            enabled: true
            credentials: minio
            scheduledBackups:
              - name: daily-backup
                schedule: "0 5 0 * * *"
                backupOwnerReference: self
                immediate: true
                suspend: false
          recovery:
            method: object_store
            credentials: minio
      vaultwarden:
        admin:
          enabled: true
          token: ${VAULTWARDEN_ADMIN_TOKEN}
        allowSignups: false
        log:
          level: info
        push:
          enabled: true
          installationId: ${VAULTWARDEN_PUSH_ID}
          installationKey: ${VAULTWARDEN_PUSH_KEY}
        yubico:
          clientId: ${YUBICO_ID}
          enabled: true
          secretKey: ${YUBICO_SECRET}
          server: ''
        smtp:
          enabled: true
          host: ${SMTP_HOST}
          from: vaultwarden@${DOMAIN_1}
          port: 587
          security: starttls
          user: ${SMTP_USER}
          password: ${SMTP_PASSWORD_VAULTWARDEN}

      workload:
        main:
          podSpec:
            containers:
              main:
                advanced: false
                env:
                  EXPERIMENTAL_CLIENT_FEATURE_FLAGS: autofill-overlay,autofill-v2
