---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole
  namespace: pihole
spec:
  interval: 15m
  chart:
    spec:
      chart: pihole
      version: 19.1.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 5m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      stopAll: false
    credentials:
      minio:
        type: s3
        url: "${S3_URL_MINIO}"
        bucket: "${S3_BUCKET}-pihole"
        accessKey: "${S3_ACCESS_KEY}"
        secretKey: "${S3_SECRET_KEY}"
        encrKey: "${S3_ENCRYPTION_KEY}"
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                FTLCONF_dns_upstreams: ${BLOCKY_IP}
                FTLCONF_webserver_api_password: ''
    service:
      dns:
        loadBalancerIP: ${PIHOLE_IP}
        type: LoadBalancer
    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
            entrypoints:
            - websecure
            middlewares:
            - name: auth
              namespace: traefik
            - name: pihole
              namespace: traefik
          certManager:
            enabled: true
            certificateIssuer: domain-1-le-prod
        hosts:
          - host: pihole.${DOMAIN_1}
            paths:
              - path: /
                pathType: Prefix
    persistence:
      config:
        volsync:
        - name: config
          type: restic
          cleanupTempPVC: true
          cleanupCachePVC: true
          credentials: minio
          dest:
            enabled: true
          src:
            enabled: true
            trigger:
              schedule: 20 1 * * *
      dnsmasq:
        volsync:
        - name: dnsmasq
          type: restic
          cleanupTempPVC: true
          cleanupCachePVC: true
          credentials: minio
          dest:
            enabled: true
          src:
            enabled: true
            trigger:
              schedule: 20 1 * * *
