---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wg-easy
  namespace: wg-easy
spec:
  interval: 15m
  chart:
    spec:
      chart: wg-easy
      version: 16.4.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 5m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      stopAll: false
    credentials:
      minio:
          type: s3
          url: "${S3_URL_MINIO}"
          bucket: "${S3_BUCKET}-wg-easy"
          accessKey: "${S3_ACCESS_KEY}"
          secretKey: "${S3_SECRET_KEY}"
          encrKey: "${S3_ENCRYPTION_KEY}"
    service:
      vpn:
        loadBalancerIP: ${WG_EASY_IP}
        type: LoadBalancer
        externalTrafficPolicy: Local
    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
            entrypoints:
            - websecure
            middlewares:
            - name: auth
              namespace: traefik
          certManager:
            enabled: true
            certificateIssuer: domain-1-le-prod
        hosts:
          - host: vpn.${DOMAIN_1}
            paths:
              - path: /
                pathType: Prefix
    persistence:
      config:
        volsync:
        - name: config
          type: restic
          cleanupTempPVC: true
          cleanupCachePVC: true
          credentials: minio
          dest:
            enabled: true
          src:
            enabled: true
            trigger:
              schedule: 40 1 * * *
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                WG_HOST: wireguard.${DOMAIN_1}
                WG_MTU: 1350
                WG_DEFAULT_DNS: ${PIHOLE_IP}
                PASSWORD_HASH: ${WG_EASY_PASSWORD}
                UI_TRAFFIC_STATS: "true"
    securityContext:
      container:
        PUID: 0
        UMASK: '0022'
        advanced: false
        capabilities:
          add:
          - NET_ADMIN
          - NET_RAW
          - SYS_MODULE
        readOnlyRootFilesystem: false
        runAsGroup: 0
        runAsNonRoot: false
        runAsUser: 0
        privileged: true
