apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: minecraft-modpack
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/gaming/minecraft-modpack/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster
